<?php

declare(strict_types=1);

namespace Tessero\Tests\Parity;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use Tessero\DType;
use Tessero\Fft\Fft;
use Tessero\Io\Npy;
use Tessero\Linalg\Linalg;
use Tessero\NDArray;
use Tessero\Mdp\MarkovDecisionProcess;
use Tessero\Optimize\LeastSquares;
use Tessero\Optimize\LinearProgramming;
use Tessero\Optimize\Minimize;
use Tessero\Optimize\Root;
use Tessero\Random\Generator;
use Tessero\Sparse\CsrMatrix;

/**
 * Replays tests/fixtures/parity.json (generated by NumPy/SciPy) through Tessero.
 */
final class ParityTest extends TestCase
{
    private static ?array $fixture = null;

    public static function cases(): iterable
    {
        self::$fixture ??= json_decode((string) file_get_contents(__DIR__ . '/../fixtures/parity.json'), true, 512, JSON_THROW_ON_ERROR);
        foreach (self::$fixture['cases'] as $i => $case) {
            $label = sprintf('%03d %s %s', $i, $case['family'], is_string($case['op'] ?? null) ? $case['op'] : '');
            yield $label => [$case];
        }
    }

    #[DataProvider('cases')]
    public function testCase(array $c): void
    {
        $method = 'run' . str_replace('_', '', ucwords($c['family'], '_'));
        $this->{$method}($c);
    }

    // ------------------------------------------------------------------ families

    private function runBinary(array $c): void
    {
        $a = self::arr($c['a']);
        $b = self::arr($c['b']);
        $this->near($c['expect'], $a->{$c['op']}($b), 1e-12, "{$c['op']}");
    }

    private function runBinaryScalar(array $c): void
    {
        $a = self::arr($c['a']);
        $b = self::scalar($c['b']);
        $this->near($c['expect'], $a->{$c['op']}($b), 1e-12, "{$c['op']} scalar");
    }

    private function runUnary(array $c): void
    {
        $this->near($c['expect'], self::arr($c['a'])->{$c['op']}(), 1e-13, $c['op']);
    }

    private function runReduce(array $c): void
    {
        $a = self::arr($c['a']);
        $op = $c['op'];
        $axis = $c['axis'];
        $r = match ($op) {
            'var', 'std' => $a->{$op}($axis, $c['ddof']),
            'cumsum', 'cumprod' => $a->{$op}($axis),
            default => $a->{$op}($axis),
        };
        $this->near($c['expect'], $r, 1e-12, "{$op} axis " . json_encode($axis));
    }

    private function runReduceRng(array $c): void
    {
        $x = Generator::defaultRng($c['seed'])->random($c['n']);
        [$sum, $mean, $std, $max, $argmax] = $c['expect'];
        $this->near($sum, $x->sum(), 1e-13, 'pairwise sum of 1M');
        $this->near($mean, $x->mean(), 1e-13, 'mean');
        $this->near($std, $x->std(), 1e-12, 'std');
        $this->near($max, $x->max(), 0.0, 'max');
        $this->assertSame($argmax, $x->argmax());
    }

    private function runSlice(array $c): void
    {
        $this->near($c['expect'], self::arr($c['a'])[$c['spec']], 0.0, "slice {$c['spec']}");
    }

    private function runTake(array $c): void
    {
        $this->near($c['expect'], self::arr($c['a'])->take($c['indices'], $c['axis']), 0.0, 'take');
    }

    private function runMask(array $c): void
    {
        $a = self::arr($c['a']);
        $this->near($c['expect'], $a[$a->gt($c['threshold'])], 0.0, 'mask');
    }

    private function runSort(array $c): void
    {
        $this->near($c['expect'], self::arr($c['a'])->sort($c['axis']), 0.0, 'sort');
    }

    private function runArgsort(array $c): void
    {
        $this->near($c['expect'], self::arr($c['a'])->argsort($c['axis']), 0.0, 'argsort');
    }

    private function runTransposeMatmul(array $c): void
    {
        $this->near($c['expect'], self::arr($c['a'])->matmul(self::arr($c['b'])->t()), 1e-12, 'a @ b.T');
    }

    private function runMatmul(array $c): void
    {
        $this->near($c['expect'], self::arr($c['a'])->matmul(self::arr($c['b'])), 1e-12, 'batched matmul');
    }

    private function runWhere(array $c): void
    {
        $this->near($c['expect'], NDArray::where(self::arr($c['c']), self::arr($c['a']), self::arr($c['b'])), 0.0, 'where');
    }

    private function runConcatenate(array $c): void
    {
        $this->near($c['expect'], NDArray::concatenate([self::arr($c['a']), self::arr($c['b'])], $c['axis']), 0.0, 'concatenate');
    }

    private function runLinalg(array $c): void
    {
        $a = self::arr($c['a']);
        $e = $c['expect'];
        $tol = 1e-9;
        switch ($c['op']) {
            case 'solve':
                $this->near($e, Linalg::solve($a, self::arr($c['b'])), $tol, 'solve');
                break;
            case 'inv':
                $this->near($e, Linalg::inv($a), $tol, 'inv');
                break;
            case 'det':
                $this->near($e, Linalg::det($a), $tol, 'det');
                break;
            case 'det_stack':
                $this->near($e, Linalg::det($a), $tol, 'stacked det');
                break;
            case 'slogdet':
                [$s, $l] = Linalg::slogdet($a);
                $this->near($e[0], $s, 0.0, 'sign');
                $this->near($e[1], $l, $tol, 'logdet');
                break;
            case 'cholesky':
                $this->near($e, Linalg::cholesky($a), $tol, 'cholesky');
                break;
            case 'qr':
                [$q, $r] = Linalg::qr($a);
                $this->near($e[0], $q, $tol, 'Q');
                $this->near($e[1], $r, $tol, 'R');
                break;
            case 'qr_complete':
                [$q, $r] = Linalg::qr($a, 'complete');
                $this->near($e[0], $q, $tol, 'Q complete');
                $this->near($e[1], $r, $tol, 'R complete');
                break;
            case 'eigh':
                [$w, $v] = Linalg::eigh($a);
                $this->near($e[0], $w, $tol, 'eigenvalues');
                $this->near($e[1], self::alignSigns($v, self::arr($e[1])), $tol, 'eigenvectors (up to sign)');
                break;
            case 'svd':
            case 'svd_full':
                [$u, $s, $vt] = Linalg::svd($a, $c['op'] === 'svd_full');
                $this->near($e[1], $s, $tol, 'singular values');
                $recon = $u->slice(':', '0:' . $s->size())->mul($s)->matmul($vt->slice('0:' . $s->size(), ':'));
                $this->near($c['a'], $recon, 1e-9, 'U S Vt reconstructs A');
                $this->assertSame(self::arr($e[0])->shape(), $u->shape());
                $this->assertSame(self::arr($e[2])->shape(), $vt->shape());
                break;
            case 'pinv':
                $this->near($e, Linalg::pinv($a), $tol, 'pinv');
                break;
            case 'lstsq':
                [$x, $res, $rank, $sv] = Linalg::lstsq($a, self::arr($c['b']));
                $this->near($e[0], $x, $tol, 'lstsq x');
                $this->near($e[1], $res, 1e-8, 'residuals');
                $this->assertSame($e[2], $rank);
                $this->near($e[3], $sv, $tol, 'sv');
                break;
            case 'eigvals':
                $w = Linalg::eigvals($a);
                $pairs = $w->dtype() === DType::Complex128 ? $w->toArray() : array_map(static fn ($v): array => [$v, 0.0], $w->toArray());
                usort($pairs, static fn (array $p, array $q): int => [$p[0], $p[1]] <=> [$q[0], $q[1]]);
                $this->near($e, NDArray::complex(array_column($pairs, 0), array_column($pairs, 1)), 1e-9, 'eigenvalues (sorted)');
                break;
            case 'norm_fro':
                $this->near($e, Linalg::norm($a), $tol, 'fro');
                break;
            case 'norm_2':
                $this->near($e, Linalg::norm($a, 2), $tol, '2-norm');
                break;
            case 'norm_1':
                $this->near($e, Linalg::norm($a, 1), $tol, '1-norm');
                break;
            case 'norm_nuc':
                $this->near($e, Linalg::norm($a, 'nuc'), $tol, 'nuc');
                break;
            case 'cond':
                $this->near($e, Linalg::cond($a), 1e-8, 'cond');
                break;
            case 'matrix_rank':
                $this->assertSame($e, Linalg::matrixRank($a));
                break;
            case 'lu':
                [$p, $l, $u] = Linalg::lu($a);
                $this->near($e[0], $p, 0.0, 'P');
                $this->near($e[1], $l, $tol, 'L');
                $this->near($e[2], $u, $tol, 'U');
                break;
            case 'solve_triangular':
                $this->near($e, Linalg::solveTriangular($a, self::arr($c['b'])), $tol, 'solve_triangular');
                break;
            default:
                $this->fail('unknown linalg op ' . $c['op']);
        }
    }

    private function runFft(array $c): void
    {
        $tol = 1e-10;
        $e = $c['expect'];
        switch ($c['op']) {
            case 'fft':
                $this->near($e, Fft::fft(NDArray::complex(self::arr($c['re']), self::arr($c['im']))), $tol, 'fft n=' . $c['re']['shape'][0]);
                break;
            case 'rfft':
                $this->near($e, Fft::rfft(self::arr($c['re'])), $tol, 'rfft');
                break;
            case 'irfft':
                $this->near($e, Fft::irfft(self::arr($c['spec']), $c['n']), $tol, 'irfft');
                break;
            case 'fft_axis0':
                $this->near($e, Fft::fft(self::arr($c['re']), null, 0), $tol, 'fft axis 0');
                break;
            case 'ifft':
                $this->near($e, Fft::ifft(self::arr($c['re'])), $tol, 'ifft');
                break;
            case 'fft_n':
                $this->near($e, Fft::fft(self::arr($c['re']), $c['n']), $tol, 'fft zero-padded');
                break;
            case 'fft_ortho':
                $this->near($e, Fft::fft(self::arr($c['re']), norm: 'ortho'), $tol, 'ortho');
                break;
            case 'fftfreq':
                $this->near($e, Fft::fftfreq($c['n'], (float) $c['d']), 1e-15, 'fftfreq');
                break;
            case 'fftshift':
                $this->near($e, Fft::fftshift(self::arr($c['re'])), 0.0, 'fftshift');
                break;
            case 'fft2':
                $this->near($e, Fft::fft2(self::arr($c['re'])), $tol, 'fft2');
                break;
        }
    }

    private function runRandom(array $c): void
    {
        $g = Generator::defaultRng($c['seed']);
        $e = $c['expect'];
        $label = 'seed ' . json_encode($c['seed']) . ' ' . $c['op'];
        switch ($c['op']) {
            case 'random':
                $this->near($e, $g->random($c['size']), 0.0, $label);
                break;
            case 'normal':
                $this->near($e, $g->normal((float) $c['loc'], (float) $c['scale'], $c['size']), 0.0, $label);
                break;
            case 'integers':
            case 'integers_big':
                $this->near($e, $g->integers($c['low'], $c['high'], $c['size']), 0.0, $label);
                break;
            case 'permutation':
                $this->near($e, $g->permutation($c['size']), 0.0, $label);
                break;
            case 'uniform':
                $this->near($e, $g->uniform((float) $c['low'], (float) $c['high'], $c['size']), 0.0, $label);
                break;
            case 'choice_p':
                $this->near($e, $g->choice(4, $c['size'], true, array_map('floatval', $c['p'])), 0.0, $label);
                break;
            case 'mixed':
                $this->near($e[0], $g->random(3), 0.0, $label . ' random');
                $this->near($e[1], $g->integers(0, 10, 3), 0.0, $label . ' integers (32-bit buffer)');
                $this->near($e[2], $g->normal(size: 3), 0.0, $label . ' normal');
                $this->near($e[3], $g->integers(0, 10, 3), 0.0, $label . ' integers again');
                break;
            case 'normal_many':
                $this->near($e, $g->normal(size: $c['size'])->slice('-5:'), 0.0, $label);
                break;
        }
    }

    private function runSparse(array $c): void
    {
        switch ($c['op']) {
            case 'csr':
                $m = CsrMatrix::fromDense(self::arr($c['a']));
                $this->near($c['expect'][0], $m->indptr(), 0.0, 'indptr');
                $this->near($c['expect'][1], $m->indices(), 0.0, 'indices');
                $this->near($c['expect'][2], $m->data(), 0.0, 'data');
                $this->near($c['a'], $m->toDense(), 0.0, 'round trip');
                break;
            case 'matvec':
                $this->near($c['expect'], CsrMatrix::fromDense(self::arr($c['a']))->dot(self::arr($c['x'])), 1e-13, 'matvec');
                break;
            case 'transpose_matvec':
                $this->near($c['expect'], CsrMatrix::fromDense(self::arr($c['a']))->transpose()->dot(self::arr($c['x'])), 1e-13, 'A^T x');
                break;
            case 'cg':
                [$x, $info] = CsrMatrix::fromDense(self::arr($c['a']))->cg(self::arr($c['b']), rtol: 1e-12);
                $this->assertSame(0, $info);
                $this->near($c['expect'], $x, 1e-9, 'cg vs spsolve');
                break;
            case 'triplets':
                $m = CsrMatrix::fromTriplets($c['rows'], $c['cols'], array_map('floatval', $c['vals']), $c['shape']);
                $this->near($c['expect'], $m->toDense(), 0.0, 'coo -> csr sums duplicates');
                break;
        }
    }

    private function runOptimize(array $c): void
    {
        $rosen = static function (array $x): float {
            $s = 0.0;
            for ($i = 0; $i < count($x) - 1; $i++) {
                $s += 100.0 * ($x[$i + 1] - $x[$i] ** 2.0) ** 2.0 + (1 - $x[$i]) ** 2.0;
            }

            return $s;
        };
        $rosenDer = static function (array $x): array {
            $n = count($x);
            $d = array_fill(0, $n, 0.0);
            for ($i = 1; $i < $n - 1; $i++) {
                $d[$i] = 200 * ($x[$i] - $x[$i - 1] ** 2) - 400 * ($x[$i + 1] - $x[$i] ** 2) * $x[$i] - 2 * (1 - $x[$i]);
            }
            $d[0] = -400 * $x[0] * ($x[1] - $x[0] ** 2) - 2 * (1 - $x[0]);
            $d[$n - 1] = 200 * ($x[$n - 1] - $x[$n - 2] ** 2);

            return $d;
        };
        $e = $c['expect'];
        switch ($c['op']) {
            case 'nelder_mead_rosen':
                $r = Minimize::minimize($rosen, array_map('floatval', $c['x0']), method: 'Nelder-Mead');
                $this->near($e['x'], $r->x, 1e-12, 'Nelder-Mead x (same iterates as scipy)');
                $this->assertSame($e['nit'], $r->nit, 'nit');
                $this->assertSame($e['nfev'], $r->nfev, 'nfev');
                break;
            case 'bfgs_rosen':
                $r = Minimize::minimize($rosen, array_map('floatval', $c['x0']), $rosenDer, 'BFGS');
                $this->assertTrue($r->success, $r->message);
                $this->near($e['x'], $r->x, 1e-5, 'BFGS x');
                break;
            case 'bfgs_rosen_fd':
                $r = Minimize::minimize($rosen, array_map('floatval', $c['x0']));
                $this->near($e['x'], $r->x, 1e-4, 'BFGS finite-difference x');
                break;
            case 'lbfgsb_bounded':
                $r = Minimize::minimize($rosen, array_map('floatval', $c['x0']), $rosenDer, 'L-BFGS-B', array_map(static fn (array $b): array => array_map('floatval', $b), $c['bounds']), ['gtol' => 1e-10, 'ftol' => 1e-15]);
                $this->assertTrue($r->success, $r->message);
                $this->near($e['x'], $r->x, 1e-5, 'bounded x');
                $this->near($e['fun'], $r->fun, 1e-8, 'bounded f');
                break;
            case 'brentq':
            case 'brentq_cos':
                $fn = $c['op'] === 'brentq' ? static fn (float $x): float => $x ** 3 - 2 * $x - 5 : static fn (float $x): float => cos($x) - $x;
                $r = Root::brentq($fn, (float) $c['a'], (float) $c['b'], fullOutput: true);
                $this->near($e['root'], $r['root'], 0.0, 'brentq root (bit-identical)');
                $this->assertSame($e['iterations'], $r['iterations']);
                $this->assertSame($e['function_calls'], $r['function_calls']);
                break;
            case 'newton_secant':
                $this->near($e, Root::newton(static fn (float $x): float => $x ** 3 - 2 * $x - 5, (float) $c['x0']), 1e-12, 'secant');
                break;
            case 'root_system':
                $r = Root::root(static fn (array $v): array => [$v[0] + 0.5 * ($v[0] - $v[1]) ** 3 - 1.0, 0.5 * ($v[1] - $v[0]) ** 3 + $v[1]], [0.0, 0.0]);
                $this->assertTrue($r->success, $r->message);
                $this->near($e, $r->x, 1e-8, 'root');
                break;
            case 'curve_fit':
                [$popt, $pcov] = LeastSquares::curveFit(static fn (float $x, float $a, float $b, float $cc): float => $a * exp(-$b * $x) + $cc,
                    self::arr($c['x'])->toList(), self::arr($c['y'])->toList(), array_map('floatval', $c['p0']));
                $this->near($e[0], $popt, 1e-6, 'popt');
                $this->near($e[1], $pcov, 1e-4, 'pcov');
                break;
        }
    }

    private function runLp(array $c): void
    {
        $e = $c['expect'];
        $num = static fn (array $xs): array => array_map(static fn ($v) => $v === null ? null : self::num($v), $xs);
        if ($c['op'] === 'milp') {
            $n = count($c['c']['data']);
            $r = LinearProgramming::milp(self::arr($c['c']), array_map('boolval', $c['integrality']['data']), self::arr($c['A_ub']), self::arr($c['b_ub']),
                bounds: array_map(static fn ($u): array => [0.0, self::num($u)], $c['ub']['data']));
            $this->assertSame($e['status'], $r->status, 'milp status');
            $this->near($e['fun'], $r->fun, 1e-9, 'milp objective');
            $this->assertSame($n, count($r->x));

            return;
        }
        $bounds = array_map($num, $c['bounds']);
        $hasEq = $c['A_eq']['shape'][0] > 0;
        $r = LinearProgramming::linprog(self::arr($c['c']), self::arr($c['A_ub']), self::arr($c['b_ub']),
            $hasEq ? self::arr($c['A_eq']) : null, $hasEq ? self::arr($c['b_eq']) : null, $bounds);
        $this->assertSame($e['status'], $r->status, 'linprog status: ' . $r->message);
        if ($e['status'] !== 0) {
            return;
        }
        $this->near($e['fun'], $r->fun, 1e-9, 'objective');
        $this->near($e['x'], $r->x, 1e-7, 'x');
        $this->near($e['ineq'], $r->ineqlinMarginals, 1e-7, 'A_ub marginals');
        if ($e['eq'] !== null) {
            $this->near($e['eq'], $r->eqlinMarginals, 1e-7, 'A_eq marginals');
        }
    }

    private function runMdp(array $c): void
    {
        $mdp = MarkovDecisionProcess::fromDense(self::arr($c['P']), self::arr($c['R']));
        $g = (float) $c['gamma'];
        $pi = $mdp->policyIteration($g);
        $this->assertTrue($pi->converged);
        $this->near($c['expect_policy'], $pi->policy, 0.0, 'policy iteration policy');
        $this->near($c['expect_V'], $pi->values, 1e-10, 'policy iteration values');
        $vi = $mdp->valueIteration($g, epsilon: 1e-9, maxIter: 100_000);
        $this->assertTrue($vi->converged);
        $this->near($c['expect_policy'], $vi->policy, 0.0, 'value iteration policy');
        $this->near($c['expect_V'], $vi->values, 1e-6, 'value iteration values');
        $mpi = $mdp->policyIteration($g, evalSweeps: 25, epsilon: 1e-9, maxIter: 100_000);
        $this->near($c['expect_policy'], $mpi->policy, 0.0, 'modified policy iteration policy');
        $this->near($c['expect_Q'], $mdp->qValues($pi->values, $g), 1e-10, 'Q values');
        $this->near($c['expect_eval'], $mdp->evaluate(self::arr($c['eval_policy']), $g), 1e-10, 'policy evaluation');
        $fh = $mdp->finiteHorizon(5);
        $this->near($c['expect_fh_V'], $fh['values'], 1e-12, 'finite-horizon values');
        $this->near($c['expect_fh_policy'], $fh['policy'], 0.0, 'finite-horizon policy');
        // the sparse constructor must give the same answer
        $csr = [];
        $P = self::arr($c['P']);
        for ($a = 0; $a < $c['A']; $a++) {
            $csr[] = \Tessero\Sparse\CsrMatrix::fromDense($P->slice($a));
        }
        $sp = MarkovDecisionProcess::fromSparse($csr, self::arr($c['R']))->policyIteration($g);
        $this->near($c['expect_policy'], $sp->policy, 0.0, 'sparse model policy');
    }

    public function testNpyInterop(): void
    {
        $dir = __DIR__ . '/../fixtures/';
        $this->assertSame(NDArray::arange(12.0)->reshape(3, 4)->div(7)->toArray(), Npy::load($dir . 'numpy_f8.npy')->toArray());
        $fortran = Npy::load($dir . 'numpy_i4_fortran.npy');
        $this->assertSame(DType::Int32, $fortran->dtype());
        $this->assertSame([[0, 1, 2], [3, 4, 5]], $fortran->toArray());
        $c = Npy::load($dir . 'numpy_c16.npy');
        $this->assertSame([[1.0, 2.0], [-3.5, -0.25]], $c->toArray());
        $tmp = tempnam(sys_get_temp_dir(), 'tsr') . '.npy';
        $x = NDArray::arange(24)->reshape(2, 3, 4)->astype('float32');
        Npy::save($tmp, $x);
        $this->assertSame($x->toArray(), Npy::load($tmp)->toArray());
        $this->assertSame(0, (strlen(Npy::encode($x)) - $x->nbytes()) % 64, 'header padded to 64 bytes keeps data aligned');
        @unlink($tmp);
    }

    // ------------------------------------------------------------------ helpers

    private static function arr(array $enc): NDArray
    {
        $dtype = DType::from_($enc['dtype']);
        if ($dtype === DType::Complex128) {
            $flat = array_map([self::class, 'num'], $enc['data']);
            $re = [];
            $im = [];
            for ($i = 0; $i < count($flat); $i += 2) {
                $re[] = $flat[$i];
                $im[] = $flat[$i + 1];
            }

            return NDArray::complex(NDArray::fromFlat($re, $enc['shape']), NDArray::fromFlat($im, $enc['shape']));
        }
        $data = $dtype->isFloat() ? array_map([self::class, 'num'], $enc['data']) : $enc['data'];

        return NDArray::fromFlat($data, $enc['shape'], $dtype);
    }

    private static function scalar(mixed $v): int|float
    {
        return is_string($v) ? self::num($v) : $v;
    }

    private static function num(mixed $v): float
    {
        return match ($v) {
            'nan' => NAN,
            'inf' => INF,
            '-inf' => -INF,
            default => (float) $v,
        };
    }

    /** Flip eigenvector columns so each matches the reference sign. */
    private static function alignSigns(NDArray $v, NDArray $ref): NDArray
    {
        $signs = $v->mul($ref)->sum(0)->ge(0)->astype(DType::Float64)->mul(2)->sub(1);

        return $v->mul($signs);
    }

    private function near(mixed $expected, mixed $actual, float $rtol, string $what): void
    {
        if (is_array($expected) && isset($expected['shape'], $expected['data'])) {
            $exp = self::arr($expected);
            $act = $actual instanceof NDArray ? $actual : NDArray::array($actual);
            $this->assertSame($exp->shape(), $act->shape(), "{$what}: shape");
            if ($exp->dtype() === DType::Bool || $exp->dtype()->isInteger()) {
                $this->assertSame($exp->toList(), $act->astype($exp->dtype())->toList(), "{$what}: values");
                if ($exp->dtype() !== $act->dtype() && ! ($exp->dtype()->isInteger() && $act->dtype()->isInteger())) {
                    $this->fail("{$what}: dtype {$act->dtype()->name()} != {$exp->dtype()->name()}");
                }

                return;
            }
            $e = $exp->toList();
            $a = $act->astype($exp->dtype())->toList();
            $scale = 0.0;
            foreach ($e as $v) {
                if (is_finite($v)) {
                    $scale = max($scale, abs($v));
                }
            }
            foreach ($e as $i => $v) {
                $this->assertTrue(self::close($v, $a[$i], $rtol, $scale), sprintf('%s: element %d expected %.17g got %.17g', $what, $i, $v, $a[$i]));
            }

            return;
        }
        if (is_array($expected) && array_is_list($expected) && is_array($actual)) {
            $this->assertCount(count($expected), $actual, $what);
            foreach ($expected as $i => $v) {
                $this->near($v, $actual[$i], $rtol, "{$what}[{$i}]");
            }

            return;
        }
        if (is_array($expected) && isset($expected['re'])) {
            $this->assertTrue(self::close(self::num($expected['re']), $actual[0], $rtol, 1.0) && self::close(self::num($expected['im']), $actual[1], $rtol, 1.0), $what);

            return;
        }
        if (is_bool($expected) || is_int($expected)) {
            $this->assertEquals($expected, $actual instanceof NDArray ? $actual->item() : $actual, $what);

            return;
        }
        $ev = self::num($expected);
        $av = $actual instanceof NDArray ? (float) $actual->item() : (float) $actual;
        $this->assertTrue(self::close($ev, $av, $rtol, abs($ev)), sprintf('%s: expected %.17g got %.17g', $what, $ev, $av));
    }

    private static function close(float $e, float $a, float $rtol, float $scale): bool
    {
        if (is_nan($e)) {
            return is_nan($a);
        }
        if (is_infinite($e)) {
            return $e === $a;
        }
        if ($rtol === 0.0) {
            return $e === $a;
        }

        return abs($e - $a) <= $rtol * max(abs($e), 1e-300) + $rtol * 1e-3 * $scale + 1e-300;
    }
}
