<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero\Random;

use Tessero\NDArray;
use Tessero\Native\Registry;

/**
 * The distribution methods of numpy.random.Generator, drawn with NumPy's own distribution code from this generator's PCG64 stream, so every call matches NumPy bit for bit.
 *
 * Array arguments broadcast as in NumPy; size fixes the output shape (null: the broadcast shape, a scalar for
 * scalar arguments). The native extension's Tessero\Ext\Random\Generator has the same methods.
 *
 * @property \FFI\CData $state
 */
trait GeneratorMethods
{
    /**
     * Samples from a beta distribution (Generator.beta).
     *
     * numpy.random.Generator.beta
     */
    public function beta(mixed $a, mixed $b, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.beta', $this->state, [$a, $b], $size, []);
    }

    /**
     * Samples from a binomial distribution (Generator.binomial).
     *
     * numpy.random.Generator.binomial
     */
    public function binomial(mixed $n, mixed $p, int|array|null $size = null): NDArray|int
    {
        return Registry::random('random.binomial', $this->state, [$n, $p], $size, []);
    }

    /**
     * Samples from a chi-square distribution (Generator.chisquare).
     *
     * numpy.random.Generator.chisquare
     */
    public function chisquare(mixed $df, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.chisquare', $this->state, [$df], $size, []);
    }

    /**
     * Samples from an exponential distribution (Generator.exponential).
     *
     * numpy.random.Generator.exponential
     */
    public function exponential(mixed $scale = 1.0, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.exponential', $this->state, [$scale], $size, []);
    }

    /**
     * Samples from an F distribution (Generator.f).
     *
     * numpy.random.Generator.f
     */
    public function f(mixed $dfnum, mixed $dfden, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.f', $this->state, [$dfnum, $dfden], $size, []);
    }

    /**
     * Samples from a gamma distribution (Generator.gamma).
     *
     * numpy.random.Generator.gamma
     */
    public function gamma(mixed $shape, mixed $scale = 1.0, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.gamma', $this->state, [$shape, $scale], $size, []);
    }

    /**
     * Samples from the geometric distribution (Generator.geometric).
     *
     * numpy.random.Generator.geometric
     */
    public function geometric(mixed $p, int|array|null $size = null): NDArray|int
    {
        return Registry::random('random.geometric', $this->state, [$p], $size, []);
    }

    /**
     * Samples from a Gumbel distribution (Generator.gumbel).
     *
     * numpy.random.Generator.gumbel
     */
    public function gumbel(mixed $loc = 0.0, mixed $scale = 1.0, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.gumbel', $this->state, [$loc, $scale], $size, []);
    }

    /**
     * Samples from a hypergeometric distribution (Generator.hypergeometric).
     *
     * numpy.random.Generator.hypergeometric
     */
    public function hypergeometric(mixed $ngood, mixed $nbad, mixed $nsample, int|array|null $size = null): NDArray|int
    {
        return Registry::random('random.hypergeometric', $this->state, [$ngood, $nbad, $nsample], $size, []);
    }

    /**
     * Samples from the Laplace or double exponential distribution (Generator.laplace).
     *
     * numpy.random.Generator.laplace
     */
    public function laplace(mixed $loc = 0.0, mixed $scale = 1.0, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.laplace', $this->state, [$loc, $scale], $size, []);
    }

    /**
     * Samples from a logistic distribution (Generator.logistic).
     *
     * numpy.random.Generator.logistic
     */
    public function logistic(mixed $loc = 0.0, mixed $scale = 1.0, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.logistic', $this->state, [$loc, $scale], $size, []);
    }

    /**
     * Samples from a log-normal distribution (Generator.lognormal).
     *
     * numpy.random.Generator.lognormal
     */
    public function lognormal(mixed $mean = 0.0, mixed $sigma = 1.0, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.lognormal', $this->state, [$mean, $sigma], $size, []);
    }

    /**
     * Samples from a logarithmic series distribution (Generator.logseries).
     *
     * numpy.random.Generator.logseries
     */
    public function logseries(mixed $p, int|array|null $size = null): NDArray|int
    {
        return Registry::random('random.logseries', $this->state, [$p], $size, []);
    }

    /**
     * Samples from a negative binomial distribution (Generator.negative_binomial).
     *
     * numpy.random.Generator.negative_binomial
     */
    public function negativeBinomial(mixed $n, mixed $p, int|array|null $size = null): NDArray|int
    {
        return Registry::random('random.negative_binomial', $this->state, [$n, $p], $size, []);
    }

    /**
     * Samples from a noncentral chi-square distribution (Generator.noncentral_chisquare).
     *
     * numpy.random.Generator.noncentral_chisquare
     */
    public function noncentralChisquare(mixed $df, mixed $nonc, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.noncentral_chisquare', $this->state, [$df, $nonc], $size, []);
    }

    /**
     * Samples from the noncentral F distribution (Generator.noncentral_f).
     *
     * numpy.random.Generator.noncentral_f
     */
    public function noncentralF(mixed $dfnum, mixed $dfden, mixed $nonc, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.noncentral_f', $this->state, [$dfnum, $dfden, $nonc], $size, []);
    }

    /**
     * Samples from a normal (Gaussian) distribution (Generator.normal).
     *
     * numpy.random.Generator.normal
     */
    public function normal(mixed $loc = 0.0, mixed $scale = 1.0, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.normal', $this->state, [$loc, $scale], $size, []);
    }

    /**
     * Samples from a Pareto II (Lomax) distribution (Generator.pareto).
     *
     * numpy.random.Generator.pareto
     */
    public function pareto(mixed $a, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.pareto', $this->state, [$a], $size, []);
    }

    /**
     * Samples from a Poisson distribution (Generator.poisson).
     *
     * numpy.random.Generator.poisson
     */
    public function poisson(mixed $lam = 1.0, int|array|null $size = null): NDArray|int
    {
        return Registry::random('random.poisson', $this->state, [$lam], $size, []);
    }

    /**
     * Samples in [0, 1] from a power distribution with positive exponent a - 1 (Generator.power).
     *
     * numpy.random.Generator.power
     */
    public function power(mixed $a, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.power', $this->state, [$a], $size, []);
    }

    /**
     * Floats in the half-open interval [0.0, 1.0) (Generator.random).
     *
     * numpy.random.Generator.random
     */
    public function random(int|array|null $size = null, string $dtype = 'float64'): NDArray|float
    {
        return Registry::random('random.random', $this->state, [], $size, ['dtype' => $dtype]);
    }

    /**
     * Samples from a Rayleigh distribution (Generator.rayleigh).
     *
     * numpy.random.Generator.rayleigh
     */
    public function rayleigh(mixed $scale = 1.0, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.rayleigh', $this->state, [$scale], $size, []);
    }

    /**
     * Samples from a standard Cauchy distribution (Generator.standard_cauchy).
     *
     * numpy.random.Generator.standard_cauchy
     */
    public function standardCauchy(int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.standard_cauchy', $this->state, [], $size, []);
    }

    /**
     * Samples from the standard exponential distribution (Generator.standard_exponential).
     *
     * numpy.random.Generator.standard_exponential
     */
    public function standardExponential(int|array|null $size = null, string $dtype = 'float64', string $method = 'zig'): NDArray|float
    {
        return Registry::random('random.standard_exponential', $this->state, [], $size, ['dtype' => $dtype, 'method' => $method]);
    }

    /**
     * Samples from the standard gamma distribution (Generator.standard_gamma).
     *
     * numpy.random.Generator.standard_gamma
     */
    public function standardGamma(mixed $shape, int|array|null $size = null, string $dtype = 'float64'): NDArray|float
    {
        return Registry::random('random.standard_gamma', $this->state, [$shape], $size, ['dtype' => $dtype]);
    }

    /**
     * Samples from the standard normal distribution, ziggurat method (Generator.standard_normal).
     *
     * numpy.random.Generator.standard_normal
     */
    public function standardNormal(int|array|null $size = null, string $dtype = 'float64'): NDArray|float
    {
        return Registry::random('random.standard_normal', $this->state, [], $size, ['dtype' => $dtype]);
    }

    /**
     * Samples from a standard Student's t distribution (Generator.standard_t).
     *
     * numpy.random.Generator.standard_t
     */
    public function standardT(mixed $df, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.standard_t', $this->state, [$df], $size, []);
    }

    /**
     * Samples from the triangular distribution over [left, right] (Generator.triangular).
     *
     * numpy.random.Generator.triangular
     */
    public function triangular(mixed $left, mixed $mode, mixed $right, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.triangular', $this->state, [$left, $mode, $right], $size, []);
    }

    /**
     * Samples from a uniform distribution over [low, high) (Generator.uniform).
     *
     * numpy.random.Generator.uniform
     */
    public function uniform(mixed $low = 0.0, mixed $high = 1.0, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.uniform', $this->state, [$low, $high], $size, []);
    }

    /**
     * Samples from a von Mises distribution (Generator.vonmises).
     *
     * numpy.random.Generator.vonmises
     */
    public function vonmises(mixed $mu, mixed $kappa, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.vonmises', $this->state, [$mu, $kappa], $size, []);
    }

    /**
     * Samples from a Wald, or inverse Gaussian, distribution (Generator.wald).
     *
     * numpy.random.Generator.wald
     */
    public function wald(mixed $mean, mixed $scale, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.wald', $this->state, [$mean, $scale], $size, []);
    }

    /**
     * Samples from a Weibull distribution (Generator.weibull).
     *
     * numpy.random.Generator.weibull
     */
    public function weibull(mixed $a, int|array|null $size = null): NDArray|float
    {
        return Registry::random('random.weibull', $this->state, [$a], $size, []);
    }

    /**
     * Samples from a Zipf distribution (Generator.zipf).
     *
     * numpy.random.Generator.zipf
     */
    public function zipf(mixed $a, int|array|null $size = null): NDArray|int
    {
        return Registry::random('random.zipf', $this->state, [$a], $size, []);
    }
}
