/* Operation codes (mirrored in PHP: Tessero\Native\Abi). */
#ifndef TSR_OPS_H
#define TSR_OPS_H
enum {
    OP_ADD = 0, OP_SUB, OP_MUL, OP_DIV, OP_POW, OP_MAX, OP_MIN, OP_ATAN2, OP_HYPOT, OP_MOD,
    OP_EQ, OP_NE, OP_LT, OP_LE, OP_GT, OP_GE, OP_AND, OP_OR, OP_XOR, OP_FLOORDIV
};
enum {
    U_NEG = 0, U_ABS, U_SQUARE, U_SIGN, U_SQRT, U_EXP, U_LOG, U_LOG10, U_LOG2, U_SIN, U_COS, U_TAN,
    U_ARCSIN, U_ARCCOS, U_ARCTAN, U_SINH, U_COSH, U_TANH, U_FLOOR, U_CEIL, U_RINT, U_EXPM1, U_LOG1P,
    U_RECIPROCAL, U_ISNAN, U_ISFINITE, U_ISINF, U_NOT, U_REAL, U_IMAG, U_CABS, U_ANGLE, U_CONJ
};
enum { R_SUM = 0, R_PROD, R_MIN, R_MAX, R_ARGMIN, R_ARGMAX, R_ANY, R_ALL };
#endif
