"""
Generate NumPy/SciPy reference results for Tessero's parity suite.

    bash tools/parity/gen-fixtures.sh legacy      # writes tests/fixtures/parity.json (pinned environment, ADR 0012)

Every case is data: inputs, the operation name and NumPy's answer. The PHP
side (tests/Parity/ParityTest.php) replays each case through Tessero and
compares with a tolerance chosen per family (exact for integer / RNG work).
Floats are written with repr() so the round trip is exact; NaN/inf as strings.
"""
import json
import math
import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "tools", "parity"))
import fixture_env  # noqa: E402  (ADR 0012: the pinned reference environment)
import scipy
import scipy.linalg as sla
import scipy.optimize as so
import scipy.sparse as sp
import scipy.sparse.linalg as spla


def enc(x):
    if isinstance(x, np.ndarray):
        if np.iscomplexobj(x):
            flat = np.stack([x.real.ravel(), x.imag.ravel()], axis=1).ravel()
            return {"shape": list(x.shape), "dtype": "complex128", "data": [f(v) for v in flat]}
        dt = str(x.dtype)
        if x.dtype == np.bool_:
            data = [bool(v) for v in x.ravel()]
        elif np.issubdtype(x.dtype, np.integer):
            data = [int(v) for v in x.ravel()]
        else:
            data = [f(v) for v in x.ravel()]
        return {"shape": list(x.shape), "dtype": dt, "data": data}
    if isinstance(x, (np.floating, float)):
        return f(x)
    if isinstance(x, (np.integer,)):
        return int(x)
    if isinstance(x, (np.bool_,)):
        return bool(x)
    if isinstance(x, complex) or isinstance(x, np.complexfloating):
        return {"re": f(x.real), "im": f(x.imag)}
    if isinstance(x, (list, tuple)):
        return [enc(v) for v in x]
    if isinstance(x, dict):
        return {k: enc(v) for k, v in x.items()}
    return x


def f(v):
    v = float(v)
    if math.isnan(v):
        return "nan"
    if math.isinf(v):
        return "inf" if v > 0 else "-inf"
    return repr(v)


rng = np.random.default_rng(20260926)
cases = []


def add(family, **kw):
    cases.append({"family": family, **{k: enc(v) for k, v in kw.items()}})


# ------------------------------------------------------------------ element-wise with broadcasting
A = rng.standard_normal((3, 4, 5))
B = rng.standard_normal((4, 1))
P = np.abs(A) + 0.5
I = rng.integers(-20, 20, (4, 5))
J = rng.integers(1, 7, (5,))
binops = {
    "add": np.add, "sub": np.subtract, "mul": np.multiply, "div": np.divide, "maximum": np.maximum,
    "minimum": np.minimum, "atan2": np.arctan2, "hypot": np.hypot, "mod": np.mod, "floorDiv": np.floor_divide,
}
for name, fn in binops.items():
    add("binary", op=name, a=A, b=B, expect=fn(A, B))
    add("binary", op=name, a=I, b=J, expect=fn(I, J))
add("binary", op="pow", a=P, b=B, expect=np.power(P, B))
add("binary", op="pow", a=I, b=np.array([2, 3, 0, 1, 2]), expect=np.power(I, np.array([2, 3, 0, 1, 2])))
for name, fn in {"lt": np.less, "ge": np.greater_equal, "eq": np.equal}.items():
    add("binary", op=name, a=I, b=J, expect=fn(I, J))
add("binary", op="add", a=I, b=A[0], expect=I + A[0])           # int64 + float64 -> float64
add("binary_scalar", op="mul", a=I, b=2.5, expect=I * 2.5)       # weak float scalar
add("binary_scalar", op="add", a=I, b=3, expect=I + 3)           # stays int64
add("binary_scalar", op="div", a=I, b=4, expect=I / 4)

for name in ["sqrt", "exp", "log", "log1p", "expm1", "sin", "cos", "tan", "arctan", "tanh", "floor", "ceil", "rint", "abs", "square", "sign", "reciprocal"]:
    src = P if name in ("sqrt", "log", "log1p") else A
    add("unary", op=name, a=src, expect=getattr(np, name)(src))
add("unary", op="abs", a=I, expect=np.abs(I))

# ------------------------------------------------------------------ reductions
R = rng.standard_normal((4, 5, 6))
RI = rng.integers(-50, 50, (4, 5, 6))
for name in ["sum", "prod", "min", "max", "mean"]:
    for axis in [None, 0, 1, 2, [0, 2]]:
        fn = getattr(np, name)
        add("reduce", op=name, a=R, axis=axis, expect=fn(R, axis=None if axis is None else tuple(axis) if isinstance(axis, list) else axis))
for name in ["argmin", "argmax"]:
    for axis in [None, 0, 2]:
        add("reduce", op=name, a=R, axis=axis, expect=getattr(np, name)(R, axis=axis))
for axis in [None, 1]:
    add("reduce", op="var", a=R, axis=axis, ddof=1, expect=np.var(R, axis=axis, ddof=1))
    add("reduce", op="std", a=R, axis=axis, ddof=0, expect=np.std(R, axis=axis))
    add("reduce", op="sum", a=RI, axis=axis, expect=np.sum(RI, axis=axis))
add("reduce", op="cumsum", a=R, axis=1, expect=np.cumsum(R, axis=1))
add("reduce", op="cumprod", a=RI[:, :2, :2], axis=None, expect=np.cumprod(RI[:, :2, :2]))
# a million values generated by the (stream-identical) PCG64 on both sides keeps the fixture small
big = np.random.default_rng(99).random(1_000_003)
add("reduce_rng", seed=99, n=1_000_003, expect=[np.sum(big), np.mean(big), np.std(big), np.max(big), int(np.argmax(big))])

# ------------------------------------------------------------------ slicing and indexing
S = np.arange(4 * 6 * 5).reshape(4, 6, 5)
for spec in ["1:3", "::-1", "1:, ::2", "..., 0", "-1, 1:5:2, ::-2", ":, None, 2", "2, 3", "::-2, -1", "3:0:-1, ..."]:
    parts = []
    for p in spec.split(","):
        p = p.strip()
        parts.append(None if p == "None" else Ellipsis if p == "..." else int(p) if p.lstrip("-").isdigit() else slice(*[int(x) if x else None for x in p.split(":")]))
    add("slice", a=S, spec=spec, expect=S[tuple(parts)])
add("take", a=S, indices=[3, 0, -1], axis=1, expect=np.take(S, [3, 0, -1], axis=1))
add("mask", a=S, threshold=57, expect=S[S > 57])
add("sort", a=R, axis=1, expect=np.sort(R, axis=1))
add("argsort", a=RI, axis=-1, expect=np.argsort(RI, axis=-1, kind="stable"))
add("transpose_matmul", a=A[0], b=A[1], expect=A[0] @ A[1].T)
add("matmul", a=rng.standard_normal((2, 3, 7, 4)), b=rng.standard_normal((4, 5)), expect=None)
cases[-1]["expect"] = enc(np.array(cases[-1]["a"]["data"], dtype=float).reshape(2, 3, 7, 4) @ np.array([float(v) for v in cases[-1]["b"]["data"]]).reshape(4, 5))
add("where", c=A > 0, a=A, b=B, expect=np.where(A > 0, A, B))
add("concatenate", a=A[0], b=A[1], axis=1, expect=np.concatenate([A[0], A[1]], axis=1))

# ------------------------------------------------------------------ linear algebra
n = 6
M = rng.standard_normal((n, n))
SPD = M @ M.T + n * np.eye(n)
rhs = rng.standard_normal((n, 3))
T = rng.standard_normal((8, 5))
add("linalg", op="solve", a=M, b=rhs, expect=np.linalg.solve(M, rhs))
add("linalg", op="solve", a=M, b=rhs[:, 0], expect=np.linalg.solve(M, rhs[:, 0]))
add("linalg", op="inv", a=M, expect=np.linalg.inv(M))
add("linalg", op="det", a=M, expect=np.linalg.det(M))
add("linalg", op="slogdet", a=M, expect=list(np.linalg.slogdet(M)))
add("linalg", op="cholesky", a=SPD, expect=np.linalg.cholesky(SPD))
add("linalg", op="qr", a=T, expect=list(np.linalg.qr(T)))
add("linalg", op="qr_complete", a=T, expect=list(np.linalg.qr(T, mode="complete")))
add("linalg", op="eigh", a=SPD, expect=list(np.linalg.eigh(SPD)))
add("linalg", op="svd", a=T, expect=list(np.linalg.svd(T, full_matrices=False)))
add("linalg", op="svd_full", a=T, expect=list(np.linalg.svd(T)))
add("linalg", op="pinv", a=T, expect=np.linalg.pinv(T))
x, res, rank, sv = np.linalg.lstsq(T, rhs[:, 0].tolist() + [1.0, 2.0], rcond=None)
add("linalg", op="lstsq", a=T, b=np.array(rhs[:, 0].tolist() + [1.0, 2.0]), expect=[x, res, rank, sv])
w, v = np.linalg.eig(M)
add("linalg", op="eigvals", a=M, expect=np.sort_complex(w))
add("linalg", op="norm_fro", a=M, expect=np.linalg.norm(M))
add("linalg", op="norm_2", a=M, expect=np.linalg.norm(M, 2))
add("linalg", op="norm_1", a=M, expect=np.linalg.norm(M, 1))
add("linalg", op="norm_nuc", a=M, expect=np.linalg.norm(M, "nuc"))
add("linalg", op="cond", a=M, expect=np.linalg.cond(M))
add("linalg", op="matrix_rank", a=np.outer(np.arange(1, 6), np.arange(1, 5)), expect=np.linalg.matrix_rank(np.outer(np.arange(1, 6), np.arange(1, 5))))
p_, l_, u_ = sla.lu(M)
add("linalg", op="lu", a=M, expect=[p_, l_, u_])
U = np.triu(M) + n * np.eye(n)
add("linalg", op="solve_triangular", a=U, b=rhs, expect=sla.solve_triangular(U, rhs))
add("linalg", op="det_stack", a=rng.standard_normal((3, 4, 4)), expect=None)
cases[-1]["expect"] = enc(np.linalg.det(np.array([float(v) for v in cases[-1]["a"]["data"]]).reshape(3, 4, 4)))

# ------------------------------------------------------------------ FFT
for length in [1, 2, 5, 8, 12, 17, 64, 97, 100, 127, 360, 1024, 1031, 4096]:
    xr = rng.standard_normal(length)
    xi = rng.standard_normal(length)
    add("fft", op="fft", re=xr, im=xi, expect=np.fft.fft(xr + 1j * xi))
    add("fft", op="rfft", re=xr, expect=np.fft.rfft(xr))
    if length > 1:
        spec = np.fft.rfft(xr)
        add("fft", op="irfft", spec=spec, n=length, expect=np.fft.irfft(spec, n=length))
X2 = rng.standard_normal((6, 10))
add("fft", op="fft_axis0", re=X2, expect=np.fft.fft(X2, axis=0))
add("fft", op="ifft", re=X2[0], expect=np.fft.ifft(X2[0]))
add("fft", op="fft_n", re=X2[0], n=16, expect=np.fft.fft(X2[0], n=16))
add("fft", op="fft_ortho", re=X2[0], expect=np.fft.fft(X2[0], norm="ortho"))
add("fft", op="fftfreq", n=9, d=0.1, expect=np.fft.fftfreq(9, 0.1))
add("fft", op="fftshift", re=np.arange(10.0), expect=np.fft.fftshift(np.arange(10.0)))
add("fft", op="fft2", re=X2, expect=np.fft.fft2(X2))

# ------------------------------------------------------------------ random (stream identity)
for seed in [0, 42, 12345, 2**40 + 7, [1, 2, 3, 4, 5]]:
    g = np.random.default_rng(seed)
    add("random", seed=seed, op="random", size=7, expect=g.random(7))
    g = np.random.default_rng(seed)
    add("random", seed=seed, op="normal", size=9, loc=1.5, scale=3.0, expect=g.normal(1.5, 3.0, 9))
    g = np.random.default_rng(seed)
    add("random", seed=seed, op="integers", size=12, low=-3, high=100, expect=g.integers(-3, 100, 12))
    g = np.random.default_rng(seed)
    add("random", seed=seed, op="integers_big", size=5, low=0, high=2**50, expect=g.integers(0, 2**50, 5))
    g = np.random.default_rng(seed)
    add("random", seed=seed, op="permutation", size=15, expect=g.permutation(15))
    g = np.random.default_rng(seed)
    add("random", seed=seed, op="uniform", size=4, low=-2.0, high=5.0, expect=g.uniform(-2.0, 5.0, 4))
    g = np.random.default_rng(seed)
    pr = [0.1, 0.2, 0.3, 0.4]
    add("random", seed=seed, op="choice_p", size=10, p=pr, expect=g.choice(4, 10, p=pr))
    g = np.random.default_rng(seed)
    add("random", seed=seed, op="mixed", size=3, expect=[g.random(3), g.integers(0, 10, 3), g.normal(size=3), g.integers(0, 10, 3)])
g = np.random.default_rng(7)
add("random", seed=7, op="normal_many", size=20000, expect_mean=np.mean(g.normal(size=20000)), expect=None)
g = np.random.default_rng(7)
cases[-1]["expect"] = enc(g.normal(size=20000)[-5:])

# ------------------------------------------------------------------ sparse
D = rng.standard_normal((30, 20))
D[np.abs(D) < 1.0] = 0.0
csr = sp.csr_matrix(D)
v20 = rng.standard_normal(20)
add("sparse", op="csr", a=D, expect=[csr.indptr.astype(np.int64), csr.indices.astype(np.int64), csr.data])
add("sparse", op="matvec", a=D, x=v20, expect=csr @ v20)
add("sparse", op="transpose_matvec", a=D, x=rng.standard_normal(30), expect=None)
cases[-1]["expect"] = enc(csr.T @ np.array([float(v) for v in cases[-1]["x"]["data"]]))
N = 50
lap = sp.diags([-np.ones(N - 1), 2.5 * np.ones(N), -np.ones(N - 1)], [-1, 0, 1]).tocsr()
bvec = rng.standard_normal(N)
add("sparse", op="cg", a=lap.toarray(), b=bvec, expect=spla.spsolve(lap.tocsc(), bvec))
rows = [0, 1, 1, 3, 0]
cols = [0, 2, 2, 1, 0]
vals = [1.0, 2.0, 3.0, 4.0, 5.0]
add("sparse", op="triplets", rows=rows, cols=cols, vals=vals, shape=[4, 3], expect=sp.coo_matrix((vals, (rows, cols)), shape=(4, 3)).toarray())


# ------------------------------------------------------------------ optimize
def rosen(x):
    return sum(100.0 * (x[1:] - x[:-1] ** 2.0) ** 2.0 + (1 - x[:-1]) ** 2.0)


r = so.minimize(rosen, [1.3, 0.7, 0.8, 1.9, 1.2], method="Nelder-Mead")
add("optimize", op="nelder_mead_rosen", x0=[1.3, 0.7, 0.8, 1.9, 1.2], expect={"x": r.x, "fun": r.fun, "nit": r.nit, "nfev": r.nfev})
r = so.minimize(rosen, [1.3, 0.7, 0.8, 1.9, 1.2], method="BFGS", jac=so.rosen_der)
add("optimize", op="bfgs_rosen", x0=[1.3, 0.7, 0.8, 1.9, 1.2], expect={"x": r.x, "fun": r.fun, "nit": r.nit})
r = so.minimize(rosen, [-1.2, 1.0], method="BFGS")
add("optimize", op="bfgs_rosen_fd", x0=[-1.2, 1.0], expect={"x": r.x, "fun": r.fun})
# tight tolerances on both sides: the comparison is against the optimum, not where each code happens to stop
r = so.minimize(rosen, [0.5, 0.5, 0.5], method="L-BFGS-B", jac=so.rosen_der, bounds=[(0, 0.8), (0, 2), (0, 2)], options={"ftol": 1e-15, "gtol": 1e-10})
add("optimize", op="lbfgsb_bounded", x0=[0.5, 0.5, 0.5], bounds=[[0, 0.8], [0, 2], [0, 2]], expect={"x": r.x, "fun": r.fun})
root, rr = so.brentq(lambda x: x ** 3 - 2 * x - 5, 2, 3, full_output=True)
add("optimize", op="brentq", a=2, b=3, expect={"root": root, "iterations": rr.iterations, "function_calls": rr.function_calls})
root, rr = so.brentq(lambda x: math.cos(x) - x, -2, 4, full_output=True)
add("optimize", op="brentq_cos", a=-2, b=4, expect={"root": root, "iterations": rr.iterations, "function_calls": rr.function_calls})
add("optimize", op="newton_secant", x0=1.5, expect=so.newton(lambda x: x ** 3 - 2 * x - 5, 1.5))
sol = so.root(lambda v: [v[0] + 0.5 * (v[0] - v[1]) ** 3 - 1.0, 0.5 * (v[1] - v[0]) ** 3 + v[1]], [0, 0])
add("optimize", op="root_system", x0=[0, 0], expect=sol.x)
xd = np.linspace(0, 4, 50)
yd = 2.5 * np.exp(-1.3 * xd) + 0.5 + 0.01 * np.sin(7 * xd)
popt, pcov = so.curve_fit(lambda x, a, b, c: a * np.exp(-b * x) + c, xd, yd, p0=[1, 1, 1])
add("optimize", op="curve_fit", x=xd, y=yd, p0=[1, 1, 1], expect=[popt, pcov])

# ------------------------------------------------------------------ linear / mixed-integer programming (HiGHS)
lprng = np.random.default_rng(4242)
for k in range(12):
    n, mub, meq = int(lprng.integers(3, 10)), int(lprng.integers(1, 7)), int(lprng.integers(0, 3))
    x0 = lprng.uniform(0.5, 3.0, n)
    Aub = np.round(lprng.normal(size=(mub, n)), 3)
    bub = np.round(Aub @ x0 + lprng.uniform(0.1, 2.0, mub), 3)
    Aeq = np.round(lprng.normal(size=(meq, n)), 3)
    beq = np.round(Aeq @ x0, 3)
    c = np.round(lprng.normal(size=n), 3)
    bounds = [(0, 5) if j % 3 == 0 else ((-4, None) if j % 3 == 1 else (None, 6)) for j in range(n)]
    r = so.linprog(c, A_ub=Aub, b_ub=bub, A_eq=Aeq if meq else None, b_eq=beq if meq else None, bounds=bounds, method="highs")
    add("lp", op="linprog", c=c, A_ub=Aub, b_ub=bub, A_eq=Aeq, b_eq=beq, bounds=[[None if v is None else float(v) for v in b] for b in bounds],
        expect={"status": int(r.status), "fun": r.fun if r.status == 0 else None, "x": r.x if r.status == 0 else None,
                "ineq": r.ineqlin.marginals if r.status == 0 else None, "eq": r.eqlin.marginals if r.status == 0 and meq else None})
add("lp", op="linprog", c=np.array([1.0, 1.0]), A_ub=np.array([[-1.0, -1.0]]), b_ub=np.array([-3.0]), A_eq=np.zeros((0, 2)), b_eq=np.zeros(0),
    bounds=[[0.0, 1.0], [0.0, 1.0]], expect={"status": 2, "fun": None, "x": None, "ineq": None, "eq": None})
add("lp", op="linprog", c=np.array([-1.0, 0.0]), A_ub=np.array([[0.0, 1.0]]), b_ub=np.array([1.0]), A_eq=np.zeros((0, 2)), b_eq=np.zeros(0),
    bounds=[[0.0, None], [0.0, None]], expect={"status": 3, "fun": None, "x": None, "ineq": None, "eq": None})
for k in range(10):
    n, m = int(lprng.integers(4, 12)), int(lprng.integers(1, 5))
    w = lprng.integers(1, 20, (m, n)).astype(float)
    cap = np.floor(w.sum(axis=1) * lprng.uniform(0.3, 0.6, m))
    val = lprng.integers(1, 30, n).astype(float)
    integ = np.array([1 if j % 4 != 3 else 0 for j in range(n)])
    ub = np.where(integ == 1, lprng.integers(1, 4, n), 2.5).astype(float)
    r = so.milp(-val, integrality=integ, bounds=so.Bounds(np.zeros(n), ub), constraints=so.LinearConstraint(w, -np.inf, cap),
                options={"mip_rel_gap": 0})
    add("lp", op="milp", c=-val, A_ub=w, b_ub=cap, integrality=integ, ub=ub, expect={"status": int(r.status), "fun": r.fun})

# ------------------------------------------------------------------ Markov decision processes (numpy reference)
def solve_mdp(P, R, gamma):
    A, S, _ = P.shape
    pol = np.zeros(S, dtype=int)
    while True:
        Pp = P[pol, np.arange(S), :]
        Rp = R[np.arange(S), pol]
        V = np.linalg.solve(np.eye(S) - gamma * Pp, Rp)
        Q = R + gamma * np.einsum("ast,t->sa", P, V)
        new = Q.argmax(axis=1)
        keep = Q[np.arange(S), pol] >= Q[np.arange(S), new] - 1e-12
        new = np.where(keep, pol, new)
        if np.array_equal(new, pol):
            return V, pol, Q
        pol = new

mdprng = np.random.default_rng(99)
for k, (S, A, support, gamma) in enumerate([(6, 2, 3, 0.9), (40, 4, 5, 0.95), (120, 3, 8, 0.99), (25, 5, 25, 0.8)]):
    P = np.zeros((A, S, S))
    for a in range(A):
        for s in range(S):
            idx = mdprng.choice(S, support, replace=False)
            P[a, s, idx] = mdprng.dirichlet(np.ones(support))
    R = np.round(mdprng.normal(size=(S, A)), 4)
    V, pol, Q = solve_mdp(P, R, gamma)
    rand_pol = mdprng.integers(0, A, S)
    Pp = P[rand_pol, np.arange(S), :]
    Vr = np.linalg.solve(np.eye(S) - gamma * Pp, R[np.arange(S), rand_pol])
    T = 5
    Vt = np.zeros((T + 1, S)); pt = np.zeros((T, S), dtype=int)
    for t in range(T - 1, -1, -1):
        Qt = R + np.einsum("ast,t->sa", P, Vt[t + 1])
        pt[t] = Qt.argmax(axis=1); Vt[t] = Qt.max(axis=1)
    add("mdp", S=S, A=A, gamma=gamma, P=P, R=R, expect_V=V, expect_policy=pol.astype(np.int64), expect_Q=Q,
        eval_policy=rand_pol.astype(np.int64), expect_eval=Vr, expect_fh_V=Vt, expect_fh_policy=pt.astype(np.int64))

# ------------------------------------------------------------------ .npy produced by numpy
here = os.path.dirname(os.path.abspath(__file__))
np.save(os.path.join(here, "numpy_f8.npy"), np.arange(12.0).reshape(3, 4) / 7)
np.save(os.path.join(here, "numpy_i4_fortran.npy"), np.asfortranarray(np.arange(6, dtype=np.int32).reshape(2, 3)))
np.save(os.path.join(here, "numpy_c16.npy"), np.array([1 + 2j, -3.5 - 0.25j]))

out = {"numpy": np.__version__, "scipy": scipy.__version__, "env": fixture_env.env(), "cases": cases}
fixture_env.require_pinned()
with open(os.path.join(here, "parity.json"), "w") as fh:
    json.dump(out, fh, separators=(",", ":"))
print(f"{len(cases)} cases, numpy {np.__version__}, scipy {scipy.__version__}", file=sys.stderr)


# ------------------------------------------------------------------ fuzz: slicing, strided iteration, broadcasting
def rand_slice_spec(frng, shape):
    parts, keys = [], []
    for d, n in enumerate(shape):
        kind = frng.integers(0, 4)
        if kind == 0 and n > 0:
            i = int(frng.integers(-n, n))
            parts.append(str(i)); keys.append(i)
        elif kind == 1:
            parts.append(":"); keys.append(slice(None))
        else:
            step = int(frng.choice([1, 2, 3, -1, -2]))
            start = int(frng.integers(-n - 1, n + 2)) if frng.random() < 0.7 else None
            stop = int(frng.integers(-n - 1, n + 2)) if frng.random() < 0.7 else None
            parts.append(f"{'' if start is None else start}:{'' if stop is None else stop}:{step}")
            keys.append(slice(start, stop, step))
    if frng.random() < 0.2:
        k = int(frng.integers(0, len(parts) + 1))
        parts.insert(k, "None"); keys.insert(k, None)
    return ", ".join(parts), tuple(keys)


frng = np.random.default_rng(777)
fuzz = []
for _ in range(300):
    nd = int(frng.integers(1, 5))
    shape = [int(v) for v in frng.integers(1, 6, nd)]
    base = np.arange(int(np.prod(shape))).reshape(shape)
    spec, key = rand_slice_spec(frng, shape)
    view = base[key]
    case = {"kind": "slice", "shape": shape, "spec": spec, "expect": enc(np.array(view, copy=True))}
    # element-wise on the strided view, broadcast against a smaller operand
    if view.ndim > 0 and view.size > 0:
        bshape = [1 if frng.random() < 0.4 else s for s in view.shape][int(frng.integers(0, view.ndim)):]
        other = (np.arange(int(np.prod(bshape))) * 0.5 - 3).reshape(bshape)
        case["bshape"] = bshape
        case["binary"] = enc(view * 1.5 - other)
        ax = int(frng.integers(0, view.ndim))
        case["axis"] = ax
        case["sum_axis"] = enc(np.asarray(view.sum(axis=ax)))
        case["max_axis"] = enc(np.asarray(view.max(axis=ax)))
        case["transposed_copy"] = enc(np.array(view.T, copy=True).astype(np.float32))
    fuzz.append(case)
with open(os.path.join(here, "fuzz.json"), "w") as fh:
    json.dump(fuzz, fh, separators=(",", ":"))
print(f"{len(fuzz)} fuzz cases", file=sys.stderr)
