<?php

/**
 * Beta issue list: one source (.github/beta-issues.json), two outputs.
 *
 *   php tools/beta-issues.php render > docs/project/open-issues.md
 *   php tools/beta-issues.php check            # CI/gate: non-zero exit if that page is stale
 *   php tools/beta-issues.php create --repo=OWNER/tessero [--dry-run] [--only=P0]
 *
 * `create` uses the GitHub CLI (`gh auth login` first). It creates the labels,
 * then one issue per entry, and skips entries whose ID already appears in an
 * open or closed issue title, so running it twice creates nothing new.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$data = json_decode((string) file_get_contents("{$root}/.github/beta-issues.json"), true, 512, JSON_THROW_ON_ERROR);
$issues = $data['issues'];
$cmd = $argv[1] ?? '';
$opt = [];
foreach (array_slice($argv, 2) as $arg) {       // getopt() stops at the sub-command, so parse --key[=value] here
    if (preg_match('/^--([a-z-]+)(?:=(.*))?$/', $arg, $m)) {
        $opt[$m[1]] = $m[2] ?? true;
    }
}

$priorityText = [
    'P0' => 'P0: beta exit and validation. Must be closed before the beta is called stable. Most need hardware, accounts or people rather than code.',
    'P1' => 'P1: correctness, parity and scale.',
    'P2' => 'P2: performance and tooling.',
    'P3' => 'P3: features (NumPy/SciPy gaps).',
];

function issue_body(array $i): string
{
    $b = $i['context'] . "\n\n**Acceptance criteria**\n\n";
    foreach ($i['acceptance'] as $a) {
        $b .= "- [ ] {$a}\n";
    }

    return $b . "\n**Estimate:** {$i['estimate']} session(s)  \n**Priority:** {$i['priority']}\n\n_From docs/project/open-issues.md ({$i['id']})._\n";
}

if ($cmd === 'render' || $cmd === 'check') {
    ob_start();
    $revision = $data['revision'] ?? 1;
    $open = array_values(array_filter($issues, static fn (array $i): bool => ($i['status'] ?? 'open') !== 'resolved'));
    $resolved = array_values(array_filter($issues, static fn (array $i): bool => ($i['status'] ?? 'open') === 'resolved'));
    $count = array_count_values(array_column($open, 'priority'));
    ksort($count);
    echo "<!-- generated by tools/beta-issues.php from .github/beta-issues.json; do not edit by hand -->\n\n";
    echo "# Open issues (beta)\n\n";
    echo "Tessero {$data['version']} is in beta; this open-issues list is at revision **v{$revision}** (it is bumped as\n";
    echo "issues are resolved). It is the tracked list of what stands between the beta and a stable release, ranked by\n";
    echo "priority. The same list is imported into GitHub Issues with `php tools/beta-issues.php create`; after the\n";
    echo "import, GitHub is the source of truth and this page is a snapshot from {$data['generated']}.\n\n";
    echo "| Priority | Issues |\n|---|---:|\n";
    foreach ($count as $p => $n) {
        echo "| {$p} | {$n} |\n";
    }
    echo "| **Total open** | **" . count($open) . "** |\n";
    if ($resolved !== []) {
        echo '| Resolved | ' . count($resolved) . " |\n";
    }
    echo "\n";
    echo "The feature items (P3) come from the [NumPy/SciPy gap analysis](numpy-scipy-gap-analysis.md). The steps for testing outside the\n";
    echo "Linux review host are in the [live-testing checklist](../operations/live-testing.md).\n\n";
    foreach ($priorityText as $p => $text) {
        $rows = array_filter($open, static fn (array $i): bool => $i['priority'] === $p);
        if ($rows === []) {
            continue;
        }
        echo "## {$text}\n\n| ID | Issue | Labels | Estimate |\n|---|---|---|---:|\n";
        foreach ($rows as $i) {
            echo "| [{$i['id']}](#" . strtolower($i['id']) . ") | {$i['title']} | " . implode(', ', $i['labels']) . " | {$i['estimate']} |\n";
        }
        echo "\n";
    }
    echo "## Details\n\n";
    foreach ($open as $i) {
        echo "### {$i['id']}\n\n**{$i['title']}** ({$i['priority']}; " . implode(', ', $i['labels']) . ")\n\n";
        echo $i['context'] . "\n\nAcceptance criteria:\n\n";
        foreach ($i['acceptance'] as $a) {
            echo "- {$a}\n";
        }
        echo "\n";
    }
    if ($resolved !== []) {
        echo "## Resolved\n\nClosed during the beta (newest list revision v{$revision}).\n\n";
        echo "| ID | Issue | Resolved in | How |\n|---|---|---|---|\n";
        foreach ($resolved as $i) {
            echo "| {$i['id']} | {$i['title']} | v" . ($i['resolvedIn'] ?? $revision) . ' | ' . ($i['resolution'] ?? '') . " |\n";
        }
        echo "\n";
    }
    $md = ob_get_clean();
    if ($cmd === 'check') {
        $path = "{$root}/docs/project/open-issues.md";
        $current = is_file($path) ? file_get_contents($path) : '';
        if ($current === $md) {
            echo "docs/project/open-issues.md is current\n";
            exit(0);
        }
        fwrite(STDERR, "docs/project/open-issues.md is out of date: run `php tools/beta-issues.php render > docs/project/open-issues.md`\n");
        exit(1);
    }
    echo $md;
    exit(0);
}

if ($cmd === 'create') {
    $repo = $opt['repo'] ?? '';
    $dry = isset($opt['dry-run']);
    if ($repo === '' && ! $dry) {
        fwrite(STDERR, "usage: php tools/beta-issues.php create --repo=OWNER/NAME [--dry-run] [--only=P0]\n");
        exit(2);
    }
    $run = static function (array $args) use ($dry): string {
        $line = implode(' ', array_map('escapeshellarg', $args));
        if ($dry) {
            echo "\$ {$line}\n";

            return '';
        }
        exec($line . ' 2>&1', $out, $rc);
        if ($rc !== 0) {
            fwrite(STDERR, implode("\n", $out) . "\n");
            exit(1);
        }

        return implode("\n", $out);
    };
    $existing = $dry ? '' : $run(['gh', 'issue', 'list', '--repo', $repo, '--state', 'all', '--limit', '1000', '--json', 'title', '--jq', '.[].title']);
    $labels = ['P0', 'P1', 'P2', 'P3'];
    foreach ($issues as $i) {
        $labels = array_merge($labels, $i['labels']);
    }
    foreach (array_unique($labels) as $l) {
        $run(['gh', 'label', 'create', $l, '--repo', $repo ?: 'OWNER/NAME', '--force', '--color', match ($l) {
            'P0' => 'b60205', 'P1' => 'd93f0b', 'P2' => 'fbca04', 'P3' => '0e8a16', 'beta-exit' => '5319e7', default => 'c5def5',
        }]);
    }
    $made = 0;
    foreach ($issues as $i) {
        if (($i['status'] ?? 'open') === 'resolved') {
            continue;                                   // already closed; don't re-open it
        }
        if (isset($opt['only']) && $i['priority'] !== $opt['only']) {
            continue;
        }
        $title = "[{$i['id']}] {$i['title']}";
        if (str_contains($existing, "[{$i['id']}]")) {
            echo "skip {$i['id']} (exists)\n";
            continue;
        }
        $run(['gh', 'issue', 'create', '--repo', $repo ?: 'OWNER/NAME', '--title', $title, '--body', issue_body($i),
            '--label', implode(',', array_merge([$i['priority']], $i['labels']))]);
        $made++;
    }
    echo ($dry ? 'would create' : 'created') . " {$made} issue(s)\n";
    exit(0);
}

fwrite(STDERR, "usage: php tools/beta-issues.php render|check|create\n");
exit(2);
