<?php

/**
 * Generate the cookbook docs pages from examples/**.php using MkDocs snippet includes, so the
 * documentation never copies example code - it embeds the runnable files that CI executes.
 *
 *   php tools/gen-example-docs.php           # write docs/examples/*.md
 *   php tools/gen-example-docs.php --check    # CI/gate: non-zero exit if any page is stale
 *
 * Each example's leading /** ... *\/ header becomes the prose; the file itself is embedded with
 * `--8<-- "examples/<module>/<file>"` (pymdownx.snippets, check_paths on, so a missing file fails).
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$exRoot = "{$root}/examples";
$check = in_array('--check', array_slice($argv, 1), true);

$titles = [
    'arrays' => 'Arrays and indexing',
    'math' => 'Math and ufuncs',
    'reductions' => 'Reductions and statistics',
    'sorting' => 'Sorting and searching',
    'linalg' => 'Linear algebra (dense)',
    'sparse' => 'Sparse matrices',
    'fft' => 'FFT',
    'random' => 'Random',
    'io' => '.npy / .npz and memory maps',
    'special' => 'scipy.special',
    'stats' => 'scipy.stats',
    'optimize' => 'Optimize',
    'csgraph' => 'Graphs (csgraph)',
    'mdp' => 'Markov decision processes',
    'laravel' => 'Laravel bridge',
];

/** First paragraph of the file's leading docblock, as Markdown prose. */
function summary(string $path): string
{
    $src = (string) file_get_contents($path);
    if (! preg_match('#/\*\*(.*?)\*/#s', $src, $m)) {
        return '';
    }
    $lines = array_map(static fn (string $l): string => (string) preg_replace('/^\s*\*\s?/', '', $l), preg_split('/\R/', $m[1]) ?: []);

    return trim(implode("\n", $lines));
}

$modules = [];
foreach (scandir($exRoot) ?: [] as $m) {
    if ($m === '.' || $m === '..' || $m[0] === '_' || ! is_dir("{$exRoot}/{$m}")) {
        continue;
    }
    $files = array_values(array_filter(scandir("{$exRoot}/{$m}") ?: [], static fn (string $f): bool => str_ends_with($f, '.php')));
    sort($files);
    if ($files !== []) {
        $modules[$m] = $files;
    }
}
ksort($modules);

$pages = [];

$index = "<!-- generated by tools/gen-example-docs.php from examples/; do not edit by hand -->\n\n";
$index .= "# Examples cookbook\n\n";
$index .= "Every example below is a runnable PHP file under `examples/`. `tools/run-examples.php` executes them on\n";
$index .= "both backends (FFI and the native extension) as part of the gate, so they cannot drift from the code.\n";
$index .= "Examples for FFI-only surfaces (optimize, dense/sparse linear algebra, I/O, csgraph, MDP) skip on the extension.\n\n";
$index .= "| Module | Examples |\n|---|---:|\n";
foreach ($modules as $m => $files) {
    $index .= '| [' . ($titles[$m] ?? ucfirst($m)) . "]({$m}.md) | " . count($files) . " |\n";
}
$index .= '| **Total** | **' . array_sum(array_map('count', $modules)) . "** |\n";
$pages['index.md'] = $index;

foreach ($modules as $m => $files) {
    $title = $titles[$m] ?? ucfirst($m);
    $md = "<!-- generated by tools/gen-example-docs.php from examples/{$m}/; do not edit by hand -->\n\n";
    $md .= "# {$title}\n\n";
    $md .= "Runnable examples from `examples/{$m}/` (executed on both backends by the gate).\n\n";
    foreach ($files as $f) {
        $name = pathinfo($f, PATHINFO_FILENAME);
        $summary = summary("{$exRoot}/{$m}/{$f}");
        $md .= "## {$name}\n\n";
        if ($summary !== '') {
            $md .= $summary . "\n\n";
        }
        $md .= "```php\n--8<-- \"examples/{$m}/{$f}\"\n```\n\n";
    }
    $pages["{$m}.md"] = $md;
}

$dir = "{$root}/docs/examples";
if ($check) {
    $stale = [];
    foreach ($pages as $rel => $content) {
        $path = "{$dir}/{$rel}";
        if (! is_file($path) || file_get_contents($path) !== $content) {
            $stale[] = "docs/examples/{$rel}";
        }
    }
    // also flag pages on disk that no longer have a source module
    foreach (glob("{$dir}/*.md") ?: [] as $p) {
        if (! isset($pages[basename($p)])) {
            $stale[] = 'docs/examples/' . basename($p) . ' (no source module)';
        }
    }
    if ($stale === []) {
        echo "docs/examples/ is current\n";
        exit(0);
    }
    fwrite(STDERR, "stale example docs: " . implode(', ', $stale) . "\nrun: php tools/gen-example-docs.php\n");
    exit(1);
}

if (! is_dir($dir)) {
    mkdir($dir, 0o755, true);
}
foreach ($pages as $rel => $content) {
    file_put_contents("{$dir}/{$rel}", $content);
}
echo 'wrote ' . count($pages) . " pages into docs/examples/\n";
