<?php

/**
 * Generate the "NumPy / SciPy to Tessero" translation table from the kernel function registry.
 *
 *   php tools/gen-translation-table.php          # write docs/reference/numpy-tessero.md
 *   php tools/gen-translation-table.php --check    # CI/gate: non-zero exit if that page is stale
 *
 * The SciPy/NumPy name, the camelCase method and the facade class all mirror
 * tools/parity/gen-facades.php (same CLASSES map, same camel()), so the rows match the generated
 * facade methods exactly. Array creation/manipulation (NDArray) and FFT are not registry
 * functions and are covered by their own guides, not this table.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$check = in_array('--check', array_slice($argv, 1), true);
$functions = json_decode((string) file_get_contents("{$root}/tools/parity/registry.json"), true, 512, JSON_THROW_ON_ERROR)['functions'];

// module => facade class (FQCN under Tessero\), mirroring gen-facades.php CLASSES.
const FACADE = [
    'np' => 'Np',
    'linalg' => 'Linalg',
    'slinalg' => 'ScipyLinalg',
    'special' => 'Special',
    'stats' => 'Stats',
    'random' => 'Random\\Generator',
    'distance' => 'Distance',
    'sparse' => 'Sparse',
    'csgraph' => 'Csgraph',
    'signal' => 'Signal',
    'ndimage' => 'Ndimage',
];

// module => SciPy/NumPy name prefix, mirroring gen-facades.php's $ref match().
function prefix(string $mod): string
{
    return match ($mod) {
        'np' => 'numpy',
        'linalg' => 'numpy.linalg',
        'slinalg' => 'scipy.linalg',
        'distance' => 'scipy.spatial.distance',
        'csgraph' => 'scipy.sparse.csgraph',
        'random' => 'numpy.random.Generator',
        default => "scipy.{$mod}",
    };
}

function camel(string $s): string
{
    $parts = explode('_', $s);
    $out = array_shift($parts);
    foreach ($parts as $p) {
        $out .= $p === '' ? '_' : ucfirst($p);
    }

    return $out;
}

$titles = [
    'np' => 'NumPy (numpy.*)',
    'linalg' => 'numpy.linalg',
    'slinalg' => 'scipy.linalg',
    'special' => 'scipy.special',
    'stats' => 'scipy.stats',
    'random' => 'numpy.random.Generator (methods on a seeded generator)',
    'distance' => 'scipy.spatial.distance',
    'sparse' => 'scipy.sparse (constructors)',
    'csgraph' => 'scipy.sparse.csgraph',
    'signal' => 'scipy.signal',
    'ndimage' => 'scipy.ndimage',
];

$rows = [];
foreach ($functions as $name => $info) {
    [$mod, $fn] = explode('.', $name, 2);
    if (! isset(FACADE[$mod])) {
        continue;
    }
    $method = camel($fn);
    $tessero = $mod === 'random'
        ? "Tessero\\Random\\Generator->{$method}()"
        : 'Tessero\\' . FACADE[$mod] . "::{$method}()";
    $rows[$mod][] = [prefix($mod) . '.' . $fn, $tessero];
}

ob_start();
echo "<!-- generated by tools/gen-translation-table.php from tools/parity/registry.json; do not edit by hand -->\n\n";
echo "# NumPy / SciPy to Tessero\n\n";
echo "Every NumPy or SciPy function Tessero implements through the kernel registry, and the Tessero call for it.\n";
echo "Both backends expose the same classes; the native extension mirrors them under `Tessero\\Ext\\...`.\n";
echo "Array creation and manipulation (the `NDArray` methods) and the FFT are not registry functions and are\n";
echo "covered by the [arrays](../guide/arrays.md) and [FFT](../guide/fft.md) guides. See the API reference for exact signatures.\n\n";

$total = 0;
foreach (array_keys($titles) as $mod) {
    if (empty($rows[$mod])) {
        continue;
    }
    usort($rows[$mod], static fn (array $a, array $b): int => strcmp($a[0], $b[0]));
    echo "## {$titles[$mod]}\n\n| NumPy / SciPy | Tessero |\n|---|---|\n";
    foreach ($rows[$mod] as [$np, $tessero]) {
        echo "| `{$np}` | `{$tessero}` |\n";
        $total++;
    }
    echo "\n";
}
$md = ob_get_clean();

$path = "{$root}/docs/reference/numpy-tessero.md";
if ($check) {
    if (is_file($path) && file_get_contents($path) === $md) {
        echo "docs/reference/numpy-tessero.md is current\n";
        exit(0);
    }
    fwrite(STDERR, "docs/reference/numpy-tessero.md is out of date: run `php tools/gen-translation-table.php`\n");
    exit(1);
}
file_put_contents($path, $md);
echo "wrote docs/reference/numpy-tessero.md ({$total} functions)\n";
