#!/usr/bin/env bash
# Deterministically refresh Tessero's coverage statistics from the kernel's recorded parity results.
#
# Run this on the reference host (tessero-ref) AFTER a verified build of the kernel + extension, so the
# published stats reflect exactly what passes the NumPy/SciPy fixtures on BOTH backends. Every number on the
# coverage pages and the website is generated by this pipeline from census.json + results.json -- nothing is
# typed by hand (claims-check enforces that).
#
#   EXT_SO=/home/tessero/ext-build/modules/tessero.so bash tools/refresh-stats.sh "<phase label>"
#
# Steps, in strict dependency order:
#   1. Record BOTH backends into tools/parity/results.json -- SEQUENTIALLY. run-tests.php load-modify-writes
#      results.json per backend; running FFI and ext concurrently makes the last writer clobber the other
#      backend's fresh results (this silently halves a backend's coverage). Never background both at once.
#   2. Dump the API with BOTH -d ffi.enable=1 AND -d extension=<so>, or api-dump.php drops every Ext\* class.
#   3. Regenerate the inventory (gap_inventory.py), the translation table, and the metrics/usage pages
#      (report.py --record) -- these are the generated, committed stat artifacts the site is built from.
#   4. Print the authoritative headline numbers for a human/agent to copy into README.md.
set -euo pipefail
cd "$(dirname "$0")/.."
PHASE=${1:-"stats refresh"}
EXT_SO=${EXT_SO:-$HOME/ext-build/modules/tessero.so}
PY=${PYTHON:-python3}

echo "== record FFI backend =="
php -d ffi.enable=1 -d memory_limit=8G tools/parity/run-tests.php --backend=ffi | tail -1
echo "== record extension backend =="
php -d extension="$EXT_SO" -d memory_limit=8G tools/parity/run-tests.php --backend=ext | tail -1

echo "== regenerate generated artifacts =="
php -d ffi.enable=1 -d extension="$EXT_SO" tools/api-dump.php > tools/parity/api.json
$PY tools/gap_inventory.py tools/parity/api.json > docs/project/numpy-scipy-coverage.md
php tools/gen-translation-table.php >/dev/null
$PY tools/parity/report.py --record "$PHASE" | tail -3

echo
echo "== AUTHORITATIVE HEADLINE (docs/project/_generated/metrics.md) =="
grep -E "NumPy core|\*\*SciPy\*\*|registry holds|Failing fixtures" docs/project/_generated/metrics.md || true
echo
echo "== USAGE-WEIGHTED (docs/project/_generated/usage.md) =="
grep -E "NumPy and SciPy|\*\*NumPy core\*\*|\*\*SciPy\*\*" docs/project/_generated/usage.md | head -6 || true
echo
echo "Now sync README.md to these figures (claims-check validates every % against the generated pages),"
echo "run 'QUICK=1 bash tools/parity/gate.sh' (must be GATE_EXIT=0), then commit+push. The website"
echo "(tessero.org) republishes via .github/workflows/docs.yml on push to main -- which needs GitHub"
echo "Actions billing to be current; a billing block leaves the site frozen even though these docs are fresh."
