<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * scipy.sparse.csgraph: connected_components (weak) over a dense adjacency matrix.
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\Csgraph.
 */
final class Csgraph
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'bellman_ford' => 'bellmanFord',
    'breadth_first_order' => 'breadthFirstOrder',
    'connected_components' => 'connectedComponents',
    'depth_first_order' => 'depthFirstOrder',
    'dijkstra' => 'dijkstra',
    'floyd_warshall' => 'floydWarshall',
    'johnson' => 'johnson',
    'laplacian' => 'laplacian',
    'shortest_path' => 'shortestPath',
    'structural_rank' => 'structuralRank',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: Csgraph::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("Csgraph::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * Bellman-Ford all-pairs shortest paths, allows negative weights (scipy.sparse.csgraph.bellman_ford; indices=None).
     *
     * scipy.sparse.csgraph.bellman_ford
     */
    public static function bellmanFord(mixed $csgraph, mixed $directed = true, mixed $indices = null, mixed $returnPredecessors = false, mixed $unweighted = false): mixed
    {
        return Registry::routine('csgraph.bellman_ford', [$csgraph, $directed, $indices, $returnPredecessors, $unweighted]);
    }

    /**
     * Breadth-first traversal order and predecessors (scipy.sparse.csgraph.breadth_first_order).
     *
     * scipy.sparse.csgraph.breadth_first_order
     *
     * @return mixed one array, or an array keyed by node_array, predecessors when several results are requested
     */
    public static function breadthFirstOrder(mixed $csgraph, mixed $iStart, mixed $directed = true, mixed $returnPredecessors = true): mixed
    {
        return Registry::routine('csgraph.breadth_first_order', [$csgraph, $iStart, $directed, $returnPredecessors]);
    }

    /**
     * Connected components of a graph, weak connectivity (scipy.sparse.csgraph.connected_components).
     *
     * scipy.sparse.csgraph.connected_components
     *
     * @return mixed one array, or an array keyed by n_components, labels when several results are requested
     */
    public static function connectedComponents(mixed $csgraph, mixed $directed = true, mixed $connection = 'weak'): mixed
    {
        return Registry::routine('csgraph.connected_components', [$csgraph, $directed, $connection]);
    }

    /**
     * Depth-first traversal order and predecessors (scipy.sparse.csgraph.depth_first_order).
     *
     * scipy.sparse.csgraph.depth_first_order
     *
     * @return mixed one array, or an array keyed by node_array, predecessors when several results are requested
     */
    public static function depthFirstOrder(mixed $csgraph, mixed $iStart, mixed $directed = true, mixed $returnPredecessors = true): mixed
    {
        return Registry::routine('csgraph.depth_first_order', [$csgraph, $iStart, $directed, $returnPredecessors]);
    }

    /**
     * Dijkstra all-pairs shortest paths, non-negative weights (scipy.sparse.csgraph.dijkstra; indices=None).
     *
     * scipy.sparse.csgraph.dijkstra
     */
    public static function dijkstra(mixed $csgraph, mixed $directed = true, mixed $indices = null, mixed $returnPredecessors = false, mixed $unweighted = false): mixed
    {
        return Registry::routine('csgraph.dijkstra', [$csgraph, $directed, $indices, $returnPredecessors, $unweighted]);
    }

    /**
     * Floyd-Warshall all-pairs shortest paths (scipy.sparse.csgraph.floyd_warshall).
     *
     * scipy.sparse.csgraph.floyd_warshall
     */
    public static function floydWarshall(mixed $csgraph, mixed $directed = true, mixed $returnPredecessors = false, mixed $unweighted = false, mixed $overwrite = false): mixed
    {
        return Registry::routine('csgraph.floyd_warshall', [$csgraph, $directed, $returnPredecessors, $unweighted, $overwrite]);
    }

    /**
     * Johnson all-pairs shortest paths (scipy.sparse.csgraph.johnson; indices=None).
     *
     * scipy.sparse.csgraph.johnson
     */
    public static function johnson(mixed $csgraph, mixed $directed = true, mixed $indices = null, mixed $returnPredecessors = false, mixed $unweighted = false): mixed
    {
        return Registry::routine('csgraph.johnson', [$csgraph, $directed, $indices, $returnPredecessors, $unweighted]);
    }

    /**
     * Graph Laplacian, plain or symmetric-normalized (scipy.sparse.csgraph.laplacian).
     *
     * scipy.sparse.csgraph.laplacian
     */
    public static function laplacian(mixed $csgraph, mixed $normed = false): mixed
    {
        return Registry::routine('csgraph.laplacian', [$csgraph, $normed]);
    }

    /**
     * All-pairs shortest path distance matrix (scipy.sparse.csgraph.shortest_path; dense, indices=None).
     *
     * scipy.sparse.csgraph.shortest_path
     */
    public static function shortestPath(mixed $csgraph, mixed $method = 'auto', mixed $directed = true, mixed $returnPredecessors = false, mixed $unweighted = false, mixed $overwrite = false, mixed $indices = null): mixed
    {
        return Registry::routine('csgraph.shortest_path', [$csgraph, $method, $directed, $returnPredecessors, $unweighted, $overwrite, $indices]);
    }

    /**
     * Structural rank of a graph's sparsity pattern (scipy.sparse.csgraph.structural_rank).
     *
     * scipy.sparse.csgraph.structural_rank
     */
    public static function structuralRank(mixed $graph): mixed
    {
        return Registry::routine('csgraph.structural_rank', [$graph]);
    }
}
