<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * scipy.spatial.distance: pdist, cdist and squareform over real float64 data, with the common metrics (euclidean, cityblock, cosine, correlation, chebyshev, minkowski, ...).
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\Distance.
 */
final class Distance
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'braycurtis' => 'braycurtis',
    'canberra' => 'canberra',
    'cdist' => 'cdist',
    'chebyshev' => 'chebyshev',
    'cityblock' => 'cityblock',
    'correlation' => 'correlation',
    'cosine' => 'cosine',
    'dice' => 'dice',
    'euclidean' => 'euclidean',
    'hamming' => 'hamming',
    'is_valid_dm' => 'isValidDm',
    'is_valid_y' => 'isValidY',
    'jaccard' => 'jaccard',
    'jensenshannon' => 'jensenshannon',
    'mahalanobis' => 'mahalanobis',
    'minkowski' => 'minkowski',
    'num_obs_dm' => 'numObsDm',
    'num_obs_y' => 'numObsY',
    'pdist' => 'pdist',
    'rogerstanimoto' => 'rogerstanimoto',
    'russellrao' => 'russellrao',
    'seuclidean' => 'seuclidean',
    'sokalsneath' => 'sokalsneath',
    'sqeuclidean' => 'sqeuclidean',
    'squareform' => 'squareform',
    'yule' => 'yule',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: Distance::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("Distance::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * Bray-Curtis distance between two 1-D arrays (scipy.spatial.distance.braycurtis).
     *
     * scipy.spatial.distance.braycurtis
     */
    public static function braycurtis(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.braycurtis', [$u, $v, $w]);
    }

    /**
     * Canberra distance between two 1-D arrays (scipy.spatial.distance.canberra).
     *
     * scipy.spatial.distance.canberra
     */
    public static function canberra(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.canberra', [$u, $v, $w]);
    }

    /**
     * Distances between each pair of rows of XA and XB (scipy.spatial.distance.cdist); real float64.
     *
     * scipy.spatial.distance.cdist
     */
    public static function cdist(mixed $XA, mixed $XB, mixed $metric = null, mixed $p = null): mixed
    {
        return Registry::routine('distance.cdist', [$XA, $XB, $metric, $p]);
    }

    /**
     * Chebyshev (L-infinity) distance (scipy.spatial.distance.chebyshev).
     *
     * scipy.spatial.distance.chebyshev
     */
    public static function chebyshev(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.chebyshev', [$u, $v, $w]);
    }

    /**
     * Manhattan (city block) distance (scipy.spatial.distance.cityblock).
     *
     * scipy.spatial.distance.cityblock
     */
    public static function cityblock(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.cityblock', [$u, $v, $w]);
    }

    /**
     * Correlation distance between two 1-D arrays (scipy.spatial.distance.correlation).
     *
     * scipy.spatial.distance.correlation
     */
    public static function correlation(mixed $u, mixed $v, mixed $w = null, mixed $centered = true): mixed
    {
        return Registry::routine('distance.correlation', [$u, $v, $w, $centered]);
    }

    /**
     * Cosine distance between two 1-D arrays (scipy.spatial.distance.cosine).
     *
     * scipy.spatial.distance.cosine
     */
    public static function cosine(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.cosine', [$u, $v, $w]);
    }

    /**
     * Dice dissimilarity between two boolean 1-D arrays (scipy.spatial.distance.dice).
     *
     * scipy.spatial.distance.dice
     */
    public static function dice(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.dice', [$u, $v, $w]);
    }

    /**
     * Euclidean distance between two 1-D arrays (scipy.spatial.distance.euclidean).
     *
     * scipy.spatial.distance.euclidean
     */
    public static function euclidean(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.euclidean', [$u, $v, $w]);
    }

    /**
     * Hamming distance, the proportion of disagreeing components (scipy.spatial.distance.hamming).
     *
     * scipy.spatial.distance.hamming
     */
    public static function hamming(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.hamming', [$u, $v, $w]);
    }

    /**
     * Whether D is a valid redundant distance matrix (scipy.spatial.distance.is_valid_dm).
     *
     * scipy.spatial.distance.is_valid_dm
     */
    public static function isValidDm(mixed $D, mixed $tol = 0.0, mixed $throw = false, mixed $name = 'D', mixed $warning = false): mixed
    {
        return Registry::routine('distance.is_valid_dm', [$D, $tol, $throw, $name, $warning]);
    }

    /**
     * Whether y is a valid condensed distance vector (scipy.spatial.distance.is_valid_y).
     *
     * scipy.spatial.distance.is_valid_y
     */
    public static function isValidY(mixed $y, mixed $warning = false, mixed $throw = false, mixed $name = null): mixed
    {
        return Registry::routine('distance.is_valid_y', [$y, $warning, $throw, $name]);
    }

    /**
     * Jaccard-Needham dissimilarity between two boolean 1-D arrays (scipy.spatial.distance.jaccard).
     *
     * scipy.spatial.distance.jaccard
     */
    public static function jaccard(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.jaccard', [$u, $v, $w]);
    }

    /**
     * Jensen-Shannon distance between two probability arrays (scipy.spatial.distance.jensenshannon).
     *
     * scipy.spatial.distance.jensenshannon
     */
    public static function jensenshannon(mixed $p, mixed $q, mixed $base = null): mixed
    {
        return Registry::routine('distance.jensenshannon', [$p, $q, $base]);
    }

    /**
     * Mahalanobis distance given the inverse covariance VI (scipy.spatial.distance.mahalanobis).
     *
     * scipy.spatial.distance.mahalanobis
     */
    public static function mahalanobis(mixed $u, mixed $v, mixed $VI): mixed
    {
        return Registry::routine('distance.mahalanobis', [$u, $v, $VI]);
    }

    /**
     * Minkowski distance of order p (scipy.spatial.distance.minkowski).
     *
     * scipy.spatial.distance.minkowski
     */
    public static function minkowski(mixed $u, mixed $v, mixed $p = 2, mixed $w = null): mixed
    {
        return Registry::routine('distance.minkowski', [$u, $v, $p, $w]);
    }

    /**
     * Number of observations in a square distance matrix (scipy.spatial.distance.num_obs_dm).
     *
     * scipy.spatial.distance.num_obs_dm
     */
    public static function numObsDm(mixed $d): mixed
    {
        return Registry::routine('distance.num_obs_dm', [$d]);
    }

    /**
     * Number of observations in a condensed distance vector (scipy.spatial.distance.num_obs_y).
     *
     * scipy.spatial.distance.num_obs_y
     */
    public static function numObsY(mixed $Y): mixed
    {
        return Registry::routine('distance.num_obs_y', [$Y]);
    }

    /**
     * Pairwise distances between the rows of X, condensed (scipy.spatial.distance.pdist); real float64.
     *
     * scipy.spatial.distance.pdist
     */
    public static function pdist(mixed $X, mixed $metric = null, mixed $p = null): mixed
    {
        return Registry::routine('distance.pdist', [$X, $metric, $p]);
    }

    /**
     * Rogers-Tanimoto dissimilarity between two boolean 1-D arrays (scipy.spatial.distance.rogerstanimoto).
     *
     * scipy.spatial.distance.rogerstanimoto
     */
    public static function rogerstanimoto(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.rogerstanimoto', [$u, $v, $w]);
    }

    /**
     * Russell-Rao dissimilarity between two boolean 1-D arrays (scipy.spatial.distance.russellrao).
     *
     * scipy.spatial.distance.russellrao
     */
    public static function russellrao(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.russellrao', [$u, $v, $w]);
    }

    /**
     * Standardized Euclidean distance given the variance vector V (scipy.spatial.distance.seuclidean).
     *
     * scipy.spatial.distance.seuclidean
     */
    public static function seuclidean(mixed $u, mixed $v, mixed $V): mixed
    {
        return Registry::routine('distance.seuclidean', [$u, $v, $V]);
    }

    /**
     * Sokal-Sneath dissimilarity between two boolean 1-D arrays (scipy.spatial.distance.sokalsneath).
     *
     * scipy.spatial.distance.sokalsneath
     */
    public static function sokalsneath(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.sokalsneath', [$u, $v, $w]);
    }

    /**
     * Squared Euclidean distance (scipy.spatial.distance.sqeuclidean).
     *
     * scipy.spatial.distance.sqeuclidean
     */
    public static function sqeuclidean(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.sqeuclidean', [$u, $v, $w]);
    }

    /**
     * Convert between a condensed distance vector and a square form (scipy.spatial.distance.squareform).
     *
     * scipy.spatial.distance.squareform
     */
    public static function squareform(mixed $X): mixed
    {
        return Registry::routine('distance.squareform', [$X]);
    }

    /**
     * Yule dissimilarity between two boolean 1-D arrays (scipy.spatial.distance.yule).
     *
     * scipy.spatial.distance.yule
     */
    public static function yule(mixed $u, mixed $v, mixed $w = null): mixed
    {
        return Registry::routine('distance.yule', [$u, $v, $w]);
    }
}
