<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * scipy.interpolate: 1-D piecewise-cubic interpolation evaluated at query points (pchip_interpolate, PchipInterpolator, Akima1DInterpolator, CubicSpline not-a-knot, CubicHermiteSpline), shared by both backends through the kernel.
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\Interpolate.
 */
final class Interpolate
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'Akima1DInterpolator' => 'Akima1DInterpolator',
    'CubicHermiteSpline' => 'CubicHermiteSpline',
    'CubicSpline' => 'CubicSpline',
    'PchipInterpolator' => 'PchipInterpolator',
    'barycentric_interpolate' => 'barycentricInterpolate',
    'krogh_interpolate' => 'kroghInterpolate',
    'pchip_interpolate' => 'pchipInterpolate',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: Interpolate::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("Interpolate::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * Akima piecewise-cubic interpolation evaluated at xnew (scipy.interpolate.Akima1DInterpolator).
     *
     * scipy.interpolate.Akima1DInterpolator
     */
    public static function Akima1DInterpolator(mixed $x, mixed $y, mixed $xnew): mixed
    {
        return Registry::routine('interpolate.Akima1DInterpolator', [$x, $y, $xnew]);
    }

    /**
     * Cubic Hermite spline with given derivatives evaluated at xnew (scipy.interpolate.CubicHermiteSpline).
     *
     * scipy.interpolate.CubicHermiteSpline
     */
    public static function CubicHermiteSpline(mixed $x, mixed $y, mixed $dydx, mixed $xnew): mixed
    {
        return Registry::routine('interpolate.CubicHermiteSpline', [$x, $y, $dydx, $xnew]);
    }

    /**
     * Not-a-knot cubic spline evaluated at xnew (scipy.interpolate.CubicSpline).
     *
     * scipy.interpolate.CubicSpline
     */
    public static function CubicSpline(mixed $x, mixed $y, mixed $xnew): mixed
    {
        return Registry::routine('interpolate.CubicSpline', [$x, $y, $xnew]);
    }

    /**
     * PCHIP monotone cubic interpolation evaluated at xnew (scipy.interpolate.PchipInterpolator).
     *
     * scipy.interpolate.PchipInterpolator
     */
    public static function PchipInterpolator(mixed $x, mixed $y, mixed $xnew): mixed
    {
        return Registry::routine('interpolate.PchipInterpolator', [$x, $y, $xnew]);
    }

    /**
     * Barycentric Lagrange polynomial interpolation evaluated at x (scipy.interpolate.barycentric_interpolate).
     *
     * scipy.interpolate.barycentric_interpolate
     */
    public static function barycentricInterpolate(mixed $xi, mixed $yi, mixed $x): mixed
    {
        return Registry::routine('interpolate.barycentric_interpolate', [$xi, $yi, $x]);
    }

    /**
     * Polynomial interpolation (Newton divided differences) evaluated at x (scipy.interpolate.krogh_interpolate).
     *
     * scipy.interpolate.krogh_interpolate
     */
    public static function kroghInterpolate(mixed $xi, mixed $yi, mixed $x): mixed
    {
        return Registry::routine('interpolate.krogh_interpolate', [$xi, $yi, $x]);
    }

    /**
     * Monotone piecewise-cubic (PCHIP) interpolation evaluated at x (scipy.interpolate.pchip_interpolate).
     *
     * scipy.interpolate.pchip_interpolate
     */
    public static function pchipInterpolate(mixed $xi, mixed $yi, mixed $x): mixed
    {
        return Registry::routine('interpolate.pchip_interpolate', [$xi, $yi, $x]);
    }
}
