<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * scipy.ndimage: generate_binary_structure, 2-D connected-component label, and 2-D convolve with the standard boundary modes.
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\Ndimage.
 */
final class Ndimage
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'affine_transform' => 'affineTransform',
    'binary_closing' => 'binaryClosing',
    'binary_dilation' => 'binaryDilation',
    'binary_erosion' => 'binaryErosion',
    'binary_fill_holes' => 'binaryFillHoles',
    'binary_hit_or_miss' => 'binaryHitOrMiss',
    'binary_opening' => 'binaryOpening',
    'binary_propagation' => 'binaryPropagation',
    'black_tophat' => 'blackTophat',
    'center_of_mass' => 'centerOfMass',
    'convolve' => 'convolve',
    'convolve1d' => 'convolve1d',
    'correlate' => 'correlate',
    'correlate1d' => 'correlate1d',
    'distance_transform_bf' => 'distanceTransformBf',
    'distance_transform_cdt' => 'distanceTransformCdt',
    'distance_transform_edt' => 'distanceTransformEdt',
    'extrema' => 'extrema',
    'find_objects' => 'findObjects',
    'fourier_ellipsoid' => 'fourierEllipsoid',
    'fourier_gaussian' => 'fourierGaussian',
    'fourier_shift' => 'fourierShift',
    'fourier_uniform' => 'fourierUniform',
    'gaussian_filter' => 'gaussianFilter',
    'gaussian_filter1d' => 'gaussianFilter1d',
    'gaussian_gradient_magnitude' => 'gaussianGradientMagnitude',
    'gaussian_laplace' => 'gaussianLaplace',
    'generate_binary_structure' => 'generateBinaryStructure',
    'grey_closing' => 'greyClosing',
    'grey_dilation' => 'greyDilation',
    'grey_erosion' => 'greyErosion',
    'grey_opening' => 'greyOpening',
    'histogram' => 'histogram',
    'iterate_structure' => 'iterateStructure',
    'label' => 'label',
    'laplace' => 'laplace',
    'map_coordinates' => 'mapCoordinates',
    'maximum' => 'maximum',
    'maximum_filter' => 'maximumFilter',
    'maximum_filter1d' => 'maximumFilter1d',
    'maximum_position' => 'maximumPosition',
    'mean' => 'mean',
    'median' => 'median',
    'median_filter' => 'medianFilter',
    'minimum' => 'minimum',
    'minimum_filter' => 'minimumFilter',
    'minimum_filter1d' => 'minimumFilter1d',
    'minimum_position' => 'minimumPosition',
    'morphological_gradient' => 'morphologicalGradient',
    'morphological_laplace' => 'morphologicalLaplace',
    'percentile_filter' => 'percentileFilter',
    'prewitt' => 'prewitt',
    'rank_filter' => 'rankFilter',
    'rotate' => 'rotate',
    'shift' => 'shift',
    'sobel' => 'sobel',
    'spline_filter' => 'splineFilter',
    'spline_filter1d' => 'splineFilter1d',
    'standard_deviation' => 'standardDeviation',
    'sum' => 'sum',
    'sum_labels' => 'sumLabels',
    'uniform_filter' => 'uniformFilter',
    'uniform_filter1d' => 'uniformFilter1d',
    'variance' => 'variance',
    'white_tophat' => 'whiteTophat',
    'zoom' => 'zoom',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: Ndimage::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("Ndimage::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * Apply an affine transform by interpolation, order 0/1 (scipy.ndimage.affine_transform).
     *
     * scipy.ndimage.affine_transform
     */
    public static function affineTransform(mixed $input, mixed $matrix, mixed $offset = 0.0, mixed $outputShape = null, mixed $order = 3, mixed $mode = 'constant', mixed $cval = 0.0, mixed $prefilter = true): mixed
    {
        return Registry::routine('ndimage.affine_transform', [$input, $matrix, $offset, $outputShape, $order, $mode, $cval, $prefilter]);
    }

    /**
     * Binary closing: dilation then erosion of a 2-D image (scipy.ndimage.binary_closing).
     *
     * scipy.ndimage.binary_closing
     */
    public static function binaryClosing(mixed $input, mixed $structure = null): mixed
    {
        return Registry::routine('ndimage.binary_closing', [$input, $structure]);
    }

    /**
     * Binary dilation of a 2-D image (scipy.ndimage.binary_dilation).
     *
     * scipy.ndimage.binary_dilation
     */
    public static function binaryDilation(mixed $input, mixed $structure = null): mixed
    {
        return Registry::routine('ndimage.binary_dilation', [$input, $structure]);
    }

    /**
     * Binary erosion of a 2-D image (scipy.ndimage.binary_erosion).
     *
     * scipy.ndimage.binary_erosion
     */
    public static function binaryErosion(mixed $input, mixed $structure = null): mixed
    {
        return Registry::routine('ndimage.binary_erosion', [$input, $structure]);
    }

    /**
     * Fill the holes in a binary 2-D image (scipy.ndimage.binary_fill_holes).
     *
     * scipy.ndimage.binary_fill_holes
     */
    public static function binaryFillHoles(mixed $input, mixed $structure = null): mixed
    {
        return Registry::routine('ndimage.binary_fill_holes', [$input, $structure]);
    }

    /**
     * Binary hit-or-miss transform of a 2-D image (scipy.ndimage.binary_hit_or_miss).
     *
     * scipy.ndimage.binary_hit_or_miss
     */
    public static function binaryHitOrMiss(mixed $input, mixed $structure1 = null, mixed $structure2 = null): mixed
    {
        return Registry::routine('ndimage.binary_hit_or_miss', [$input, $structure1, $structure2]);
    }

    /**
     * Binary opening: erosion then dilation of a 2-D image (scipy.ndimage.binary_opening).
     *
     * scipy.ndimage.binary_opening
     */
    public static function binaryOpening(mixed $input, mixed $structure = null): mixed
    {
        return Registry::routine('ndimage.binary_opening', [$input, $structure]);
    }

    /**
     * Binary propagation: dilate within a mask until stable (scipy.ndimage.binary_propagation).
     *
     * scipy.ndimage.binary_propagation
     */
    public static function binaryPropagation(mixed $input, mixed $structure = null, mixed $mask = null): mixed
    {
        return Registry::routine('ndimage.binary_propagation', [$input, $structure, $mask]);
    }

    /**
     * Black tophat: greyscale closing minus the input (scipy.ndimage.black_tophat).
     *
     * scipy.ndimage.black_tophat
     */
    public static function blackTophat(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.black_tophat', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * Center of mass of labeled regions (scipy.ndimage.center_of_mass).
     *
     * scipy.ndimage.center_of_mass
     */
    public static function centerOfMass(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.center_of_mass', [$input, $labels, $index]);
    }

    /**
     * 2-D convolution with boundary handling (scipy.ndimage.convolve).
     *
     * scipy.ndimage.convolve
     */
    public static function convolve(mixed $input, mixed $weights, mixed $mode = 'reflect', mixed $cval = 0.0): mixed
    {
        return Registry::routine('ndimage.convolve', [$input, $weights, $mode, $cval]);
    }

    /**
     * 1-D convolution along an axis (scipy.ndimage.convolve1d).
     *
     * scipy.ndimage.convolve1d
     */
    public static function convolve1d(mixed $input, mixed $weights, mixed $axis = -1, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.convolve1d', [$input, $weights, $axis, $mode, $cval, $origin]);
    }

    /**
     * Multidimensional correlation with a weights array (scipy.ndimage.correlate).
     *
     * scipy.ndimage.correlate
     */
    public static function correlate(mixed $input, mixed $weights, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.correlate', [$input, $weights, $mode, $cval, $origin]);
    }

    /**
     * 1-D correlation along an axis with boundary handling (scipy.ndimage.correlate1d).
     *
     * scipy.ndimage.correlate1d
     */
    public static function correlate1d(mixed $input, mixed $weights, mixed $axis = -1, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.correlate1d', [$input, $weights, $axis, $mode, $cval, $origin]);
    }

    /**
     * Brute-force distance to the nearest zero, any metric (scipy.ndimage.distance_transform_bf).
     *
     * scipy.ndimage.distance_transform_bf
     */
    public static function distanceTransformBf(mixed $input, mixed $metric = 'euclidean', mixed $sampling = null): mixed
    {
        return Registry::routine('ndimage.distance_transform_bf', [$input, $metric, $sampling]);
    }

    /**
     * Chamfer (chessboard/taxicab) distance to the nearest zero (scipy.ndimage.distance_transform_cdt).
     *
     * scipy.ndimage.distance_transform_cdt
     */
    public static function distanceTransformCdt(mixed $input, mixed $metric = 'chessboard'): mixed
    {
        return Registry::routine('ndimage.distance_transform_cdt', [$input, $metric]);
    }

    /**
     * Exact Euclidean distance to the nearest zero (scipy.ndimage.distance_transform_edt).
     *
     * scipy.ndimage.distance_transform_edt
     */
    public static function distanceTransformEdt(mixed $input, mixed $sampling = null): mixed
    {
        return Registry::routine('ndimage.distance_transform_edt', [$input, $sampling]);
    }

    /**
     * Min, max and their positions over labeled regions (scipy.ndimage.extrema).
     *
     * scipy.ndimage.extrema
     *
     * @return mixed one array, or an array keyed by minimum, maximum, min_position, max_position when several results are requested
     */
    public static function extrema(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.extrema', [$input, $labels, $index]);
    }

    /**
     * Bounding box of each label as an (L, ndim, 2) array of start/stop (scipy.ndimage.find_objects).
     *
     * scipy.ndimage.find_objects
     */
    public static function findObjects(mixed $input, mixed $maxLabel = 0): mixed
    {
        return Registry::routine('ndimage.find_objects', [$input, $maxLabel]);
    }

    /**
     * Multiply an FFT by the transform of an ellipsoid, rank <= 3 (scipy.ndimage.fourier_ellipsoid).
     *
     * scipy.ndimage.fourier_ellipsoid
     */
    public static function fourierEllipsoid(mixed $input, mixed $size, mixed $n = -1, mixed $axis = -1): mixed
    {
        return Registry::routine('ndimage.fourier_ellipsoid', [$input, $size, $n, $axis]);
    }

    /**
     * Multiply an FFT by the transform of a Gaussian (scipy.ndimage.fourier_gaussian).
     *
     * scipy.ndimage.fourier_gaussian
     */
    public static function fourierGaussian(mixed $input, mixed $sigma, mixed $n = -1, mixed $axis = -1): mixed
    {
        return Registry::routine('ndimage.fourier_gaussian', [$input, $sigma, $n, $axis]);
    }

    /**
     * Multiply an FFT by a linear phase to shift the image (scipy.ndimage.fourier_shift).
     *
     * scipy.ndimage.fourier_shift
     */
    public static function fourierShift(mixed $input, mixed $shift, mixed $n = -1, mixed $axis = -1): mixed
    {
        return Registry::routine('ndimage.fourier_shift', [$input, $shift, $n, $axis]);
    }

    /**
     * Multiply an FFT by the transform of a uniform box (scipy.ndimage.fourier_uniform).
     *
     * scipy.ndimage.fourier_uniform
     */
    public static function fourierUniform(mixed $input, mixed $size, mixed $n = -1, mixed $axis = -1): mixed
    {
        return Registry::routine('ndimage.fourier_uniform', [$input, $size, $n, $axis]);
    }

    /**
     * Multidimensional Gaussian filter, order 0 (scipy.ndimage.gaussian_filter).
     *
     * scipy.ndimage.gaussian_filter
     */
    public static function gaussianFilter(mixed $input, mixed $sigma, mixed $order = 0, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $truncate = 4.0, mixed $radius = null): mixed
    {
        return Registry::routine('ndimage.gaussian_filter', [$input, $sigma, $order, $mode, $cval, $truncate, $radius]);
    }

    /**
     * 1-D Gaussian filter along an axis, order 0 (scipy.ndimage.gaussian_filter1d).
     *
     * scipy.ndimage.gaussian_filter1d
     */
    public static function gaussianFilter1d(mixed $input, mixed $sigma, mixed $axis = -1, mixed $order = 0, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $truncate = 4.0, mixed $radius = null): mixed
    {
        return Registry::routine('ndimage.gaussian_filter1d', [$input, $sigma, $axis, $order, $mode, $cval, $truncate, $radius]);
    }

    /**
     * Gradient magnitude using Gaussian derivatives (scipy.ndimage.gaussian_gradient_magnitude).
     *
     * scipy.ndimage.gaussian_gradient_magnitude
     */
    public static function gaussianGradientMagnitude(mixed $input, mixed $sigma, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $truncate = 4.0): mixed
    {
        return Registry::routine('ndimage.gaussian_gradient_magnitude', [$input, $sigma, $mode, $cval, $truncate]);
    }

    /**
     * Laplace filter using Gaussian second derivatives (scipy.ndimage.gaussian_laplace).
     *
     * scipy.ndimage.gaussian_laplace
     */
    public static function gaussianLaplace(mixed $input, mixed $sigma, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $truncate = 4.0): mixed
    {
        return Registry::routine('ndimage.gaussian_laplace', [$input, $sigma, $mode, $cval, $truncate]);
    }

    /**
     * Boolean structuring element for binary morphology (scipy.ndimage.generate_binary_structure).
     *
     * scipy.ndimage.generate_binary_structure
     */
    public static function generateBinaryStructure(mixed $rank, mixed $connectivity): mixed
    {
        return Registry::routine('ndimage.generate_binary_structure', [$rank, $connectivity]);
    }

    /**
     * Greyscale closing: dilation then erosion with a flat box SE (scipy.ndimage.grey_closing).
     *
     * scipy.ndimage.grey_closing
     */
    public static function greyClosing(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.grey_closing', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * Greyscale dilation with a flat box structuring element (scipy.ndimage.grey_dilation).
     *
     * scipy.ndimage.grey_dilation
     */
    public static function greyDilation(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.grey_dilation', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * Greyscale erosion with a flat box structuring element (scipy.ndimage.grey_erosion).
     *
     * scipy.ndimage.grey_erosion
     */
    public static function greyErosion(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.grey_erosion', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * Greyscale opening: erosion then dilation with a flat box SE (scipy.ndimage.grey_opening).
     *
     * scipy.ndimage.grey_opening
     */
    public static function greyOpening(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.grey_opening', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * Histogram of array values over a labeled region (scipy.ndimage.histogram).
     *
     * scipy.ndimage.histogram
     */
    public static function histogram(mixed $input, mixed $min, mixed $max, mixed $bins, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.histogram', [$input, $min, $max, $bins, $labels, $index]);
    }

    /**
     * A 3x3 structuring element dilated by itself iterations-1 times (scipy.ndimage.iterate_structure).
     *
     * scipy.ndimage.iterate_structure
     */
    public static function iterateStructure(mixed $structure, mixed $iterations): mixed
    {
        return Registry::routine('ndimage.iterate_structure', [$structure, $iterations]);
    }

    /**
     * Label connected components of a 2-D array, row-major (scipy.ndimage.label).
     *
     * scipy.ndimage.label
     *
     * @return mixed one array, or an array keyed by labels, num when several results are requested
     */
    public static function label(mixed $input, mixed $structure = null): mixed
    {
        return Registry::routine('ndimage.label', [$input, $structure]);
    }

    /**
     * Laplace filter: sum of second derivatives over all axes (scipy.ndimage.laplace).
     *
     * scipy.ndimage.laplace
     */
    public static function laplace(mixed $input, mixed $mode = 'reflect', mixed $cval = 0.0): mixed
    {
        return Registry::routine('ndimage.laplace', [$input, $mode, $cval]);
    }

    /**
     * Interpolate an array at given coordinates, order 0/1 (scipy.ndimage.map_coordinates).
     *
     * scipy.ndimage.map_coordinates
     */
    public static function mapCoordinates(mixed $input, mixed $coordinates, mixed $order = 3, mixed $mode = 'constant', mixed $cval = 0.0, mixed $prefilter = true): mixed
    {
        return Registry::routine('ndimage.map_coordinates', [$input, $coordinates, $order, $mode, $cval, $prefilter]);
    }

    /**
     * Maximum of array values over labeled regions (scipy.ndimage.maximum).
     *
     * scipy.ndimage.maximum
     */
    public static function maximum(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.maximum', [$input, $labels, $index]);
    }

    /**
     * Multidimensional windowed maximum filter, box footprint (scipy.ndimage.maximum_filter).
     *
     * scipy.ndimage.maximum_filter
     */
    public static function maximumFilter(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.maximum_filter', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * 1-D sliding-window maximum along an axis (scipy.ndimage.maximum_filter1d).
     *
     * scipy.ndimage.maximum_filter1d
     */
    public static function maximumFilter1d(mixed $input, mixed $size, mixed $axis = -1, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.maximum_filter1d', [$input, $size, $axis, $mode, $cval, $origin]);
    }

    /**
     * Position of the maximum over labeled regions (scipy.ndimage.maximum_position).
     *
     * scipy.ndimage.maximum_position
     */
    public static function maximumPosition(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.maximum_position', [$input, $labels, $index]);
    }

    /**
     * Mean of array values over labeled regions (scipy.ndimage.mean).
     *
     * scipy.ndimage.mean
     */
    public static function mean(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.mean', [$input, $labels, $index]);
    }

    /**
     * Median of array values over labeled regions (scipy.ndimage.median).
     *
     * scipy.ndimage.median
     */
    public static function median(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.median', [$input, $labels, $index]);
    }

    /**
     * Multidimensional median filter, box footprint (scipy.ndimage.median_filter).
     *
     * scipy.ndimage.median_filter
     */
    public static function medianFilter(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.median_filter', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * Minimum of array values over labeled regions (scipy.ndimage.minimum).
     *
     * scipy.ndimage.minimum
     */
    public static function minimum(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.minimum', [$input, $labels, $index]);
    }

    /**
     * Multidimensional windowed minimum filter, box footprint (scipy.ndimage.minimum_filter).
     *
     * scipy.ndimage.minimum_filter
     */
    public static function minimumFilter(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.minimum_filter', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * 1-D sliding-window minimum along an axis (scipy.ndimage.minimum_filter1d).
     *
     * scipy.ndimage.minimum_filter1d
     */
    public static function minimumFilter1d(mixed $input, mixed $size, mixed $axis = -1, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.minimum_filter1d', [$input, $size, $axis, $mode, $cval, $origin]);
    }

    /**
     * Position of the minimum over labeled regions (scipy.ndimage.minimum_position).
     *
     * scipy.ndimage.minimum_position
     */
    public static function minimumPosition(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.minimum_position', [$input, $labels, $index]);
    }

    /**
     * Morphological gradient: greyscale dilation minus erosion (scipy.ndimage.morphological_gradient).
     *
     * scipy.ndimage.morphological_gradient
     */
    public static function morphologicalGradient(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.morphological_gradient', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * Morphological laplace: dilation + erosion - 2*input (scipy.ndimage.morphological_laplace).
     *
     * scipy.ndimage.morphological_laplace
     */
    public static function morphologicalLaplace(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.morphological_laplace', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * Multidimensional percentile filter over a box footprint (scipy.ndimage.percentile_filter).
     *
     * scipy.ndimage.percentile_filter
     */
    public static function percentileFilter(mixed $input, mixed $percentile, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.percentile_filter', [$input, $percentile, $size, $mode, $cval, $origin]);
    }

    /**
     * Prewitt edge filter along an axis (scipy.ndimage.prewitt).
     *
     * scipy.ndimage.prewitt
     */
    public static function prewitt(mixed $input, mixed $axis = -1, mixed $mode = 'reflect', mixed $cval = 0.0): mixed
    {
        return Registry::routine('ndimage.prewitt', [$input, $axis, $mode, $cval]);
    }

    /**
     * Multidimensional rank filter ( order statistic) over a box footprint (scipy.ndimage.rank_filter).
     *
     * scipy.ndimage.rank_filter
     */
    public static function rankFilter(mixed $input, mixed $rank, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.rank_filter', [$input, $rank, $size, $mode, $cval, $origin]);
    }

    /**
     * Rotate an array in a plane by interpolation, order 0/1 (scipy.ndimage.rotate).
     *
     * scipy.ndimage.rotate
     */
    public static function rotate(mixed $input, mixed $angle, mixed $axes = null, mixed $reshape = true, mixed $order = 3, mixed $mode = 'constant', mixed $cval = 0.0, mixed $prefilter = true): mixed
    {
        return Registry::routine('ndimage.rotate', [$input, $angle, $axes, $reshape, $order, $mode, $cval, $prefilter]);
    }

    /**
     * Shift an array by interpolation, order 0/1 (scipy.ndimage.shift).
     *
     * scipy.ndimage.shift
     */
    public static function shift(mixed $input, mixed $shift, mixed $order = 3, mixed $mode = 'constant', mixed $cval = 0.0, mixed $prefilter = true): mixed
    {
        return Registry::routine('ndimage.shift', [$input, $shift, $order, $mode, $cval, $prefilter]);
    }

    /**
     * Sobel edge filter along an axis (scipy.ndimage.sobel).
     *
     * scipy.ndimage.sobel
     */
    public static function sobel(mixed $input, mixed $axis = -1, mixed $mode = 'reflect', mixed $cval = 0.0): mixed
    {
        return Registry::routine('ndimage.sobel', [$input, $axis, $mode, $cval]);
    }

    /**
     * N-D B-spline prefilter over all axes (scipy.ndimage.spline_filter).
     *
     * scipy.ndimage.spline_filter
     */
    public static function splineFilter(mixed $input, mixed $order = 3, mixed $mode = 'mirror'): mixed
    {
        return Registry::routine('ndimage.spline_filter', [$input, $order, $mode]);
    }

    /**
     * 1-D B-spline prefilter along an axis (scipy.ndimage.spline_filter1d).
     *
     * scipy.ndimage.spline_filter1d
     */
    public static function splineFilter1d(mixed $input, mixed $order = 3, mixed $axis = -1, mixed $mode = 'mirror'): mixed
    {
        return Registry::routine('ndimage.spline_filter1d', [$input, $order, $axis, $mode]);
    }

    /**
     * Standard deviation over labeled regions (scipy.ndimage.standard_deviation).
     *
     * scipy.ndimage.standard_deviation
     */
    public static function standardDeviation(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.standard_deviation', [$input, $labels, $index]);
    }

    /**
     * Sum of array values over labeled regions; deprecated alias of sum_labels (scipy.ndimage.sum).
     *
     * scipy.ndimage.sum
     */
    public static function sum(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.sum', [$input, $labels, $index]);
    }

    /**
     * Sum of array values over labeled regions (scipy.ndimage.sum_labels).
     *
     * scipy.ndimage.sum_labels
     */
    public static function sumLabels(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.sum_labels', [$input, $labels, $index]);
    }

    /**
     * Multidimensional uniform (box) filter (scipy.ndimage.uniform_filter).
     *
     * scipy.ndimage.uniform_filter
     */
    public static function uniformFilter(mixed $input, mixed $size = 3, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.uniform_filter', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * 1-D uniform (box) filter along an axis (scipy.ndimage.uniform_filter1d).
     *
     * scipy.ndimage.uniform_filter1d
     */
    public static function uniformFilter1d(mixed $input, mixed $size, mixed $axis = -1, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.uniform_filter1d', [$input, $size, $axis, $mode, $cval, $origin]);
    }

    /**
     * Variance of array values over labeled regions (scipy.ndimage.variance).
     *
     * scipy.ndimage.variance
     */
    public static function variance(mixed $input, mixed $labels = null, mixed $index = null): mixed
    {
        return Registry::routine('ndimage.variance', [$input, $labels, $index]);
    }

    /**
     * White tophat: input minus its greyscale opening (scipy.ndimage.white_tophat).
     *
     * scipy.ndimage.white_tophat
     */
    public static function whiteTophat(mixed $input, mixed $size = null, mixed $mode = 'reflect', mixed $cval = 0.0, mixed $origin = 0): mixed
    {
        return Registry::routine('ndimage.white_tophat', [$input, $size, $mode, $cval, $origin]);
    }

    /**
     * Resample an array by a zoom factor, order 0/1 (scipy.ndimage.zoom).
     *
     * scipy.ndimage.zoom
     */
    public static function zoom(mixed $input, mixed $zoom, mixed $order = 3, mixed $mode = 'constant', mixed $cval = 0.0, mixed $prefilter = true): mixed
    {
        return Registry::routine('ndimage.zoom', [$input, $zoom, $order, $mode, $cval, $prefilter]);
    }
}
