<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * NumPy functions beyond the NDArray methods: statistics, NaN-aware reductions, quantiles, histograms, set operations, searching (numpy.*).
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\Np.
 */
final class Np
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'allclose' => 'allclose',
    'append' => 'append',
    'argpartition' => 'argpartition',
    'argwhere' => 'argwhere',
    'around' => 'around',
    'array_equal' => 'arrayEqual',
    'array_equiv' => 'arrayEquiv',
    'array_split' => 'arraySplit',
    'ascontiguousarray' => 'ascontiguousarray',
    'asfortranarray' => 'asfortranarray',
    'atleast_1d' => 'atleast1d',
    'atleast_2d' => 'atleast2d',
    'atleast_3d' => 'atleast3d',
    'average' => 'average',
    'bartlett' => 'bartlett',
    'bincount' => 'bincount',
    'bitwise_and' => 'bitwiseAnd',
    'bitwise_count' => 'bitwiseCount',
    'bitwise_or' => 'bitwiseOr',
    'bitwise_xor' => 'bitwiseXor',
    'blackman' => 'blackman',
    'broadcast_arrays' => 'broadcastArrays',
    'broadcast_shapes' => 'broadcastShapes',
    'broadcast_to' => 'broadcastTo',
    'can_cast' => 'canCast',
    'choose' => 'choose',
    'column_stack' => 'columnStack',
    'compress' => 'compress',
    'concat' => 'concat',
    'concatenate' => 'concatenate',
    'convolve' => 'convolve',
    'copyto' => 'copyto',
    'corrcoef' => 'corrcoef',
    'correlate' => 'correlate',
    'count_nonzero' => 'countNonzero',
    'cov' => 'cov',
    'cross' => 'cross',
    'cumulativeTrapezoid' => 'cumulativeTrapezoid',
    'cumulative_prod' => 'cumulativeProd',
    'cumulative_sum' => 'cumulativeSum',
    'delete' => 'delete',
    'diag' => 'diag',
    'diag_indices' => 'diagIndices',
    'diag_indices_from' => 'diagIndicesFrom',
    'diagflat' => 'diagflat',
    'diagonal' => 'diagonal',
    'diff' => 'diff',
    'digitize' => 'digitize',
    'divmod' => 'divmod',
    'dsplit' => 'dsplit',
    'dstack' => 'dstack',
    'ediff1d' => 'ediff1d',
    'einsum' => 'einsum',
    'empty_like' => 'emptyLike',
    'expand_dims' => 'expandDims',
    'extract' => 'extract',
    'fabs' => 'fabs',
    'fill_diagonal' => 'fillDiagonal',
    'finfo' => 'finfo',
    'flatnonzero' => 'flatnonzero',
    'flip' => 'flip',
    'fliplr' => 'fliplr',
    'flipud' => 'flipud',
    'frexp' => 'frexp',
    'fromfile' => 'fromfile',
    'fromiter' => 'fromiter',
    'full_like' => 'fullLike',
    'geomspace' => 'geomspace',
    'gradient' => 'gradient',
    'hamming' => 'hamming',
    'hanning' => 'hanning',
    'histogram' => 'histogram',
    'histogram_bin_edges' => 'histogramBinEdges',
    'hsplit' => 'hsplit',
    'hstack' => 'hstack',
    'i0' => 'i0',
    'identity' => 'identity',
    'iinfo' => 'iinfo',
    'indices' => 'indices',
    'inner' => 'inner',
    'insert' => 'insert',
    'interp' => 'interp',
    'intersect1d' => 'intersect1d',
    'isclose' => 'isclose',
    'iscomplex' => 'iscomplex',
    'iscomplexobj' => 'iscomplexobj',
    'isin' => 'isin',
    'isneginf' => 'isneginf',
    'isposinf' => 'isposinf',
    'isreal' => 'isreal',
    'isrealobj' => 'isrealobj',
    'ix_' => 'ix_',
    'kaiser' => 'kaiser',
    'kron' => 'kron',
    'ldexp' => 'ldexp',
    'left_shift' => 'leftShift',
    'lexsort' => 'lexsort',
    'loadtxt' => 'loadtxt',
    'logspace' => 'logspace',
    'matrix_transpose' => 'matrixTranspose',
    'matvec' => 'matvec',
    'median' => 'median',
    'meshgrid' => 'meshgrid',
    'modf' => 'modf',
    'moveaxis' => 'moveaxis',
    'nan_to_num' => 'nanToNum',
    'nanargmax' => 'nanargmax',
    'nanargmin' => 'nanargmin',
    'nancumprod' => 'nancumprod',
    'nancumsum' => 'nancumsum',
    'nanmax' => 'nanmax',
    'nanmean' => 'nanmean',
    'nanmedian' => 'nanmedian',
    'nanmin' => 'nanmin',
    'nanpercentile' => 'nanpercentile',
    'nanprod' => 'nanprod',
    'nanquantile' => 'nanquantile',
    'nanstd' => 'nanstd',
    'nansum' => 'nansum',
    'nanvar' => 'nanvar',
    'ndim' => 'ndim',
    'nonzero' => 'nonzero',
    'ones_like' => 'onesLike',
    'outer' => 'outer',
    'pad' => 'pad',
    'partition' => 'partition',
    'percentile' => 'percentile',
    'place' => 'place',
    'polyadd' => 'polyadd',
    'polyder' => 'polyder',
    'polydiv' => 'polydiv',
    'polyfit' => 'polyfit',
    'polyint' => 'polyint',
    'polymul' => 'polymul',
    'polysub' => 'polysub',
    'polyval' => 'polyval',
    'promote_types' => 'promoteTypes',
    'ptp' => 'ptp',
    'put' => 'put',
    'put_along_axis' => 'putAlongAxis',
    'putmask' => 'putmask',
    'quantile' => 'quantile',
    'ravel_multi_index' => 'ravelMultiIndex',
    'real_if_close' => 'realIfClose',
    'repeat' => 'repeat',
    'resize' => 'resize',
    'result_type' => 'resultType',
    'right_shift' => 'rightShift',
    'roll' => 'roll',
    'rollaxis' => 'rollaxis',
    'roots' => 'roots',
    'rot90' => 'rot90',
    'round' => 'round',
    'searchsorted' => 'searchsorted',
    'select' => 'select',
    'setdiff1d' => 'setdiff1d',
    'setxor1d' => 'setxor1d',
    'shape' => 'shape',
    'simpson' => 'simpson',
    'sinc' => 'sinc',
    'size' => 'size',
    'spacing' => 'spacing',
    'split' => 'split',
    'squeeze' => 'squeeze',
    'stack' => 'stack',
    'swapaxes' => 'swapaxes',
    'take' => 'take',
    'take_along_axis' => 'takeAlongAxis',
    'tensordot' => 'tensordot',
    'tile' => 'tile',
    'trace' => 'trace',
    'trapezoid' => 'trapezoid',
    'tri' => 'tri',
    'tril' => 'tril',
    'tril_indices' => 'trilIndices',
    'tril_indices_from' => 'trilIndicesFrom',
    'trim_zeros' => 'trimZeros',
    'triu' => 'triu',
    'triu_indices' => 'triuIndices',
    'triu_indices_from' => 'triuIndicesFrom',
    'union1d' => 'union1d',
    'unique' => 'unique',
    'unique_all' => 'uniqueAll',
    'unique_counts' => 'uniqueCounts',
    'unique_inverse' => 'uniqueInverse',
    'unique_values' => 'uniqueValues',
    'unravel_index' => 'unravelIndex',
    'unstack' => 'unstack',
    'unwrap' => 'unwrap',
    'vander' => 'vander',
    'vdot' => 'vdot',
    'vecdot' => 'vecdot',
    'vecmat' => 'vecmat',
    'vsplit' => 'vsplit',
    'vstack' => 'vstack',
    'zeros_like' => 'zerosLike',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: Np::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("Np::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * True when two arrays are element-wise equal within a tolerance (numpy.allclose).
     *
     * numpy.allclose
     */
    public static function allclose(mixed $a, mixed $b, mixed $rtol = 1e-05, mixed $atol = 1e-08, mixed $equalNan = false): mixed
    {
        return Registry::routine('np.allclose', [$a, $b, $rtol, $atol, $equalNan]);
    }

    /**
     * Append values to the end of an array (numpy.append).
     *
     * numpy.append
     */
    public static function append(mixed $arr, mixed $values, mixed $axis = null): mixed
    {
        return Registry::routine('np.append', [$arr, $values, $axis]);
    }

    /**
     * Indices that partition the array (numpy.argpartition).
     *
     * numpy.argpartition
     */
    public static function argpartition(mixed $a, mixed $kth, ?int $axis = -1): NDArray|float|int
    {
        return Registry::gufunc('np.argpartition', [$a, $kth], $axis, false, []);
    }

    /**
     * Indices of the non-zero elements, one row per element (numpy.argwhere).
     *
     * numpy.argwhere
     */
    public static function argwhere(mixed $a): mixed
    {
        return Registry::routine('np.argwhere', [$a]);
    }

    /**
     * Round to the given number of decimals, half to even (numpy.around; an alias of round).
     *
     * numpy.around
     */
    public static function around(mixed $a, mixed $decimals = 0): mixed
    {
        return Registry::routine('np.around', [$a, $decimals]);
    }

    /**
     * True when two arrays have the same shape and elements (numpy.array_equal).
     *
     * numpy.array_equal
     */
    public static function arrayEqual(mixed $a1, mixed $a2, mixed $equalNan = false): mixed
    {
        return Registry::routine('np.array_equal', [$a1, $a2, $equalNan]);
    }

    /**
     * True when two arrays are shape-consistent and equal (numpy.array_equiv).
     *
     * numpy.array_equiv
     */
    public static function arrayEquiv(mixed $a1, mixed $a2): mixed
    {
        return Registry::routine('np.array_equiv', [$a1, $a2]);
    }

    /**
     * Split into sections of nearly equal size (numpy.array_split).
     *
     * numpy.array_split
     */
    public static function arraySplit(mixed $ary, mixed $indicesOrSections, mixed $axis = 0): mixed
    {
        return Registry::routine('np.array_split', [$ary, $indicesOrSections, $axis]);
    }

    /**
     * A C-contiguous array (ndim >= 1) of the given dtype (numpy.ascontiguousarray).
     *
     * numpy.ascontiguousarray
     */
    public static function ascontiguousarray(mixed $a, mixed $dtype = null): mixed
    {
        return Registry::routine('np.ascontiguousarray', [$a, $dtype]);
    }

    /**
     * A contiguous array (ndim >= 1); Tessero has no Fortran memory order, so the values, shape and dtype match numpy.asfortranarray but the memory layout is C order.
     *
     * numpy.asfortranarray
     */
    public static function asfortranarray(mixed $a, mixed $dtype = null): mixed
    {
        return Registry::routine('np.asfortranarray', [$a, $dtype]);
    }

    /**
     * Arrays with at least one dimension; several arguments give a list (numpy.atleast_1d).
     *
     * numpy.atleast_1d: the positional arguments are numpy's *arys.
     */
    public static function atleast1d(mixed ...$arys): mixed
    {
        return Registry::routineVariadic('np.atleast_1d', $arys);
    }

    /**
     * Arrays with at least two dimensions; several arguments give a list (numpy.atleast_2d).
     *
     * numpy.atleast_2d: the positional arguments are numpy's *arys.
     */
    public static function atleast2d(mixed ...$arys): mixed
    {
        return Registry::routineVariadic('np.atleast_2d', $arys);
    }

    /**
     * Arrays with at least three dimensions; several arguments give a list (numpy.atleast_3d).
     *
     * numpy.atleast_3d: the positional arguments are numpy's *arys.
     */
    public static function atleast3d(mixed ...$arys): mixed
    {
        return Registry::routineVariadic('np.atleast_3d', $arys);
    }

    /**
     * Weighted average along the given axes (numpy.average).
     *
     * numpy.average
     */
    public static function average(mixed $a, mixed $weights = null, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.average', [$a, $weights], $axis, $keepdims, []);
    }

    /**
     * Bartlett (triangular) window (numpy.bartlett).
     *
     * numpy.bartlett
     */
    public static function bartlett(mixed $M): mixed
    {
        return Registry::routine('np.bartlett', [$M]);
    }

    /**
     * Count (or sum weights of) each non-negative integer (numpy.bincount).
     *
     * numpy.bincount
     */
    public static function bincount(mixed $x, mixed $weights = null, mixed $minlength = 0): mixed
    {
        return Registry::routine('np.bincount', [$x, $weights, $minlength]);
    }

    /**
     * Element-wise bitwise AND of two integer arrays (numpy.bitwise_and).
     *
     * numpy.bitwise_and
     */
    public static function bitwiseAnd(mixed $x1, mixed $x2): mixed
    {
        return Registry::routine('np.bitwise_and', [$x1, $x2]);
    }

    /**
     * The number of 1-bits in the absolute value of each integer element, as uint8 (numpy.bitwise_count).
     *
     * numpy.bitwise_count
     */
    public static function bitwiseCount(mixed $x): mixed
    {
        return Registry::routine('np.bitwise_count', [$x]);
    }

    /**
     * Element-wise bitwise OR of two integer arrays (numpy.bitwise_or).
     *
     * numpy.bitwise_or
     */
    public static function bitwiseOr(mixed $x1, mixed $x2): mixed
    {
        return Registry::routine('np.bitwise_or', [$x1, $x2]);
    }

    /**
     * Element-wise bitwise XOR of two integer arrays (numpy.bitwise_xor).
     *
     * numpy.bitwise_xor
     */
    public static function bitwiseXor(mixed $x1, mixed $x2): mixed
    {
        return Registry::routine('np.bitwise_xor', [$x1, $x2]);
    }

    /**
     * Blackman window (numpy.blackman).
     *
     * numpy.blackman
     */
    public static function blackman(mixed $M): mixed
    {
        return Registry::routine('np.blackman', [$M]);
    }

    /**
     * Broadcast arrays against each other (numpy.broadcast_arrays).
     *
     * numpy.broadcast_arrays: the positional arguments are numpy's *args.
     */
    public static function broadcastArrays(mixed ...$args): mixed
    {
        return Registry::routineVariadic('np.broadcast_arrays', $args);
    }

    /**
     * The broadcast shape of the given shapes (numpy.broadcast_shapes).
     *
     * numpy.broadcast_shapes: the positional arguments are numpy's *args.
     */
    public static function broadcastShapes(mixed ...$args): mixed
    {
        return Registry::routineVariadic('np.broadcast_shapes', $args);
    }

    /**
     * Broadcast an array to a shape (numpy.broadcast_to).
     *
     * numpy.broadcast_to
     */
    public static function broadcastTo(mixed $array, mixed $shape): mixed
    {
        return Registry::routine('np.broadcast_to', [$array, $shape]);
    }

    /**
     * Whether a cast between two dtypes is allowed under a casting rule (numpy.can_cast).
     *
     * numpy.can_cast
     */
    public static function canCast(mixed $from_, mixed $to, mixed $casting = 'safe'): mixed
    {
        return Registry::routine('np.can_cast', [$from_, $to, $casting]);
    }

    /**
     * Build an array from an index array and a list of choices (numpy.choose).
     *
     * numpy.choose
     */
    public static function choose(mixed $a, mixed $choices, mixed $mode = 'raise'): mixed
    {
        return Registry::routine('np.choose', [$a, $choices, $mode]);
    }

    /**
     * Stack 1-D arrays as columns of a 2-D array (numpy.column_stack).
     *
     * numpy.column_stack
     */
    public static function columnStack(mixed $tup): mixed
    {
        return Registry::routine('np.column_stack', [$tup]);
    }

    /**
     * Selected slices along an axis (numpy.compress).
     *
     * numpy.compress
     */
    public static function compress(mixed $condition, mixed $a, mixed $axis = null): mixed
    {
        return Registry::routine('np.compress', [$condition, $a, $axis]);
    }

    /**
     * Join arrays along an existing axis (numpy.concat, the Array API name of concatenate).
     *
     * numpy.concat
     */
    public static function concat(mixed $arrays, mixed $axis = 0, mixed $dtype = null, mixed $casting = 'same_kind'): mixed
    {
        return Registry::routine('np.concat', [$arrays, $axis, $dtype, $casting]);
    }

    /**
     * Join arrays along an existing axis; axis=None flattens them first (numpy.concatenate).
     *
     * numpy.concatenate
     */
    public static function concatenate(mixed $arrays, mixed $axis = 0, mixed $dtype = null, mixed $casting = 'same_kind'): mixed
    {
        return Registry::routine('np.concatenate', [$arrays, $axis, $dtype, $casting]);
    }

    /**
     * Discrete linear convolution of two 1-D sequences (numpy.convolve).
     *
     * numpy.convolve
     */
    public static function convolve(mixed $a, mixed $v, mixed $mode = 'full'): mixed
    {
        return Registry::routine('np.convolve', [$a, $v, $mode]);
    }

    /**
     * Copy values into an array, broadcasting, in place (numpy.copyto).
     *
     * numpy.copyto
     */
    public static function copyto(mixed $dst, mixed $src, mixed $casting = 'same_kind', mixed $where = null): mixed
    {
        return Registry::routine('np.copyto', [$dst, $src, $casting, $where]);
    }

    /**
     * Pearson correlation coefficients (numpy.corrcoef).
     *
     * numpy.corrcoef
     */
    public static function corrcoef(mixed $x, mixed $y = null, mixed $rowvar = true): mixed
    {
        return Registry::routine('np.corrcoef', [$x, $y, $rowvar]);
    }

    /**
     * Cross-correlation of two 1-D sequences (numpy.correlate).
     *
     * numpy.correlate
     */
    public static function correlate(mixed $a, mixed $v, mixed $mode = 'valid'): mixed
    {
        return Registry::routine('np.correlate', [$a, $v, $mode]);
    }

    /**
     * Number of non-zero values (numpy.count_nonzero).
     *
     * numpy.count_nonzero
     */
    public static function countNonzero(mixed $a, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.count_nonzero', [$a], $axis, $keepdims, []);
    }

    /**
     * Covariance matrix (numpy.cov).
     *
     * numpy.cov
     */
    public static function cov(mixed $m, mixed $y = null, mixed $rowvar = true, mixed $bias = false, mixed $ddof = null, mixed $fweights = null, mixed $aweights = null): mixed
    {
        return Registry::routine('np.cov', [$m, $y, $rowvar, $bias, $ddof, $fweights, $aweights]);
    }

    /**
     * Cross product of 3- (or 2-) element vectors (numpy.cross).
     *
     * numpy.cross
     */
    public static function cross(mixed $a, mixed $b, mixed $axisa = -1, mixed $axisb = -1, mixed $axisc = -1, mixed $axis = null): mixed
    {
        return Registry::routine('np.cross', [$a, $b, $axisa, $axisb, $axisc, $axis]);
    }

    /**
     * Running integral by the trapezoidal rule (scipy.integrate.cumulative_trapezoid).
     *
     * numpy.cumulativeTrapezoid
     */
    public static function cumulativeTrapezoid(mixed $y, mixed $x = null, mixed $dx = 1.0, mixed $axis = -1, mixed $initial = null): mixed
    {
        return Registry::routine('np.cumulativeTrapezoid', [$y, $x, $dx, $axis, $initial]);
    }

    /**
     * Cumulative product, optionally starting with 1 (numpy.cumulative_prod).
     *
     * numpy.cumulative_prod
     */
    public static function cumulativeProd(mixed $x, ?int $axis = null, int|float|bool|null $includeInitial = false): NDArray|float|int
    {
        return Registry::gufunc('np.cumulative_prod', [$x], $axis, false, ['include_initial' => $includeInitial]);
    }

    /**
     * Cumulative sum, optionally starting with 0 (numpy.cumulative_sum).
     *
     * numpy.cumulative_sum
     */
    public static function cumulativeSum(mixed $x, ?int $axis = null, int|float|bool|null $includeInitial = false): NDArray|float|int
    {
        return Registry::gufunc('np.cumulative_sum', [$x], $axis, false, ['include_initial' => $includeInitial]);
    }

    /**
     * Remove the given indices along an axis (numpy.delete).
     *
     * numpy.delete
     */
    public static function delete(mixed $arr, mixed $obj, mixed $axis = null): mixed
    {
        return Registry::routine('np.delete', [$arr, $obj, $axis]);
    }

    /**
     * Extract a diagonal, or build a 2-D array with the given diagonal (numpy.diag).
     *
     * numpy.diag
     */
    public static function diag(mixed $v, mixed $k = 0): mixed
    {
        return Registry::routine('np.diag', [$v, $k]);
    }

    /**
     * Indices of the main diagonal of an n x ... x n array (numpy.diag_indices).
     *
     * numpy.diag_indices
     */
    public static function diagIndices(mixed $n, mixed $ndim = 2): mixed
    {
        return Registry::routine('np.diag_indices', [$n, $ndim]);
    }

    /**
     * Indices of the main diagonal of an array (numpy.diag_indices_from).
     *
     * numpy.diag_indices_from
     */
    public static function diagIndicesFrom(mixed $arr): mixed
    {
        return Registry::routine('np.diag_indices_from', [$arr]);
    }

    /**
     * A 2-D array with the flattened input as a diagonal (numpy.diagflat).
     *
     * numpy.diagflat
     */
    public static function diagflat(mixed $v, mixed $k = 0): mixed
    {
        return Registry::routine('np.diagflat', [$v, $k]);
    }

    /**
     * The given diagonal of an array (numpy.diagonal).
     *
     * numpy.diagonal
     */
    public static function diagonal(mixed $a, mixed $offset = 0, mixed $axis1 = 0, mixed $axis2 = 1): mixed
    {
        return Registry::routine('np.diagonal', [$a, $offset, $axis1, $axis2]);
    }

    /**
     * n-th discrete difference along an axis (numpy.diff).
     *
     * numpy.diff
     */
    public static function diff(mixed $a, mixed $n = 1, mixed $axis = -1, mixed $prepend = null, mixed $append = null): mixed
    {
        return Registry::routine('np.diff', [$a, $n, $axis, $prepend, $append]);
    }

    /**
     * Indices of the bins to which each value belongs (numpy.digitize).
     *
     * numpy.digitize
     */
    public static function digitize(mixed $x, mixed $bins, int|float|bool|null $right = false): NDArray|float|int
    {
        return Registry::gufunc('np.digitize', [$x, $bins], null, false, ['right' => $right]);
    }

    /**
     * The element-wise floor-division quotient and remainder as a pair (numpy.divmod).
     *
     * numpy.divmod
     */
    public static function divmod(mixed $x1, mixed $x2): mixed
    {
        return Registry::routine('np.divmod', [$x1, $x2]);
    }

    /**
     * Split along the third axis (numpy.dsplit).
     *
     * numpy.dsplit
     */
    public static function dsplit(mixed $ary, mixed $indicesOrSections): mixed
    {
        return Registry::routine('np.dsplit', [$ary, $indicesOrSections]);
    }

    /**
     * Stack arrays depth-wise, along the third axis (numpy.dstack).
     *
     * numpy.dstack
     */
    public static function dstack(mixed $tup): mixed
    {
        return Registry::routine('np.dstack', [$tup]);
    }

    /**
     * Differences between consecutive elements of the flattened array (numpy.ediff1d).
     *
     * numpy.ediff1d
     */
    public static function ediff1d(mixed $ary, mixed $toEnd = null, mixed $toBegin = null): mixed
    {
        return Registry::routine('np.ediff1d', [$ary, $toEnd, $toBegin]);
    }

    /**
     * Einstein summation over the operands (numpy.einsum); real float64 operands.
     *
     * numpy.einsum: the positional arguments are numpy's *operands.
     *
     * Named options: $subscripts.
     */
    public static function einsum(mixed ...$operands): mixed
    {
        return Registry::routineVariadic('np.einsum', $operands);
    }

    /**
     * An array with the shape and dtype of another; Tessero fills it with zeros (numpy.empty_like).
     *
     * numpy.empty_like
     */
    public static function emptyLike(mixed $a, mixed $dtype = null, mixed $shape = null): mixed
    {
        return Registry::routine('np.empty_like', [$a, $dtype, $shape]);
    }

    /**
     * Insert length-1 axes (numpy.expand_dims).
     *
     * numpy.expand_dims
     */
    public static function expandDims(mixed $a, mixed $axis): mixed
    {
        return Registry::routine('np.expand_dims', [$a, $axis]);
    }

    /**
     * Elements where the condition holds, flattened (numpy.extract).
     *
     * numpy.extract
     */
    public static function extract(mixed $condition, mixed $arr): mixed
    {
        return Registry::routine('np.extract', [$condition, $arr]);
    }

    /**
     * Element-wise absolute value as float64 (numpy.fabs).
     *
     * numpy.fabs
     */
    public static function fabs(mixed $x): mixed
    {
        return Registry::routine('np.fabs', [$x]);
    }

    /**
     * Fill the main diagonal, in place (numpy.fill_diagonal).
     *
     * numpy.fill_diagonal
     */
    public static function fillDiagonal(mixed $a, mixed $val, mixed $wrap = false): mixed
    {
        return Registry::routine('np.fill_diagonal', [$a, $val, $wrap]);
    }

    /**
     * The machine limits of a floating-point dtype as a dict of the common fields (numpy.finfo).
     *
     * numpy.finfo
     *
     * @return mixed one array, or an array keyed by eps, epsneg, max, min, tiny, smallest_normal, resolution, precision, bits, nmant, nexp, maxexp, minexp when several results are requested
     */
    public static function finfo(mixed $dtype): mixed
    {
        return Registry::routine('np.finfo', [$dtype]);
    }

    /**
     * Indices of the non-zero elements of the flattened array (numpy.flatnonzero).
     *
     * numpy.flatnonzero
     */
    public static function flatnonzero(mixed $a): mixed
    {
        return Registry::routine('np.flatnonzero', [$a]);
    }

    /**
     * Reverse the order of elements along the given axes (numpy.flip).
     *
     * numpy.flip
     */
    public static function flip(mixed $m, mixed $axis = null): mixed
    {
        return Registry::routine('np.flip', [$m, $axis]);
    }

    /**
     * Reverse the order along axis 1 (numpy.fliplr).
     *
     * numpy.fliplr
     */
    public static function fliplr(mixed $m): mixed
    {
        return Registry::routine('np.fliplr', [$m]);
    }

    /**
     * Reverse the order along axis 0 (numpy.flipud).
     *
     * numpy.flipud
     */
    public static function flipud(mixed $m): mixed
    {
        return Registry::routine('np.flipud', [$m]);
    }

    /**
     * The normalised mantissa and integer exponent of each element as a (mantissa, exponent) pair (numpy.frexp).
     *
     * numpy.frexp
     */
    public static function frexp(mixed $x): mixed
    {
        return Registry::routine('np.frexp', [$x]);
    }

    /**
     * Read a binary or text file into a 1-D array of the given dtype (numpy.fromfile).
     *
     * numpy.fromfile
     */
    public static function fromfile(mixed $fname, mixed $dtype = null, mixed $count = -1, mixed $sep = null, mixed $offset = 0): mixed
    {
        return Registry::routine('np.fromfile', [$fname, $dtype, $count, $sep, $offset]);
    }

    /**
     * A 1-D array built from the first count elements of an iterable, cast to dtype (numpy.fromiter).
     *
     * numpy.fromiter
     */
    public static function fromiter(mixed $iterable, mixed $dtype, mixed $count = -1): mixed
    {
        return Registry::routine('np.fromiter', [$iterable, $dtype, $count]);
    }

    /**
     * An array of fill_value with the shape and dtype of another (numpy.full_like).
     *
     * numpy.full_like
     */
    public static function fullLike(mixed $a, mixed $fillValue, mixed $dtype = null, mixed $shape = null): mixed
    {
        return Registry::routine('np.full_like', [$a, $fillValue, $dtype, $shape]);
    }

    /**
     * Numbers spaced evenly on a log scale, a geometric progression (numpy.geomspace).
     *
     * numpy.geomspace
     */
    public static function geomspace(mixed $start, mixed $stop, mixed $num = 50, mixed $endpoint = true, mixed $dtype = null, mixed $axis = 0): mixed
    {
        return Registry::routine('np.geomspace', [$start, $stop, $num, $endpoint, $dtype, $axis]);
    }

    /**
     * Gradient by central differences, one-sided at the edges (numpy.gradient); several axes give a list.
     *
     * numpy.gradient: the positional arguments are numpy's *varargs.
     *
     * Named options: $f, $axis = null, $edgeOrder = 1.
     */
    public static function gradient(mixed ...$varargs): mixed
    {
        return Registry::routineVariadic('np.gradient', $varargs);
    }

    /**
     * Hamming window (numpy.hamming).
     *
     * numpy.hamming
     */
    public static function hamming(mixed $M): mixed
    {
        return Registry::routine('np.hamming', [$M]);
    }

    /**
     * Hanning window (numpy.hanning).
     *
     * numpy.hanning
     */
    public static function hanning(mixed $M): mixed
    {
        return Registry::routine('np.hanning', [$M]);
    }

    /**
     * Histogram of the data: counts (or density) and bin edges (numpy.histogram).
     *
     * numpy.histogram
     *
     * @return mixed one array, or an array keyed by hist, bin_edges when several results are requested
     */
    public static function histogram(mixed $a, mixed $bins = 10, mixed $range = null, mixed $density = false, mixed $weights = null): mixed
    {
        return Registry::routine('np.histogram', [$a, $bins, $range, $density, $weights]);
    }

    /**
     * Bin edges numpy.histogram would use (numpy.histogram_bin_edges).
     *
     * numpy.histogram_bin_edges
     */
    public static function histogramBinEdges(mixed $a, mixed $bins = 10, mixed $range = null, mixed $weights = null): mixed
    {
        return Registry::routine('np.histogram_bin_edges', [$a, $bins, $range, $weights]);
    }

    /**
     * Split horizontally, column-wise (numpy.hsplit).
     *
     * numpy.hsplit
     */
    public static function hsplit(mixed $ary, mixed $indicesOrSections): mixed
    {
        return Registry::routine('np.hsplit', [$ary, $indicesOrSections]);
    }

    /**
     * Stack arrays horizontally, column-wise (numpy.hstack).
     *
     * numpy.hstack
     */
    public static function hstack(mixed $tup, mixed $dtype = null, mixed $casting = 'same_kind'): mixed
    {
        return Registry::routine('np.hstack', [$tup, $dtype, $casting]);
    }

    /**
     * Modified Bessel function of the first kind, order 0 (numpy.i0).
     *
     * numpy.i0
     */
    public static function i0(mixed $x): mixed
    {
        return Registry::routine('np.i0', [$x]);
    }

    /**
     * The identity matrix (numpy.identity).
     *
     * numpy.identity
     */
    public static function identity(mixed $n, mixed $dtype = null): mixed
    {
        return Registry::routine('np.identity', [$n, $dtype]);
    }

    /**
     * The limits of an integer dtype as a dict (min, max, bits) (numpy.iinfo).
     *
     * numpy.iinfo
     *
     * @return mixed one array, or an array keyed by min, max, bits when several results are requested
     */
    public static function iinfo(mixed $dtype): mixed
    {
        return Registry::routine('np.iinfo', [$dtype]);
    }

    /**
     * An array of grid indices (numpy.indices); sparse=True gives a list of arrays.
     *
     * numpy.indices
     */
    public static function indices(mixed $dimensions, mixed $dtype = 'int64', mixed $sparse = false): mixed
    {
        return Registry::routine('np.indices', [$dimensions, $dtype, $sparse]);
    }

    /**
     * Inner product over the last axes (numpy.inner).
     *
     * numpy.inner
     */
    public static function inner(mixed $a, mixed $b): mixed
    {
        return Registry::routine('np.inner', [$a, $b]);
    }

    /**
     * Insert values before the given indices (numpy.insert).
     *
     * numpy.insert
     */
    public static function insert(mixed $arr, mixed $obj, mixed $values, mixed $axis = null): mixed
    {
        return Registry::routine('np.insert', [$arr, $obj, $values, $axis]);
    }

    /**
     * One-dimensional piecewise linear interpolation (numpy.interp).
     *
     * numpy.interp
     */
    public static function interp(mixed $x, mixed $xp, mixed $fp, mixed $left = null, mixed $right = null, mixed $period = null): mixed
    {
        return Registry::routine('np.interp', [$x, $xp, $fp, $left, $right, $period]);
    }

    /**
     * Sorted unique values in both arrays (numpy.intersect1d).
     *
     * numpy.intersect1d
     *
     * @return mixed one array, or an array keyed by intersect1d, comm1, comm2 when several results are requested
     */
    public static function intersect1d(mixed $ar1, mixed $ar2, mixed $assumeUnique = false, mixed $returnIndices = false): mixed
    {
        return Registry::routine('np.intersect1d', [$ar1, $ar2, $assumeUnique, $returnIndices]);
    }

    /**
     * Element-wise test for approximate equality within a tolerance (numpy.isclose).
     *
     * numpy.isclose
     */
    public static function isclose(mixed $a, mixed $b, mixed $rtol = 1e-05, mixed $atol = 1e-08, mixed $equalNan = false): mixed
    {
        return Registry::routine('np.isclose', [$a, $b, $rtol, $atol, $equalNan]);
    }

    /**
     * Element-wise test for a non-zero imaginary part (numpy.iscomplex).
     *
     * numpy.iscomplex
     */
    public static function iscomplex(mixed $x): mixed
    {
        return Registry::routine('np.iscomplex', [$x]);
    }

    /**
     * True for a complex dtype (numpy.iscomplexobj).
     *
     * numpy.iscomplexobj
     */
    public static function iscomplexobj(mixed $x): mixed
    {
        return Registry::routine('np.iscomplexobj', [$x]);
    }

    /**
     * Whether each element is in test_elements (numpy.isin).
     *
     * numpy.isin
     */
    public static function isin(mixed $element, mixed $testElements, int|float|bool|null $invert = false): NDArray|float|int|bool
    {
        return Registry::gufunc('np.isin', [$element, $testElements], null, false, ['invert' => $invert]);
    }

    /**
     * Element-wise test for negative infinity (numpy.isneginf).
     *
     * numpy.isneginf
     */
    public static function isneginf(mixed $x): mixed
    {
        return Registry::routine('np.isneginf', [$x]);
    }

    /**
     * Element-wise test for positive infinity (numpy.isposinf).
     *
     * numpy.isposinf
     */
    public static function isposinf(mixed $x): mixed
    {
        return Registry::routine('np.isposinf', [$x]);
    }

    /**
     * Element-wise test for a zero imaginary part (numpy.isreal).
     *
     * numpy.isreal
     */
    public static function isreal(mixed $x): mixed
    {
        return Registry::routine('np.isreal', [$x]);
    }

    /**
     * True for a non-complex dtype (numpy.isrealobj).
     *
     * numpy.isrealobj
     */
    public static function isrealobj(mixed $x): mixed
    {
        return Registry::routine('np.isrealobj', [$x]);
    }

    /**
     * An open mesh from several sequences (numpy.ix_).
     *
     * numpy.ix_: the positional arguments are numpy's *args.
     */
    public static function ix_(mixed ...$args): mixed
    {
        return Registry::routineVariadic('np.ix_', $args);
    }

    /**
     * Kaiser window (numpy.kaiser).
     *
     * numpy.kaiser
     */
    public static function kaiser(mixed $M, mixed $beta): mixed
    {
        return Registry::routine('np.kaiser', [$M, $beta]);
    }

    /**
     * Kronecker product (numpy.kron).
     *
     * numpy.kron
     */
    public static function kron(mixed $a, mixed $b): mixed
    {
        return Registry::routine('np.kron', [$a, $b]);
    }

    /**
     * x1 * 2**x2 element-wise, with an integer exponent (numpy.ldexp).
     *
     * numpy.ldexp
     */
    public static function ldexp(mixed $x1, mixed $x2): mixed
    {
        return Registry::routine('np.ldexp', [$x1, $x2]);
    }

    /**
     * Shift the bits of each integer left by the per-element count (numpy.left_shift).
     *
     * numpy.left_shift
     */
    public static function leftShift(mixed $x1, mixed $x2): mixed
    {
        return Registry::routine('np.left_shift', [$x1, $x2]);
    }

    /**
     * Indirect stable sort on several keys, the last key primary (numpy.lexsort).
     *
     * numpy.lexsort
     */
    public static function lexsort(mixed $keys): mixed
    {
        return Registry::routine('np.lexsort', [$keys]);
    }

    /**
     * Load a text file of numbers into a float64 array (numpy.loadtxt).
     *
     * numpy.loadtxt
     */
    public static function loadtxt(mixed $fname, mixed $delimiter = null, mixed $skiprows = 0, mixed $comments = null, mixed $usecols = null): mixed
    {
        return Registry::routine('np.loadtxt', [$fname, $delimiter, $skiprows, $comments, $usecols]);
    }

    /**
     * Numbers spaced evenly on a log scale (numpy.logspace).
     *
     * numpy.logspace
     */
    public static function logspace(mixed $start, mixed $stop, mixed $num = 50, mixed $endpoint = true, mixed $base = 10.0, mixed $dtype = null, mixed $axis = 0): mixed
    {
        return Registry::routine('np.logspace', [$start, $stop, $num, $endpoint, $base, $dtype, $axis]);
    }

    /**
     * Transpose the last two axes (numpy.matrix_transpose).
     *
     * numpy.matrix_transpose
     */
    public static function matrixTranspose(mixed $x): mixed
    {
        return Registry::routine('np.matrix_transpose', [$x]);
    }

    /**
     * Matrix-vector product over the last two axes of x1 and the last axis of x2 (numpy.matvec).
     *
     * numpy.matvec
     */
    public static function matvec(mixed $x1, mixed $x2): mixed
    {
        return Registry::routine('np.matvec', [$x1, $x2]);
    }

    /**
     * Median along the given axes (numpy.median).
     *
     * numpy.median
     */
    public static function median(mixed $a, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.median', [$a], $axis, $keepdims, []);
    }

    /**
     * Coordinate matrices from coordinate vectors (numpy.meshgrid).
     *
     * numpy.meshgrid: the positional arguments are numpy's *xi.
     *
     * Named options: $copy = true, $sparse = false, $indexing = 'xy'.
     */
    public static function meshgrid(mixed ...$xi): mixed
    {
        return Registry::routineVariadic('np.meshgrid', $xi);
    }

    /**
     * The fractional and integral parts of each element as a (frac, intpart) pair, both carrying the sign of x (numpy.modf).
     *
     * numpy.modf
     */
    public static function modf(mixed $x): mixed
    {
        return Registry::routine('np.modf', [$x]);
    }

    /**
     * Move axes to new positions (numpy.moveaxis).
     *
     * numpy.moveaxis
     */
    public static function moveaxis(mixed $a, mixed $source, mixed $destination): mixed
    {
        return Registry::routine('np.moveaxis', [$a, $source, $destination]);
    }

    /**
     * Replace NaN and infinities by finite numbers (numpy.nan_to_num).
     *
     * numpy.nan_to_num
     */
    public static function nanToNum(mixed $x, mixed $copy = true, mixed $nan = 0.0, mixed $posinf = null, mixed $neginf = null): mixed
    {
        return Registry::routine('np.nan_to_num', [$x, $copy, $nan, $posinf, $neginf]);
    }

    /**
     * Index of the maximum ignoring NaN (numpy.nanargmax).
     *
     * numpy.nanargmax
     */
    public static function nanargmax(mixed $a, ?int $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nanargmax', [$a], $axis, $keepdims, []);
    }

    /**
     * Index of the minimum ignoring NaN (numpy.nanargmin).
     *
     * numpy.nanargmin
     */
    public static function nanargmin(mixed $a, ?int $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nanargmin', [$a], $axis, $keepdims, []);
    }

    /**
     * Cumulative product treating NaN as one (numpy.nancumprod).
     *
     * numpy.nancumprod
     */
    public static function nancumprod(mixed $a, ?int $axis = null): NDArray|float|int
    {
        return Registry::gufunc('np.nancumprod', [$a], $axis, false, []);
    }

    /**
     * Cumulative sum treating NaN as zero (numpy.nancumsum).
     *
     * numpy.nancumsum
     */
    public static function nancumsum(mixed $a, ?int $axis = null): NDArray|float|int
    {
        return Registry::gufunc('np.nancumsum', [$a], $axis, false, []);
    }

    /**
     * Maximum ignoring NaN; NaN for an all-NaN slice (numpy.nanmax).
     *
     * numpy.nanmax
     */
    public static function nanmax(mixed $a, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nanmax', [$a], $axis, $keepdims, []);
    }

    /**
     * Mean ignoring NaN (numpy.nanmean).
     *
     * numpy.nanmean
     */
    public static function nanmean(mixed $a, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nanmean', [$a], $axis, $keepdims, []);
    }

    /**
     * Median ignoring NaNs (numpy.nanmedian).
     *
     * numpy.nanmedian
     */
    public static function nanmedian(mixed $a, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nanmedian', [$a], $axis, $keepdims, []);
    }

    /**
     * Minimum ignoring NaN; NaN for an all-NaN slice (numpy.nanmin).
     *
     * numpy.nanmin
     */
    public static function nanmin(mixed $a, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nanmin', [$a], $axis, $keepdims, []);
    }

    /**
     * Percentiles ignoring NaNs (numpy.nanpercentile).
     *
     * numpy.nanpercentile
     */
    public static function nanpercentile(mixed $a, mixed $q, int|array|null $axis = null, string $method = 'linear', bool $keepdims = false): NDArray|float|int|bool
    {
        return Registry::gufunc('np.nanpercentile', [$a, $q], $axis, $keepdims, ['method' => $method]);
    }

    /**
     * Product treating NaN as one (numpy.nanprod).
     *
     * numpy.nanprod
     */
    public static function nanprod(mixed $a, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nanprod', [$a], $axis, $keepdims, []);
    }

    /**
     * Quantiles ignoring NaNs (numpy.nanquantile).
     *
     * numpy.nanquantile
     */
    public static function nanquantile(mixed $a, mixed $q, int|array|null $axis = null, string $method = 'linear', bool $keepdims = false): NDArray|float|int|bool
    {
        return Registry::gufunc('np.nanquantile', [$a, $q], $axis, $keepdims, ['method' => $method]);
    }

    /**
     * Standard deviation ignoring NaN (numpy.nanstd).
     *
     * numpy.nanstd
     */
    public static function nanstd(mixed $a, int|array|null $axis = null, int|float|bool|null $ddof = 0, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nanstd', [$a], $axis, $keepdims, ['ddof' => $ddof]);
    }

    /**
     * Sum treating NaN as zero (numpy.nansum).
     *
     * numpy.nansum
     */
    public static function nansum(mixed $a, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nansum', [$a], $axis, $keepdims, []);
    }

    /**
     * Variance ignoring NaN (numpy.nanvar).
     *
     * numpy.nanvar
     */
    public static function nanvar(mixed $a, int|array|null $axis = null, int|float|bool|null $ddof = 0, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.nanvar', [$a], $axis, $keepdims, ['ddof' => $ddof]);
    }

    /**
     * Number of dimensions (numpy.ndim).
     *
     * numpy.ndim
     */
    public static function ndim(mixed $a): mixed
    {
        return Registry::routine('np.ndim', [$a]);
    }

    /**
     * Indices of the non-zero elements, one array per axis (numpy.nonzero).
     *
     * numpy.nonzero
     */
    public static function nonzero(mixed $a): mixed
    {
        return Registry::routine('np.nonzero', [$a]);
    }

    /**
     * Ones with the shape and dtype of an array (numpy.ones_like).
     *
     * numpy.ones_like
     */
    public static function onesLike(mixed $a, mixed $dtype = null, mixed $shape = null): mixed
    {
        return Registry::routine('np.ones_like', [$a, $dtype, $shape]);
    }

    /**
     * Outer product of two vectors (numpy.outer).
     *
     * numpy.outer
     */
    public static function outer(mixed $a, mixed $b): mixed
    {
        return Registry::routine('np.outer', [$a, $b]);
    }

    /**
     * Pad an array (numpy.pad): constant, edge, linear_ramp, maximum, mean, median, minimum, reflect, symmetric, wrap, empty.
     *
     * numpy.pad
     */
    public static function pad(mixed $array, mixed $padWidth, mixed $mode = 'constant', mixed $constantValues = null, mixed $endValues = null, mixed $statLength = null, mixed $reflectType = null): mixed
    {
        return Registry::routine('np.pad', [$array, $padWidth, $mode, $constantValues, $endValues, $statLength, $reflectType]);
    }

    /**
     * Partially sorted copy: the kth element in its sorted place (numpy.partition).
     *
     * numpy.partition
     */
    public static function partition(mixed $a, mixed $kth, ?int $axis = -1): NDArray|float|int
    {
        return Registry::gufunc('np.partition', [$a, $kth], $axis, false, []);
    }

    /**
     * q-th percentiles along the given axes, q in [0, 100] (numpy.percentile).
     *
     * numpy.percentile
     */
    public static function percentile(mixed $a, mixed $q, int|array|null $axis = null, string $method = 'linear', bool $keepdims = false): NDArray|float|int|bool
    {
        return Registry::gufunc('np.percentile', [$a, $q], $axis, $keepdims, ['method' => $method]);
    }

    /**
     * Write successive values where the mask holds, in place (numpy.place).
     *
     * numpy.place
     */
    public static function place(mixed $arr, mixed $mask, mixed $vals): mixed
    {
        return Registry::routine('np.place', [$arr, $mask, $vals]);
    }

    /**
     * Sum of two polynomials (numpy.polyadd).
     *
     * numpy.polyadd
     */
    public static function polyadd(mixed $a1, mixed $a2): mixed
    {
        return Registry::routine('np.polyadd', [$a1, $a2]);
    }

    /**
     * Derivative of a polynomial (numpy.polyder).
     *
     * numpy.polyder
     */
    public static function polyder(mixed $p, mixed $m = 1): mixed
    {
        return Registry::routine('np.polyder', [$p, $m]);
    }

    /**
     * Quotient and remainder of polynomial division (numpy.polydiv).
     *
     * numpy.polydiv
     */
    public static function polydiv(mixed $u, mixed $v): mixed
    {
        return Registry::routine('np.polydiv', [$u, $v]);
    }

    /**
     * Least-squares polynomial fit, highest-degree coefficient first (numpy.polyfit).
     *
     * numpy.polyfit
     */
    public static function polyfit(mixed $x, mixed $y, mixed $deg): mixed
    {
        return Registry::routine('np.polyfit', [$x, $y, $deg]);
    }

    /**
     * Antiderivative of a polynomial (numpy.polyint).
     *
     * numpy.polyint
     */
    public static function polyint(mixed $p, mixed $m = 1, mixed $k = null): mixed
    {
        return Registry::routine('np.polyint', [$p, $m, $k]);
    }

    /**
     * Product of two polynomials (numpy.polymul).
     *
     * numpy.polymul
     */
    public static function polymul(mixed $a1, mixed $a2): mixed
    {
        return Registry::routine('np.polymul', [$a1, $a2]);
    }

    /**
     * Difference of two polynomials (numpy.polysub).
     *
     * numpy.polysub
     */
    public static function polysub(mixed $a1, mixed $a2): mixed
    {
        return Registry::routine('np.polysub', [$a1, $a2]);
    }

    /**
     * Evaluate a polynomial at x (numpy.polyval).
     *
     * numpy.polyval
     */
    public static function polyval(mixed $p, mixed $x): mixed
    {
        return Registry::routine('np.polyval', [$p, $x]);
    }

    /**
     * The smallest dtype both arguments can be safely cast to (numpy.promote_types).
     *
     * numpy.promote_types
     */
    public static function promoteTypes(mixed $type1, mixed $type2): mixed
    {
        return Registry::routine('np.promote_types', [$type1, $type2]);
    }

    /**
     * Range of values, maximum - minimum (numpy.ptp).
     *
     * numpy.ptp
     */
    public static function ptp(mixed $a, int|array|null $axis = null, bool $keepdims = false): NDArray|float|int
    {
        return Registry::gufunc('np.ptp', [$a], $axis, $keepdims, []);
    }

    /**
     * Write values at flat indices, in place (numpy.put).
     *
     * numpy.put
     */
    public static function put(mixed $a, mixed $ind, mixed $v, mixed $mode = 'raise'): mixed
    {
        return Registry::routine('np.put', [$a, $ind, $v, $mode]);
    }

    /**
     * Write values at matching 1-D index slices, in place (numpy.put_along_axis).
     *
     * numpy.put_along_axis
     */
    public static function putAlongAxis(mixed $arr, mixed $indices, mixed $values, mixed $axis): mixed
    {
        return Registry::routine('np.put_along_axis', [$arr, $indices, $values, $axis]);
    }

    /**
     * Write values where the mask holds, in place (numpy.putmask).
     *
     * numpy.putmask
     */
    public static function putmask(mixed $a, mixed $mask, mixed $values): mixed
    {
        return Registry::routine('np.putmask', [$a, $mask, $values]);
    }

    /**
     * q-th quantiles along the given axes, q in [0, 1] (numpy.quantile).
     *
     * numpy.quantile
     */
    public static function quantile(mixed $a, mixed $q, int|array|null $axis = null, string $method = 'linear', bool $keepdims = false): NDArray|float|int|bool
    {
        return Registry::gufunc('np.quantile', [$a, $q], $axis, $keepdims, ['method' => $method]);
    }

    /**
     * Convert coordinate arrays into flat indices (numpy.ravel_multi_index).
     *
     * numpy.ravel_multi_index
     */
    public static function ravelMultiIndex(mixed $multiIndex, mixed $dims, mixed $mode = 'raise', mixed $order = 'C'): mixed
    {
        return Registry::routine('np.ravel_multi_index', [$multiIndex, $dims, $mode, $order]);
    }

    /**
     * The real part when every imaginary part is close to zero (numpy.real_if_close).
     *
     * numpy.real_if_close
     */
    public static function realIfClose(mixed $a, mixed $tol = 100): mixed
    {
        return Registry::routine('np.real_if_close', [$a, $tol]);
    }

    /**
     * Repeat each element (numpy.repeat).
     *
     * numpy.repeat
     */
    public static function repeat(mixed $a, mixed $repeats, mixed $axis = null): mixed
    {
        return Registry::routine('np.repeat', [$a, $repeats, $axis]);
    }

    /**
     * A new array of the given shape, repeating the data cyclically (numpy.resize).
     *
     * numpy.resize
     */
    public static function resize(mixed $a, mixed $newShape): mixed
    {
        return Registry::routine('np.resize', [$a, $newShape]);
    }

    /**
     * The dtype resulting from NumPy's type-promotion rules (numpy.result_type).
     *
     * numpy.result_type: the positional arguments are numpy's *arraysAndDtypes.
     */
    public static function resultType(mixed ...$arraysAndDtypes): mixed
    {
        return Registry::routineVariadic('np.result_type', $arraysAndDtypes);
    }

    /**
     * Shift the bits of each integer right by the per-element count (numpy.right_shift).
     *
     * numpy.right_shift
     */
    public static function rightShift(mixed $x1, mixed $x2): mixed
    {
        return Registry::routine('np.right_shift', [$x1, $x2]);
    }

    /**
     * Roll elements along the given axes; without axis on the flattened array (numpy.roll).
     *
     * numpy.roll
     */
    public static function roll(mixed $a, mixed $shift, mixed $axis = null): mixed
    {
        return Registry::routine('np.roll', [$a, $shift, $axis]);
    }

    /**
     * Roll an axis backwards to a position (numpy.rollaxis).
     *
     * numpy.rollaxis
     */
    public static function rollaxis(mixed $a, mixed $axis, mixed $start = 0): mixed
    {
        return Registry::routine('np.rollaxis', [$a, $axis, $start]);
    }

    /**
     * Roots of a polynomial, complex128 sorted by (re, im) (numpy.roots).
     *
     * numpy.roots
     */
    public static function roots(mixed $p): mixed
    {
        return Registry::routine('np.roots', [$p]);
    }

    /**
     * Rotate by 90 degrees in the plane of two axes, default (0, 1) (numpy.rot90).
     *
     * numpy.rot90
     */
    public static function rot90(mixed $m, mixed $k = 1, mixed $axes = null): mixed
    {
        return Registry::routine('np.rot90', [$m, $k, $axes]);
    }

    /**
     * Round to the given number of decimals, half to even (numpy.round).
     *
     * numpy.round
     */
    public static function round(mixed $a, mixed $decimals = 0): mixed
    {
        return Registry::routine('np.round', [$a, $decimals]);
    }

    /**
     * Indices where v would be inserted into the sorted array a (numpy.searchsorted).
     *
     * numpy.searchsorted
     */
    public static function searchsorted(mixed $a, mixed $v, string $side = 'left'): NDArray|float|int
    {
        return Registry::gufunc('np.searchsorted', [$a, $v], null, false, ['side' => $side]);
    }

    /**
     * Elements from the choices where the conditions hold (numpy.select).
     *
     * numpy.select
     */
    public static function select(mixed $condlist, mixed $choicelist, mixed $default = 0): mixed
    {
        return Registry::routine('np.select', [$condlist, $choicelist, $default]);
    }

    /**
     * Unique values of ar1 that are not in ar2 (numpy.setdiff1d).
     *
     * numpy.setdiff1d
     */
    public static function setdiff1d(mixed $ar1, mixed $ar2, mixed $assumeUnique = false): mixed
    {
        return Registry::routine('np.setdiff1d', [$ar1, $ar2, $assumeUnique]);
    }

    /**
     * Sorted values in exactly one of the arrays (numpy.setxor1d).
     *
     * numpy.setxor1d
     */
    public static function setxor1d(mixed $ar1, mixed $ar2, mixed $assumeUnique = false): mixed
    {
        return Registry::routine('np.setxor1d', [$ar1, $ar2, $assumeUnique]);
    }

    /**
     * The shape of an array (numpy.shape).
     *
     * numpy.shape
     */
    public static function shape(mixed $a): mixed
    {
        return Registry::routine('np.shape', [$a]);
    }

    /**
     * Integral by the composite Simpson's rule (scipy.integrate.simpson).
     *
     * numpy.simpson
     */
    public static function simpson(mixed $y, mixed $x = null, mixed $dx = 1.0, mixed $axis = -1): mixed
    {
        return Registry::routine('np.simpson', [$y, $x, $dx, $axis]);
    }

    /**
     * Normalised sinc, sin(pi x) / (pi x) (numpy.sinc).
     *
     * numpy.sinc
     */
    public static function sinc(mixed $x): mixed
    {
        return Registry::routine('np.sinc', [$x]);
    }

    /**
     * Number of elements, in total or along axes (numpy.size).
     *
     * numpy.size
     */
    public static function size(mixed $a, mixed $axis = null): mixed
    {
        return Registry::routine('np.size', [$a, $axis]);
    }

    /**
     * The signed distance from each element to the adjacent representable float (numpy.spacing).
     *
     * numpy.spacing
     */
    public static function spacing(mixed $x): mixed
    {
        return Registry::routine('np.spacing', [$x]);
    }

    /**
     * Split into equal sections or at the given indices (numpy.split).
     *
     * numpy.split
     */
    public static function split(mixed $ary, mixed $indicesOrSections, mixed $axis = 0): mixed
    {
        return Registry::routine('np.split', [$ary, $indicesOrSections, $axis]);
    }

    /**
     * Remove length-1 axes (numpy.squeeze).
     *
     * numpy.squeeze
     */
    public static function squeeze(mixed $a, mixed $axis = null): mixed
    {
        return Registry::routine('np.squeeze', [$a, $axis]);
    }

    /**
     * Join arrays along a new axis (numpy.stack).
     *
     * numpy.stack
     */
    public static function stack(mixed $arrays, mixed $axis = 0, mixed $dtype = null, mixed $casting = 'same_kind'): mixed
    {
        return Registry::routine('np.stack', [$arrays, $axis, $dtype, $casting]);
    }

    /**
     * Interchange two axes (numpy.swapaxes).
     *
     * numpy.swapaxes
     */
    public static function swapaxes(mixed $a, mixed $axis1, mixed $axis2): mixed
    {
        return Registry::routine('np.swapaxes', [$a, $axis1, $axis2]);
    }

    /**
     * Elements at the given indices along an axis (numpy.take).
     *
     * numpy.take
     */
    public static function take(mixed $a, mixed $indices, mixed $axis = null, mixed $mode = 'raise'): mixed
    {
        return Registry::routine('np.take', [$a, $indices, $axis, $mode]);
    }

    /**
     * Pick values by matching 1-D index slices (numpy.take_along_axis).
     *
     * numpy.take_along_axis
     */
    public static function takeAlongAxis(mixed $arr, mixed $indices, mixed $axis = -1): mixed
    {
        return Registry::routine('np.take_along_axis', [$arr, $indices, $axis]);
    }

    /**
     * Tensor dot product over the given axes (numpy.tensordot).
     *
     * numpy.tensordot
     */
    public static function tensordot(mixed $a, mixed $b, mixed $axes = 2): mixed
    {
        return Registry::routine('np.tensordot', [$a, $b, $axes]);
    }

    /**
     * Repeat an array the given number of times per axis (numpy.tile).
     *
     * numpy.tile
     */
    public static function tile(mixed $A, mixed $reps): mixed
    {
        return Registry::routine('np.tile', [$A, $reps]);
    }

    /**
     * Sum along a diagonal (numpy.trace).
     *
     * numpy.trace
     */
    public static function trace(mixed $a, mixed $offset = 0, mixed $axis1 = 0, mixed $axis2 = 1, mixed $dtype = null): mixed
    {
        return Registry::routine('np.trace', [$a, $offset, $axis1, $axis2, $dtype]);
    }

    /**
     * Integral by the composite trapezoidal rule (numpy.trapezoid).
     *
     * numpy.trapezoid
     */
    public static function trapezoid(mixed $y, mixed $x = null, mixed $dx = 1.0, mixed $axis = -1): mixed
    {
        return Registry::routine('np.trapezoid', [$y, $x, $dx, $axis]);
    }

    /**
     * Ones at and below the k-th diagonal, zeros elsewhere (numpy.tri).
     *
     * numpy.tri
     */
    public static function tri(mixed $N, mixed $M = null, mixed $k = 0, mixed $dtype = 'float64'): mixed
    {
        return Registry::routine('np.tri', [$N, $M, $k, $dtype]);
    }

    /**
     * Lower triangle of an array (numpy.tril).
     *
     * numpy.tril
     */
    public static function tril(mixed $m, mixed $k = 0): mixed
    {
        return Registry::routine('np.tril', [$m, $k]);
    }

    /**
     * Indices of the lower triangle of an (n, m) array (numpy.tril_indices).
     *
     * numpy.tril_indices
     */
    public static function trilIndices(mixed $n, mixed $k = 0, mixed $m = null): mixed
    {
        return Registry::routine('np.tril_indices', [$n, $k, $m]);
    }

    /**
     * Indices of the lower triangle of a 2-D array (numpy.tril_indices_from).
     *
     * numpy.tril_indices_from
     */
    public static function trilIndicesFrom(mixed $arr, mixed $k = 0): mixed
    {
        return Registry::routine('np.tril_indices_from', [$arr, $k]);
    }

    /**
     * Trim leading and/or trailing zeros (numpy.trim_zeros).
     *
     * numpy.trim_zeros
     */
    public static function trimZeros(mixed $filt, mixed $trim = 'fb', mixed $axis = null): mixed
    {
        return Registry::routine('np.trim_zeros', [$filt, $trim, $axis]);
    }

    /**
     * Upper triangle of an array (numpy.triu).
     *
     * numpy.triu
     */
    public static function triu(mixed $m, mixed $k = 0): mixed
    {
        return Registry::routine('np.triu', [$m, $k]);
    }

    /**
     * Indices of the upper triangle of an (n, m) array (numpy.triu_indices).
     *
     * numpy.triu_indices
     */
    public static function triuIndices(mixed $n, mixed $k = 0, mixed $m = null): mixed
    {
        return Registry::routine('np.triu_indices', [$n, $k, $m]);
    }

    /**
     * Indices of the upper triangle of a 2-D array (numpy.triu_indices_from).
     *
     * numpy.triu_indices_from
     */
    public static function triuIndicesFrom(mixed $arr, mixed $k = 0): mixed
    {
        return Registry::routine('np.triu_indices_from', [$arr, $k]);
    }

    /**
     * Sorted unique values in either array (numpy.union1d).
     *
     * numpy.union1d
     */
    public static function union1d(mixed $ar1, mixed $ar2): mixed
    {
        return Registry::routine('np.union1d', [$ar1, $ar2]);
    }

    /**
     * Sorted unique elements, optionally with indices, inverse and counts (numpy.unique).
     *
     * numpy.unique
     *
     * @return mixed one array, or an array keyed by values, indices, inverse, counts when several results are requested
     */
    public static function unique(mixed $ar, mixed $returnIndex = false, mixed $returnInverse = false, mixed $returnCounts = false, mixed $equalNan = true): mixed
    {
        return Registry::routine('np.unique', [$ar, $returnIndex, $returnInverse, $returnCounts, $equalNan]);
    }

    /**
     * Unique values, first indices, inverse indices and counts (numpy.unique_all).
     *
     * numpy.unique_all
     *
     * @return mixed one array, or an array keyed by values, indices, inverse_indices, counts when several results are requested
     */
    public static function uniqueAll(mixed $x): mixed
    {
        return Registry::routine('np.unique_all', [$x]);
    }

    /**
     * Unique values and their counts (numpy.unique_counts).
     *
     * numpy.unique_counts
     *
     * @return mixed one array, or an array keyed by values, counts when several results are requested
     */
    public static function uniqueCounts(mixed $x): mixed
    {
        return Registry::routine('np.unique_counts', [$x]);
    }

    /**
     * Unique values and the inverse indices (numpy.unique_inverse).
     *
     * numpy.unique_inverse
     *
     * @return mixed one array, or an array keyed by values, inverse_indices when several results are requested
     */
    public static function uniqueInverse(mixed $x): mixed
    {
        return Registry::routine('np.unique_inverse', [$x]);
    }

    /**
     * Unique values; NaNs are not merged (numpy.unique_values).
     *
     * numpy.unique_values
     */
    public static function uniqueValues(mixed $x): mixed
    {
        return Registry::routine('np.unique_values', [$x]);
    }

    /**
     * Convert flat indices into a tuple of coordinate arrays (numpy.unravel_index).
     *
     * numpy.unravel_index
     */
    public static function unravelIndex(mixed $indices, mixed $shape, mixed $order = 'C'): mixed
    {
        return Registry::routine('np.unravel_index', [$indices, $shape, $order]);
    }

    /**
     * Split an array into the arrays along an axis (numpy.unstack).
     *
     * numpy.unstack
     */
    public static function unstack(mixed $x, mixed $axis = 0): mixed
    {
        return Registry::routine('np.unstack', [$x, $axis]);
    }

    /**
     * Unwrap by taking the complement of large jumps with respect to the period (numpy.unwrap).
     *
     * numpy.unwrap
     */
    public static function unwrap(mixed $p, mixed $discont = null, mixed $axis = -1, mixed $period = 6.283185307179586): mixed
    {
        return Registry::routine('np.unwrap', [$p, $discont, $axis, $period]);
    }

    /**
     * Vandermonde matrix (numpy.vander).
     *
     * numpy.vander
     */
    public static function vander(mixed $x, mixed $N = null, mixed $increasing = false): mixed
    {
        return Registry::routine('np.vander', [$x, $N, $increasing]);
    }

    /**
     * Dot product of the flattened arrays (numpy.vdot).
     *
     * numpy.vdot
     */
    public static function vdot(mixed $a, mixed $b): mixed
    {
        return Registry::routine('np.vdot', [$a, $b]);
    }

    /**
     * Vector dot product over the last axis (numpy.vecdot).
     *
     * numpy.vecdot
     */
    public static function vecdot(mixed $x1, mixed $x2, mixed $axis = -1): mixed
    {
        return Registry::routine('np.vecdot', [$x1, $x2, $axis]);
    }

    /**
     * Vector-matrix product; x1 is (..., N), x2 is (..., N, M) (numpy.vecmat).
     *
     * numpy.vecmat
     */
    public static function vecmat(mixed $x1, mixed $x2): mixed
    {
        return Registry::routine('np.vecmat', [$x1, $x2]);
    }

    /**
     * Split vertically, row-wise (numpy.vsplit).
     *
     * numpy.vsplit
     */
    public static function vsplit(mixed $ary, mixed $indicesOrSections): mixed
    {
        return Registry::routine('np.vsplit', [$ary, $indicesOrSections]);
    }

    /**
     * Stack arrays vertically, row-wise (numpy.vstack).
     *
     * numpy.vstack
     */
    public static function vstack(mixed $tup, mixed $dtype = null, mixed $casting = 'same_kind'): mixed
    {
        return Registry::routine('np.vstack', [$tup, $dtype, $casting]);
    }

    /**
     * Zeros with the shape and dtype of an array (numpy.zeros_like).
     *
     * numpy.zeros_like
     */
    public static function zerosLike(mixed $a, mixed $dtype = null, mixed $shape = null): mixed
    {
        return Registry::routine('np.zeros_like', [$a, $dtype, $shape]);
    }
}
