<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * scipy.linalg on LAPACK, shared by both backends through the kernel: solve, inv, det, cholesky, lu, solve_triangular, svd, eigh, ...
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\ScipyLinalg.
 */
final class ScipyLinalg
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'block_diag' => 'blockDiag',
    'cho_factor' => 'choFactor',
    'cho_solve' => 'choSolve',
    'cho_solve_banded' => 'choSolveBanded',
    'cholesky' => 'cholesky',
    'cholesky_banded' => 'choleskyBanded',
    'circulant' => 'circulant',
    'companion' => 'companion',
    'convolution_matrix' => 'convolutionMatrix',
    'coshm' => 'coshm',
    'cosm' => 'cosm',
    'det' => 'det',
    'dft' => 'dft',
    'diagsvd' => 'diagsvd',
    'eig' => 'eig',
    'eig_banded' => 'eigBanded',
    'eigh' => 'eigh',
    'eigh_tridiagonal' => 'eighTridiagonal',
    'eigvals' => 'eigvals',
    'eigvals_banded' => 'eigvalsBanded',
    'eigvalsh' => 'eigvalsh',
    'eigvalsh_tridiagonal' => 'eigvalshTridiagonal',
    'expm' => 'expm',
    'fiedler' => 'fiedler',
    'fractional_matrix_power' => 'fractionalMatrixPower',
    'hadamard' => 'hadamard',
    'hankel' => 'hankel',
    'helmert' => 'helmert',
    'hessenberg' => 'hessenberg',
    'hilbert' => 'hilbert',
    'inv' => 'inv',
    'invhilbert' => 'invhilbert',
    'invpascal' => 'invpascal',
    'ishermitian' => 'ishermitian',
    'issymmetric' => 'issymmetric',
    'khatri_rao' => 'khatriRao',
    'ldl' => 'ldl',
    'leslie' => 'leslie',
    'logm' => 'logm',
    'lstsq' => 'lstsq',
    'lu' => 'lu',
    'lu_factor' => 'luFactor',
    'lu_solve' => 'luSolve',
    'matmul_toeplitz' => 'matmulToeplitz',
    'norm' => 'norm',
    'null_space' => 'nullSpace',
    'orth' => 'orth',
    'pascal' => 'pascal',
    'pinv' => 'pinv',
    'pinvh' => 'pinvh',
    'polar' => 'polar',
    'qr' => 'qr',
    'qz' => 'qz',
    'schur' => 'schur',
    'sinhm' => 'sinhm',
    'sinm' => 'sinm',
    'solve' => 'solve',
    'solve_banded' => 'solveBanded',
    'solve_circulant' => 'solveCirculant',
    'solve_continuous_lyapunov' => 'solveContinuousLyapunov',
    'solve_discrete_lyapunov' => 'solveDiscreteLyapunov',
    'solve_sylvester' => 'solveSylvester',
    'solve_toeplitz' => 'solveToeplitz',
    'solve_triangular' => 'solveTriangular',
    'solveh_banded' => 'solvehBanded',
    'sqrtm' => 'sqrtm',
    'svd' => 'svd',
    'svdvals' => 'svdvals',
    'tanhm' => 'tanhm',
    'tanm' => 'tanm',
    'toeplitz' => 'toeplitz',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: ScipyLinalg::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("ScipyLinalg::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * Assemble 2-D blocks on the diagonal of a larger zero matrix (scipy.linalg.block_diag).
     *
     * scipy.linalg.block_diag: the positional arguments are numpy's *arrs.
     */
    public static function blockDiag(mixed ...$arrs): mixed
    {
        return Registry::routineVariadic('slinalg.block_diag', $arrs);
    }

    /**
     * Cholesky factor for cho_solve, other triangle left as input (scipy.linalg.cho_factor).
     *
     * scipy.linalg.cho_factor
     *
     * @return mixed one array, or an array keyed by c, lower when several results are requested
     */
    public static function choFactor(mixed $a, mixed $lower = false): mixed
    {
        return Registry::routine('slinalg.cho_factor', [$a, $lower]);
    }

    /**
     * Solve a x = b from a Cholesky factor; takes c, lower, b unpacked (scipy.linalg.cho_solve).
     *
     * scipy.linalg.cho_solve
     */
    public static function choSolve(mixed $c, mixed $lower, mixed $b): mixed
    {
        return Registry::routine('slinalg.cho_solve', [$c, $lower, $b]);
    }

    /**
     * Solve A x = b from a banded Cholesky factor via dpbtrs (scipy.linalg.cho_solve_banded).
     *
     * scipy.linalg.cho_solve_banded
     */
    public static function choSolveBanded(mixed $cb, mixed $lower, mixed $b): mixed
    {
        return Registry::routine('slinalg.cho_solve_banded', [$cb, $lower, $b]);
    }

    /**
     * Cholesky factor, upper by default (scipy.linalg.cholesky).
     *
     * scipy.linalg.cholesky
     */
    public static function cholesky(mixed $a, mixed $lower = false): mixed
    {
        return Registry::routine('slinalg.cholesky', [$a, $lower]);
    }

    /**
     * Cholesky factor of a symmetric positive-definite banded matrix via dpbtrf (scipy.linalg.cholesky_banded).
     *
     * scipy.linalg.cholesky_banded
     */
    public static function choleskyBanded(mixed $ab, mixed $lower = false): mixed
    {
        return Registry::routine('slinalg.cholesky_banded', [$ab, $lower]);
    }

    /**
     * Circulant matrix with first column c (scipy.linalg.circulant).
     *
     * scipy.linalg.circulant
     */
    public static function circulant(mixed $c): mixed
    {
        return Registry::routine('slinalg.circulant', [$c]);
    }

    /**
     * Companion matrix of a polynomial (scipy.linalg.companion).
     *
     * scipy.linalg.companion
     */
    public static function companion(mixed $a): mixed
    {
        return Registry::routine('slinalg.companion', [$a]);
    }

    /**
     * Toeplitz matrix A with A @ v = convolve(a, v, mode) (scipy.linalg.convolution_matrix).
     *
     * scipy.linalg.convolution_matrix
     */
    public static function convolutionMatrix(mixed $a, mixed $n, mixed $mode = 'full'): mixed
    {
        return Registry::routine('slinalg.convolution_matrix', [$a, $n, $mode]);
    }

    /**
     * Matrix hyperbolic cosine via the Schur-Parlett method (scipy.linalg.coshm; real spectrum).
     *
     * scipy.linalg.coshm
     */
    public static function coshm(mixed $a): mixed
    {
        return Registry::routine('slinalg.coshm', [$a]);
    }

    /**
     * Matrix cosine via the Schur-Parlett method (scipy.linalg.cosm; real spectrum).
     *
     * scipy.linalg.cosm
     */
    public static function cosm(mixed $a): mixed
    {
        return Registry::routine('slinalg.cosm', [$a]);
    }

    /**
     * Determinant of a square matrix (scipy.linalg.det).
     *
     * scipy.linalg.det
     */
    public static function det(mixed $a): mixed
    {
        return Registry::routine('slinalg.det', [$a]);
    }

    /**
     * The n x n discrete Fourier transform matrix (scipy.linalg.dft).
     *
     * scipy.linalg.dft
     */
    public static function dft(mixed $n, mixed $scale = null): mixed
    {
        return Registry::routine('slinalg.dft', [$n, $scale]);
    }

    /**
     * M x N matrix with s on the diagonal (scipy.linalg.diagsvd).
     *
     * scipy.linalg.diagsvd
     */
    public static function diagsvd(mixed $s, mixed $M, mixed $N): mixed
    {
        return Registry::routine('slinalg.diagsvd', [$s, $M, $N]);
    }

    /**
     * Eigenvalues and right eigenvectors of a general matrix, complex (scipy.linalg.eig).
     *
     * scipy.linalg.eig
     *
     * @return mixed one array, or an array keyed by eigenvalues, eigenvectors when several results are requested
     */
    public static function eig(mixed $a): mixed
    {
        return Registry::routine('slinalg.eig', [$a]);
    }

    /**
     * Eigenvalues and eigenvectors of a symmetric banded matrix via dsbevd (scipy.linalg.eig_banded).
     *
     * scipy.linalg.eig_banded
     *
     * @return mixed one array, or an array keyed by w, v when several results are requested
     */
    public static function eigBanded(mixed $ab, mixed $lower = false, mixed $eigvalsOnly = false): mixed
    {
        return Registry::routine('slinalg.eig_banded', [$ab, $lower, $eigvalsOnly]);
    }

    /**
     * Eigenvalues and eigenvectors of a symmetric matrix (scipy.linalg.eigh).
     *
     * scipy.linalg.eigh
     *
     * @return mixed one array, or an array keyed by eigenvalues, eigenvectors when several results are requested
     */
    public static function eigh(mixed $a): mixed
    {
        return Registry::routine('slinalg.eigh', [$a]);
    }

    /**
     * Eigenvalues and eigenvectors of a symmetric tridiagonal matrix via dstev (scipy.linalg.eigh_tridiagonal).
     *
     * scipy.linalg.eigh_tridiagonal
     *
     * @return mixed one array, or an array keyed by eigenvalues, eigenvectors when several results are requested
     */
    public static function eighTridiagonal(mixed $d, mixed $e): mixed
    {
        return Registry::routine('slinalg.eigh_tridiagonal', [$d, $e]);
    }

    /**
     * Eigenvalues of a general matrix, complex, sorted (scipy.linalg.eigvals).
     *
     * scipy.linalg.eigvals
     */
    public static function eigvals(mixed $a): mixed
    {
        return Registry::routine('slinalg.eigvals', [$a]);
    }

    /**
     * Eigenvalues of a symmetric banded matrix in band storage via dsbevd (scipy.linalg.eigvals_banded).
     *
     * scipy.linalg.eigvals_banded
     */
    public static function eigvalsBanded(mixed $aBand, mixed $lower = false): mixed
    {
        return Registry::routine('slinalg.eigvals_banded', [$aBand, $lower]);
    }

    /**
     * Eigenvalues of a symmetric matrix, ascending (scipy.linalg.eigvalsh).
     *
     * scipy.linalg.eigvalsh
     */
    public static function eigvalsh(mixed $a): mixed
    {
        return Registry::routine('slinalg.eigvalsh', [$a]);
    }

    /**
     * Eigenvalues of a symmetric tridiagonal matrix via dsterf (scipy.linalg.eigvalsh_tridiagonal).
     *
     * scipy.linalg.eigvalsh_tridiagonal
     */
    public static function eigvalshTridiagonal(mixed $d, mixed $e): mixed
    {
        return Registry::routine('slinalg.eigvalsh_tridiagonal', [$d, $e]);
    }

    /**
     * Matrix exponential via the Schur-Parlett method (scipy.linalg.expm; real spectrum).
     *
     * scipy.linalg.expm
     */
    public static function expm(mixed $a): mixed
    {
        return Registry::routine('slinalg.expm', [$a]);
    }

    /**
     * Symmetric Fiedler matrix of absolute differences |a_i - a_j| (scipy.linalg.fiedler).
     *
     * scipy.linalg.fiedler
     */
    public static function fiedler(mixed $a): mixed
    {
        return Registry::routine('slinalg.fiedler', [$a]);
    }

    /**
     * Fractional matrix power a^t via the Schur-Parlett method (scipy.linalg.fractional_matrix_power; positive real spectrum).
     *
     * scipy.linalg.fractional_matrix_power
     */
    public static function fractionalMatrixPower(mixed $a, mixed $t): mixed
    {
        return Registry::routine('slinalg.fractional_matrix_power', [$a, $t]);
    }

    /**
     * Sylvester-Hadamard matrix of order n, a power of two (scipy.linalg.hadamard).
     *
     * scipy.linalg.hadamard
     */
    public static function hadamard(mixed $n): mixed
    {
        return Registry::routine('slinalg.hadamard', [$n]);
    }

    /**
     * Hankel matrix with first column c and last row r (scipy.linalg.hankel).
     *
     * scipy.linalg.hankel
     */
    public static function hankel(mixed $c, mixed $r = null): mixed
    {
        return Registry::routine('slinalg.hankel', [$c, $r]);
    }

    /**
     * Helmert matrix of order n (scipy.linalg.helmert).
     *
     * scipy.linalg.helmert
     */
    public static function helmert(mixed $n, mixed $full = false): mixed
    {
        return Registry::routine('slinalg.helmert', [$n, $full]);
    }

    /**
     * Upper Hessenberg form via dgehrd (scipy.linalg.hessenberg).
     *
     * scipy.linalg.hessenberg
     */
    public static function hessenberg(mixed $a, mixed $calcQ = false): mixed
    {
        return Registry::routine('slinalg.hessenberg', [$a, $calcQ]);
    }

    /**
     * Hilbert matrix of order n (scipy.linalg.hilbert).
     *
     * scipy.linalg.hilbert
     */
    public static function hilbert(mixed $n): mixed
    {
        return Registry::routine('slinalg.hilbert', [$n]);
    }

    /**
     * Inverse of a square matrix (scipy.linalg.inv).
     *
     * scipy.linalg.inv
     */
    public static function inv(mixed $a): mixed
    {
        return Registry::routine('slinalg.inv', [$a]);
    }

    /**
     * Inverse of the Hilbert matrix of order n (scipy.linalg.invhilbert).
     *
     * scipy.linalg.invhilbert
     */
    public static function invhilbert(mixed $n): mixed
    {
        return Registry::routine('slinalg.invhilbert', [$n]);
    }

    /**
     * Inverse of the Pascal matrix of order n (scipy.linalg.invpascal).
     *
     * scipy.linalg.invpascal
     */
    public static function invpascal(mixed $n, mixed $kind = 'symmetric'): mixed
    {
        return Registry::routine('slinalg.invpascal', [$n, $kind]);
    }

    /**
     * Whether a square matrix is Hermitian; for real input, symmetric (scipy.linalg.ishermitian).
     *
     * scipy.linalg.ishermitian
     */
    public static function ishermitian(mixed $a, mixed $atol = null, mixed $rtol = null): mixed
    {
        return Registry::routine('slinalg.ishermitian', [$a, $atol, $rtol]);
    }

    /**
     * Whether a square matrix is symmetric (scipy.linalg.issymmetric).
     *
     * scipy.linalg.issymmetric
     */
    public static function issymmetric(mixed $a, mixed $atol = null, mixed $rtol = null): mixed
    {
        return Registry::routine('slinalg.issymmetric', [$a, $atol, $rtol]);
    }

    /**
     * Column-wise Kronecker (Khatri-Rao) product (scipy.linalg.khatri_rao).
     *
     * scipy.linalg.khatri_rao
     */
    public static function khatriRao(mixed $a, mixed $b): mixed
    {
        return Registry::routine('slinalg.khatri_rao', [$a, $b]);
    }

    /**
     * LDL^T factorisation of a symmetric matrix via dsytrf (scipy.linalg.ldl).
     *
     * scipy.linalg.ldl
     *
     * @return mixed one array, or an array keyed by lu, d, perm when several results are requested
     */
    public static function ldl(mixed $a, mixed $lower = true): mixed
    {
        return Registry::routine('slinalg.ldl', [$a, $lower]);
    }

    /**
     * Leslie population matrix with first row f and sub-diagonal s (scipy.linalg.leslie).
     *
     * scipy.linalg.leslie
     */
    public static function leslie(mixed $f, mixed $s): mixed
    {
        return Registry::routine('slinalg.leslie', [$f, $s]);
    }

    /**
     * Principal matrix logarithm via the Schur-Parlett method (scipy.linalg.logm; distinct positive real spectrum).
     *
     * scipy.linalg.logm
     */
    public static function logm(mixed $a, mixed $disp = true): mixed
    {
        return Registry::routine('slinalg.logm', [$a, $disp]);
    }

    /**
     * Least-squares solution (scipy.linalg.lstsq).
     *
     * scipy.linalg.lstsq
     *
     * @return mixed one array, or an array keyed by x, residues, rank, s when several results are requested
     */
    public static function lstsq(mixed $a, mixed $b, mixed $cond = null): mixed
    {
        return Registry::routine('slinalg.lstsq', [$a, $b, $cond]);
    }

    /**
     * LU factorisation with partial pivoting, A = P L U (scipy.linalg.lu).
     *
     * scipy.linalg.lu
     *
     * @return mixed one array, or an array keyed by p, l, u when several results are requested
     */
    public static function lu(mixed $a, mixed $permuteL = false): mixed
    {
        return Registry::routine('slinalg.lu', [$a, $permuteL]);
    }

    /**
     * LU factorisation for lu_solve: combined factors and 0-based pivots (scipy.linalg.lu_factor).
     *
     * scipy.linalg.lu_factor
     *
     * @return mixed one array, or an array keyed by lu, piv when several results are requested
     */
    public static function luFactor(mixed $a): mixed
    {
        return Registry::routine('slinalg.lu_factor', [$a]);
    }

    /**
     * Solve a x = b from an lu_factor result; takes lu, piv, b unpacked (scipy.linalg.lu_solve).
     *
     * scipy.linalg.lu_solve
     */
    public static function luSolve(mixed $lu, mixed $piv, mixed $b, mixed $trans = 0): mixed
    {
        return Registry::routine('slinalg.lu_solve', [$lu, $piv, $b, $trans]);
    }

    /**
     * The product of a Toeplitz matrix with x (scipy.linalg.matmul_toeplitz).
     *
     * scipy.linalg.matmul_toeplitz
     */
    public static function matmulToeplitz(mixed $cOrCr, mixed $x): mixed
    {
        return Registry::routine('slinalg.matmul_toeplitz', [$cOrCr, $x]);
    }

    /**
     * Vector or matrix norm (scipy.linalg.norm).
     *
     * scipy.linalg.norm
     */
    public static function norm(mixed $a, mixed $ord = null, mixed $axis = null, mixed $keepdims = false): mixed
    {
        return Registry::routine('slinalg.norm', [$a, $ord, $axis, $keepdims]);
    }

    /**
     * Orthonormal basis for the null space of A via SVD (scipy.linalg.null_space).
     *
     * scipy.linalg.null_space
     */
    public static function nullSpace(mixed $A, mixed $rcond = null): mixed
    {
        return Registry::routine('slinalg.null_space', [$A, $rcond]);
    }

    /**
     * Orthonormal basis for the range of A via SVD (scipy.linalg.orth).
     *
     * scipy.linalg.orth
     */
    public static function orth(mixed $A, mixed $rcond = null): mixed
    {
        return Registry::routine('slinalg.orth', [$A, $rcond]);
    }

    /**
     * Pascal matrix of order n (scipy.linalg.pascal).
     *
     * scipy.linalg.pascal
     */
    public static function pascal(mixed $n, mixed $kind = 'symmetric'): mixed
    {
        return Registry::routine('slinalg.pascal', [$n, $kind]);
    }

    /**
     * Moore-Penrose pseudo-inverse via SVD (scipy.linalg.pinv).
     *
     * scipy.linalg.pinv
     */
    public static function pinv(mixed $a): mixed
    {
        return Registry::routine('slinalg.pinv', [$a]);
    }

    /**
     * Moore-Penrose pseudo-inverse of a symmetric matrix via eigendecomposition (scipy.linalg.pinvh).
     *
     * scipy.linalg.pinvh
     */
    public static function pinvh(mixed $a): mixed
    {
        return Registry::routine('slinalg.pinvh', [$a]);
    }

    /**
     * Polar decomposition a = u p (right) or p u (left) via SVD (scipy.linalg.polar).
     *
     * scipy.linalg.polar
     *
     * @return mixed one array, or an array keyed by u, p when several results are requested
     */
    public static function polar(mixed $a, mixed $side = 'right'): mixed
    {
        return Registry::routine('slinalg.polar', [$a, $side]);
    }

    /**
     * QR factorisation (scipy.linalg.qr; mode 'full' or 'economic').
     *
     * scipy.linalg.qr
     *
     * @return mixed one array, or an array keyed by Q, R when several results are requested
     */
    public static function qr(mixed $a, mixed $mode = 'full'): mixed
    {
        return Registry::routine('slinalg.qr', [$a, $mode]);
    }

    /**
     * Generalised real Schur decomposition via dgges (scipy.linalg.qz).
     *
     * scipy.linalg.qz
     *
     * @return mixed one array, or an array keyed by AA, BB, Q, Z when several results are requested
     */
    public static function qz(mixed $A, mixed $B, mixed $output = 'real'): mixed
    {
        return Registry::routine('slinalg.qz', [$A, $B, $output]);
    }

    /**
     * Real Schur decomposition A = Z T Z^T via dgees (scipy.linalg.schur).
     *
     * scipy.linalg.schur
     *
     * @return mixed one array, or an array keyed by T, Z when several results are requested
     */
    public static function schur(mixed $a, mixed $output = 'real'): mixed
    {
        return Registry::routine('slinalg.schur', [$a, $output]);
    }

    /**
     * Matrix hyperbolic sine via the Schur-Parlett method (scipy.linalg.sinhm; real spectrum).
     *
     * scipy.linalg.sinhm
     */
    public static function sinhm(mixed $a): mixed
    {
        return Registry::routine('slinalg.sinhm', [$a]);
    }

    /**
     * Matrix sine via the Schur-Parlett method (scipy.linalg.sinm; real spectrum).
     *
     * scipy.linalg.sinm
     */
    public static function sinm(mixed $a): mixed
    {
        return Registry::routine('slinalg.sinm', [$a]);
    }

    /**
     * Solve a linear system a x = b (scipy.linalg.solve).
     *
     * scipy.linalg.solve
     */
    public static function solve(mixed $a, mixed $b): mixed
    {
        return Registry::routine('slinalg.solve', [$a, $b]);
    }

    /**
     * Solve a banded linear system via dgbsv; takes l, u, ab, b unpacked (scipy.linalg.solve_banded).
     *
     * scipy.linalg.solve_banded
     */
    public static function solveBanded(mixed $l, mixed $u, mixed $ab, mixed $b): mixed
    {
        return Registry::routine('slinalg.solve_banded', [$l, $u, $ab, $b]);
    }

    /**
     * Solve a circulant system C x = b (scipy.linalg.solve_circulant).
     *
     * scipy.linalg.solve_circulant
     */
    public static function solveCirculant(mixed $c, mixed $b): mixed
    {
        return Registry::routine('slinalg.solve_circulant', [$c, $b]);
    }

    /**
     * Solve the continuous Lyapunov equation a x + x a^H = q (scipy.linalg.solve_continuous_lyapunov).
     *
     * scipy.linalg.solve_continuous_lyapunov
     */
    public static function solveContinuousLyapunov(mixed $a, mixed $q): mixed
    {
        return Registry::routine('slinalg.solve_continuous_lyapunov', [$a, $q]);
    }

    /**
     * Solve the discrete Lyapunov equation a x a^H - x + q = 0 (scipy.linalg.solve_discrete_lyapunov).
     *
     * scipy.linalg.solve_discrete_lyapunov
     */
    public static function solveDiscreteLyapunov(mixed $a, mixed $q): mixed
    {
        return Registry::routine('slinalg.solve_discrete_lyapunov', [$a, $q]);
    }

    /**
     * Solve the Sylvester equation a x + x b = q (scipy.linalg.solve_sylvester).
     *
     * scipy.linalg.solve_sylvester
     */
    public static function solveSylvester(mixed $a, mixed $b, mixed $q): mixed
    {
        return Registry::routine('slinalg.solve_sylvester', [$a, $b, $q]);
    }

    /**
     * Solve a Toeplitz system T x = b (scipy.linalg.solve_toeplitz).
     *
     * scipy.linalg.solve_toeplitz
     */
    public static function solveToeplitz(mixed $cOrCr, mixed $b): mixed
    {
        return Registry::routine('slinalg.solve_toeplitz', [$cOrCr, $b]);
    }

    /**
     * Solve a triangular system (scipy.linalg.solve_triangular).
     *
     * scipy.linalg.solve_triangular
     */
    public static function solveTriangular(mixed $a, mixed $b, mixed $trans = 0, mixed $lower = false, mixed $unitDiagonal = false): mixed
    {
        return Registry::routine('slinalg.solve_triangular', [$a, $b, $trans, $lower, $unitDiagonal]);
    }

    /**
     * Solve a Hermitian positive-definite banded system via dpbsv (scipy.linalg.solveh_banded).
     *
     * scipy.linalg.solveh_banded
     */
    public static function solvehBanded(mixed $ab, mixed $b, mixed $lower = false): mixed
    {
        return Registry::routine('slinalg.solveh_banded', [$ab, $b, $lower]);
    }

    /**
     * Principal matrix square root via the Schur method (scipy.linalg.sqrtm; real spectrum).
     *
     * scipy.linalg.sqrtm
     */
    public static function sqrtm(mixed $a, mixed $disp = true): mixed
    {
        return Registry::routine('slinalg.sqrtm', [$a, $disp]);
    }

    /**
     * Singular value decomposition (scipy.linalg.svd).
     *
     * scipy.linalg.svd
     *
     * @return mixed one array, or an array keyed by U, s, Vh when several results are requested
     */
    public static function svd(mixed $a, mixed $fullMatrices = true): mixed
    {
        return Registry::routine('slinalg.svd', [$a, $fullMatrices]);
    }

    /**
     * Singular values of a matrix (scipy.linalg.svdvals).
     *
     * scipy.linalg.svdvals
     */
    public static function svdvals(mixed $a): mixed
    {
        return Registry::routine('slinalg.svdvals', [$a]);
    }

    /**
     * Matrix hyperbolic tangent via the Schur-Parlett method (scipy.linalg.tanhm; real spectrum).
     *
     * scipy.linalg.tanhm
     */
    public static function tanhm(mixed $a): mixed
    {
        return Registry::routine('slinalg.tanhm', [$a]);
    }

    /**
     * Matrix tangent via the Schur-Parlett method (scipy.linalg.tanm; real spectrum).
     *
     * scipy.linalg.tanm
     */
    public static function tanm(mixed $a): mixed
    {
        return Registry::routine('slinalg.tanm', [$a]);
    }

    /**
     * Toeplitz matrix with first column c and first row r (scipy.linalg.toeplitz).
     *
     * scipy.linalg.toeplitz
     */
    public static function toeplitz(mixed $c, mixed $r = null): mixed
    {
        return Registry::routine('slinalg.toeplitz', [$c, $r]);
    }
}
