<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * scipy.signal: 1-D convolve (full/same/valid) and lfilter over real float64 sequences.
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\Signal.
 */
final class Signal
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'butter' => 'butter',
    'cheby1' => 'cheby1',
    'cheby2' => 'cheby2',
    'chirp' => 'chirp',
    'convolve' => 'convolve',
    'correlate' => 'correlate',
    'detrend' => 'detrend',
    'fftconvolve' => 'fftconvolve',
    'filtfilt' => 'filtfilt',
    'freqz' => 'freqz',
    'gausspulse' => 'gausspulse',
    'lfilter' => 'lfilter',
    'lfilter_zi' => 'lfilterZi',
    'normalize' => 'normalize',
    'oaconvolve' => 'oaconvolve',
    'savgol_coeffs' => 'savgolCoeffs',
    'savgol_filter' => 'savgolFilter',
    'sawtooth' => 'sawtooth',
    'sos2tf' => 'sos2tf',
    'sosfilt' => 'sosfilt',
    'sosfilt_zi' => 'sosfiltZi',
    'sosfiltfilt' => 'sosfiltfilt',
    'square' => 'square',
    'tf2zpk' => 'tf2zpk',
    'unit_impulse' => 'unitImpulse',
    'zpk2tf' => 'zpk2tf',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: Signal::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("Signal::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * Butterworth IIR filter design, digital lowpass/highpass, output 'ba' (scipy.signal.butter).
     *
     * scipy.signal.butter
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function butter(mixed $N, mixed $Wn, mixed $btype = 'low', mixed $analog = false, mixed $output = 'ba', mixed $fs = null): mixed
    {
        return Registry::routine('signal.butter', [$N, $Wn, $btype, $analog, $output, $fs]);
    }

    /**
     * Chebyshev type I IIR filter design, digital lowpass/highpass, output 'ba' (scipy.signal.cheby1).
     *
     * scipy.signal.cheby1
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function cheby1(mixed $N, mixed $rp, mixed $Wn, mixed $btype = 'low', mixed $analog = false, mixed $output = 'ba', mixed $fs = null): mixed
    {
        return Registry::routine('signal.cheby1', [$N, $rp, $Wn, $btype, $analog, $output, $fs]);
    }

    /**
     * Chebyshev type II IIR filter design, digital lowpass/highpass, output 'ba' (scipy.signal.cheby2).
     *
     * scipy.signal.cheby2
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function cheby2(mixed $N, mixed $rs, mixed $Wn, mixed $btype = 'low', mixed $analog = false, mixed $output = 'ba', mixed $fs = null): mixed
    {
        return Registry::routine('signal.cheby2', [$N, $rs, $Wn, $btype, $analog, $output, $fs]);
    }

    /**
     * Frequency-swept cosine (linear/quadratic/logarithmic/hyperbolic) (scipy.signal.chirp).
     *
     * scipy.signal.chirp
     */
    public static function chirp(mixed $t, mixed $f0, mixed $t1, mixed $f1, mixed $method = 'linear', mixed $phi = 0, mixed $vertexZero = true): mixed
    {
        return Registry::routine('signal.chirp', [$t, $f0, $t1, $f1, $method, $phi, $vertexZero]);
    }

    /**
     * 1-D convolution of two sequences, modes full/same/valid (scipy.signal.convolve).
     *
     * scipy.signal.convolve
     */
    public static function convolve(mixed $a, mixed $v, mixed $mode = 'full'): mixed
    {
        return Registry::routine('signal.convolve', [$a, $v, $mode]);
    }

    /**
     * N-D cross-correlation of two arrays, modes full/same/valid (scipy.signal.correlate; real).
     *
     * scipy.signal.correlate
     */
    public static function correlate(mixed $in1, mixed $in2, mixed $mode = 'full', mixed $method = 'auto'): mixed
    {
        return Registry::routine('signal.correlate', [$in1, $in2, $mode, $method]);
    }

    /**
     * Remove a constant or piecewise-linear least-squares trend along an axis (scipy.signal.detrend).
     *
     * scipy.signal.detrend
     */
    public static function detrend(mixed $data, mixed $axis = -1, mixed $type = 'linear', mixed $bp = 0, mixed $overwriteData = false): mixed
    {
        return Registry::routine('signal.detrend', [$data, $axis, $type, $bp, $overwriteData]);
    }

    /**
     * N-D convolution of two arrays, modes full/same/valid (scipy.signal.fftconvolve; real).
     *
     * scipy.signal.fftconvolve
     */
    public static function fftconvolve(mixed $in1, mixed $in2, mixed $mode = 'full', mixed $axes = null): mixed
    {
        return Registry::routine('signal.fftconvolve', [$in1, $in2, $mode, $axes]);
    }

    /**
     * Zero-phase forward-backward IIR filtering with odd padding (scipy.signal.filtfilt; 1-D).
     *
     * scipy.signal.filtfilt
     */
    public static function filtfilt(mixed $b, mixed $a, mixed $x, mixed $axis = -1, mixed $padtype = 'odd', mixed $padlen = null, mixed $method = 'pad', mixed $irlen = null): mixed
    {
        return Registry::routine('signal.filtfilt', [$b, $a, $x, $axis, $padtype, $padlen, $method, $irlen]);
    }

    /**
     * Frequency response of a digital filter (scipy.signal.freqz).
     *
     * scipy.signal.freqz
     *
     * @return mixed one array, or an array keyed by w, h when several results are requested
     */
    public static function freqz(mixed $b, mixed $a = 1, mixed $worN = 512, mixed $whole = false): mixed
    {
        return Registry::routine('signal.freqz', [$b, $a, $worN, $whole]);
    }

    /**
     * Gaussian-modulated sinusoid, in-phase component (scipy.signal.gausspulse).
     *
     * scipy.signal.gausspulse
     */
    public static function gausspulse(mixed $t, mixed $fc = 1000, mixed $bw = 0.5, mixed $bwr = -6): mixed
    {
        return Registry::routine('signal.gausspulse', [$t, $fc, $bw, $bwr]);
    }

    /**
     * Filter a 1-D signal with an IIR or FIR filter (scipy.signal.lfilter; zero initial state).
     *
     * scipy.signal.lfilter
     */
    public static function lfilter(mixed $b, mixed $a, mixed $x): mixed
    {
        return Registry::routine('signal.lfilter', [$b, $a, $x]);
    }

    /**
     * Steady-state step-response initial conditions for lfilter (scipy.signal.lfilter_zi).
     *
     * scipy.signal.lfilter_zi
     */
    public static function lfilterZi(mixed $b, mixed $a): mixed
    {
        return Registry::routine('signal.lfilter_zi', [$b, $a]);
    }

    /**
     * Normalize a transfer-function representation (scipy.signal.normalize).
     *
     * scipy.signal.normalize
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function normalize(mixed $b, mixed $a): mixed
    {
        return Registry::routine('signal.normalize', [$b, $a]);
    }

    /**
     * N-D convolution by the overlap-add method, modes full/same/valid (scipy.signal.oaconvolve; real).
     *
     * scipy.signal.oaconvolve
     */
    public static function oaconvolve(mixed $in1, mixed $in2, mixed $mode = 'full', mixed $axes = null): mixed
    {
        return Registry::routine('signal.oaconvolve', [$in1, $in2, $mode, $axes]);
    }

    /**
     * Savitzky-Golay filter coefficients (scipy.signal.savgol_coeffs).
     *
     * scipy.signal.savgol_coeffs
     */
    public static function savgolCoeffs(mixed $windowLength, mixed $polyorder, mixed $deriv = 0, mixed $delta = 1.0, mixed $pos = null, mixed $use = 'conv'): mixed
    {
        return Registry::routine('signal.savgol_coeffs', [$windowLength, $polyorder, $deriv, $delta, $pos, $use]);
    }

    /**
     * Apply a Savitzky-Golay filter to a 1-D signal (scipy.signal.savgol_filter).
     *
     * scipy.signal.savgol_filter
     */
    public static function savgolFilter(mixed $x, mixed $windowLength, mixed $polyorder, mixed $deriv = 0, mixed $delta = 1.0, mixed $axis = -1, mixed $mode = 'interp', mixed $cval = 0.0): mixed
    {
        return Registry::routine('signal.savgol_filter', [$x, $windowLength, $polyorder, $deriv, $delta, $axis, $mode, $cval]);
    }

    /**
     * Sawtooth/triangle wave of period 2pi with the given rising width (scipy.signal.sawtooth).
     *
     * scipy.signal.sawtooth
     */
    public static function sawtooth(mixed $t, mixed $width = 1): mixed
    {
        return Registry::routine('signal.sawtooth', [$t, $width]);
    }

    /**
     * Transfer function (b, a) from a second-order-sections cascade (scipy.signal.sos2tf).
     *
     * scipy.signal.sos2tf
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function sos2tf(mixed $sos): mixed
    {
        return Registry::routine('signal.sos2tf', [$sos]);
    }

    /**
     * Filter a 1-D signal through a cascade of second-order sections (scipy.signal.sosfilt; zero initial state).
     *
     * scipy.signal.sosfilt
     */
    public static function sosfilt(mixed $sos, mixed $x, mixed $axis = -1, mixed $zi = null): mixed
    {
        return Registry::routine('signal.sosfilt', [$sos, $x, $axis, $zi]);
    }

    /**
     * Per-section steady-state initial conditions for sosfilt (scipy.signal.sosfilt_zi).
     *
     * scipy.signal.sosfilt_zi
     */
    public static function sosfiltZi(mixed $sos): mixed
    {
        return Registry::routine('signal.sosfilt_zi', [$sos]);
    }

    /**
     * Zero-phase forward-backward SOS filtering with odd padding (scipy.signal.sosfiltfilt; 1-D).
     *
     * scipy.signal.sosfiltfilt
     */
    public static function sosfiltfilt(mixed $sos, mixed $x, mixed $axis = -1, mixed $padtype = 'odd', mixed $padlen = null): mixed
    {
        return Registry::routine('signal.sosfiltfilt', [$sos, $x, $axis, $padtype, $padlen]);
    }

    /**
     * Square-wave of period 2pi with the given duty cycle (scipy.signal.square).
     *
     * scipy.signal.square
     */
    public static function square(mixed $t, mixed $duty = 0.5): mixed
    {
        return Registry::routine('signal.square', [$t, $duty]);
    }

    /**
     * Zeros, poles and gain from transfer-function coefficients (scipy.signal.tf2zpk).
     *
     * scipy.signal.tf2zpk
     *
     * @return mixed one array, or an array keyed by z, p, k when several results are requested
     */
    public static function tf2zpk(mixed $b, mixed $a): mixed
    {
        return Registry::routine('signal.tf2zpk', [$b, $a]);
    }

    /**
     * Unit impulse: zeros with a single 1 at idx (scipy.signal.unit_impulse).
     *
     * scipy.signal.unit_impulse
     */
    public static function unitImpulse(mixed $shape, mixed $idx = null): mixed
    {
        return Registry::routine('signal.unit_impulse', [$shape, $idx]);
    }

    /**
     * Transfer-function (b, a) from zeros, poles and gain (scipy.signal.zpk2tf).
     *
     * scipy.signal.zpk2tf
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function zpk2tf(mixed $z, mixed $p, mixed $k): mixed
    {
        return Registry::routine('signal.zpk2tf', [$z, $p, $k]);
    }
}
