<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * scipy.signal: 1-D convolve (full/same/valid) and lfilter over real float64 sequences.
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\Signal.
 */
final class Signal
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'bilinear' => 'bilinear',
    'butter' => 'butter',
    'cheby1' => 'cheby1',
    'cheby2' => 'cheby2',
    'chirp' => 'chirp',
    'coherence' => 'coherence',
    'convolve' => 'convolve',
    'correlate' => 'correlate',
    'correlation_lags' => 'correlationLags',
    'csd' => 'csd',
    'detrend' => 'detrend',
    'fftconvolve' => 'fftconvolve',
    'filtfilt' => 'filtfilt',
    'firwin' => 'firwin',
    'freqs' => 'freqs',
    'freqs_zpk' => 'freqsZpk',
    'freqz' => 'freqz',
    'freqz_zpk' => 'freqzZpk',
    'gausspulse' => 'gausspulse',
    'group_delay' => 'groupDelay',
    'hilbert' => 'hilbert',
    'hilbert2' => 'hilbert2',
    'kaiser_atten' => 'kaiserAtten',
    'kaiser_beta' => 'kaiserBeta',
    'kaiserord' => 'kaiserord',
    'lfilter' => 'lfilter',
    'lfilter_zi' => 'lfilterZi',
    'lp2bp' => 'lp2bp',
    'lp2bs' => 'lp2bs',
    'lp2hp' => 'lp2hp',
    'lp2lp' => 'lp2lp',
    'normalize' => 'normalize',
    'oaconvolve' => 'oaconvolve',
    'periodogram' => 'periodogram',
    'resample' => 'resample',
    'savgol_coeffs' => 'savgolCoeffs',
    'savgol_filter' => 'savgolFilter',
    'sawtooth' => 'sawtooth',
    'sos2tf' => 'sos2tf',
    'sosfilt' => 'sosfilt',
    'sosfilt_zi' => 'sosfiltZi',
    'sosfiltfilt' => 'sosfiltfilt',
    'sosfreqz' => 'sosfreqz',
    'spectrogram' => 'spectrogram',
    'square' => 'square',
    'tf2zpk' => 'tf2zpk',
    'unit_impulse' => 'unitImpulse',
    'welch' => 'welch',
    'zpk2tf' => 'zpk2tf',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: Signal::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("Signal::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * Bilinear transform of an analog filter to a digital filter (scipy.signal.bilinear).
     *
     * scipy.signal.bilinear
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function bilinear(mixed $b, mixed $a, mixed $fs = 1.0): mixed
    {
        return Registry::routine('signal.bilinear', [$b, $a, $fs]);
    }

    /**
     * Butterworth IIR filter design, digital lowpass/highpass, output 'ba' (scipy.signal.butter).
     *
     * scipy.signal.butter
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function butter(mixed $N, mixed $Wn, mixed $btype = 'low', mixed $analog = false, mixed $output = 'ba', mixed $fs = null): mixed
    {
        return Registry::routine('signal.butter', [$N, $Wn, $btype, $analog, $output, $fs]);
    }

    /**
     * Chebyshev type I IIR filter design, digital lowpass/highpass, output 'ba' (scipy.signal.cheby1).
     *
     * scipy.signal.cheby1
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function cheby1(mixed $N, mixed $rp, mixed $Wn, mixed $btype = 'low', mixed $analog = false, mixed $output = 'ba', mixed $fs = null): mixed
    {
        return Registry::routine('signal.cheby1', [$N, $rp, $Wn, $btype, $analog, $output, $fs]);
    }

    /**
     * Chebyshev type II IIR filter design, digital lowpass/highpass, output 'ba' (scipy.signal.cheby2).
     *
     * scipy.signal.cheby2
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function cheby2(mixed $N, mixed $rs, mixed $Wn, mixed $btype = 'low', mixed $analog = false, mixed $output = 'ba', mixed $fs = null): mixed
    {
        return Registry::routine('signal.cheby2', [$N, $rs, $Wn, $btype, $analog, $output, $fs]);
    }

    /**
     * Frequency-swept cosine (linear/quadratic/logarithmic/hyperbolic) (scipy.signal.chirp).
     *
     * scipy.signal.chirp
     */
    public static function chirp(mixed $t, mixed $f0, mixed $t1, mixed $f1, mixed $method = 'linear', mixed $phi = 0, mixed $vertexZero = true): mixed
    {
        return Registry::routine('signal.chirp', [$t, $f0, $t1, $f1, $method, $phi, $vertexZero]);
    }

    /**
     * Magnitude-squared coherence by Welch's method (scipy.signal.coherence).
     *
     * scipy.signal.coherence
     *
     * @return mixed one array, or an array keyed by f, Cxy when several results are requested
     */
    public static function coherence(mixed $x, mixed $y, mixed $fs = 1.0, mixed $window = 'hann', mixed $nperseg = null, mixed $noverlap = null, mixed $nfft = null, mixed $detrend = 'constant', mixed $axis = -1): mixed
    {
        return Registry::routine('signal.coherence', [$x, $y, $fs, $window, $nperseg, $noverlap, $nfft, $detrend, $axis]);
    }

    /**
     * 1-D convolution of two sequences, modes full/same/valid (scipy.signal.convolve).
     *
     * scipy.signal.convolve
     */
    public static function convolve(mixed $a, mixed $v, mixed $mode = 'full'): mixed
    {
        return Registry::routine('signal.convolve', [$a, $v, $mode]);
    }

    /**
     * N-D cross-correlation of two arrays, modes full/same/valid (scipy.signal.correlate; real).
     *
     * scipy.signal.correlate
     */
    public static function correlate(mixed $in1, mixed $in2, mixed $mode = 'full', mixed $method = 'auto'): mixed
    {
        return Registry::routine('signal.correlate', [$in1, $in2, $mode, $method]);
    }

    /**
     * Lag indices for the output of signal.correlate (scipy.signal.correlation_lags).
     *
     * scipy.signal.correlation_lags
     */
    public static function correlationLags(mixed $in1Len, mixed $in2Len, mixed $mode = 'full'): mixed
    {
        return Registry::routine('signal.correlation_lags', [$in1Len, $in2Len, $mode]);
    }

    /**
     * Cross power spectral density by Welch's method (scipy.signal.csd).
     *
     * scipy.signal.csd
     *
     * @return mixed one array, or an array keyed by f, Pxy when several results are requested
     */
    public static function csd(mixed $x, mixed $y, mixed $fs = 1.0, mixed $window = 'hann', mixed $nperseg = null, mixed $noverlap = null, mixed $nfft = null, mixed $detrend = 'constant', mixed $returnOnesided = true, mixed $scaling = 'density', mixed $axis = -1, mixed $average = 'mean'): mixed
    {
        return Registry::routine('signal.csd', [$x, $y, $fs, $window, $nperseg, $noverlap, $nfft, $detrend, $returnOnesided, $scaling, $axis, $average]);
    }

    /**
     * Remove a constant or piecewise-linear least-squares trend along an axis (scipy.signal.detrend).
     *
     * scipy.signal.detrend
     */
    public static function detrend(mixed $data, mixed $axis = -1, mixed $type = 'linear', mixed $bp = 0, mixed $overwriteData = false): mixed
    {
        return Registry::routine('signal.detrend', [$data, $axis, $type, $bp, $overwriteData]);
    }

    /**
     * N-D convolution of two arrays, modes full/same/valid (scipy.signal.fftconvolve; real).
     *
     * scipy.signal.fftconvolve
     */
    public static function fftconvolve(mixed $in1, mixed $in2, mixed $mode = 'full', mixed $axes = null): mixed
    {
        return Registry::routine('signal.fftconvolve', [$in1, $in2, $mode, $axes]);
    }

    /**
     * Zero-phase forward-backward IIR filtering with odd padding (scipy.signal.filtfilt; 1-D).
     *
     * scipy.signal.filtfilt
     */
    public static function filtfilt(mixed $b, mixed $a, mixed $x, mixed $axis = -1, mixed $padtype = 'odd', mixed $padlen = null, mixed $method = 'pad', mixed $irlen = null): mixed
    {
        return Registry::routine('signal.filtfilt', [$b, $a, $x, $axis, $padtype, $padlen, $method, $irlen]);
    }

    /**
     * FIR filter design by the window method (scipy.signal.firwin).
     *
     * scipy.signal.firwin
     */
    public static function firwin(mixed $numtaps, mixed $cutoff, mixed $window = 'hamming', mixed $passZero = true, mixed $scale = true, mixed $fs = null): mixed
    {
        return Registry::routine('signal.firwin', [$numtaps, $cutoff, $window, $passZero, $scale, $fs]);
    }

    /**
     * Analog filter frequency response at the given frequencies (scipy.signal.freqs).
     *
     * scipy.signal.freqs
     *
     * @return mixed one array, or an array keyed by w, h when several results are requested
     */
    public static function freqs(mixed $b, mixed $a, mixed $worN): mixed
    {
        return Registry::routine('signal.freqs', [$b, $a, $worN]);
    }

    /**
     * Analog zpk frequency response at the given frequencies (scipy.signal.freqs_zpk).
     *
     * scipy.signal.freqs_zpk
     *
     * @return mixed one array, or an array keyed by w, h when several results are requested
     */
    public static function freqsZpk(mixed $z, mixed $p, mixed $k, mixed $worN): mixed
    {
        return Registry::routine('signal.freqs_zpk', [$z, $p, $k, $worN]);
    }

    /**
     * Frequency response of a digital filter (scipy.signal.freqz).
     *
     * scipy.signal.freqz
     *
     * @return mixed one array, or an array keyed by w, h when several results are requested
     */
    public static function freqz(mixed $b, mixed $a = 1, mixed $worN = 512, mixed $whole = false): mixed
    {
        return Registry::routine('signal.freqz', [$b, $a, $worN, $whole]);
    }

    /**
     * Digital zpk frequency response on a linear grid (scipy.signal.freqz_zpk).
     *
     * scipy.signal.freqz_zpk
     *
     * @return mixed one array, or an array keyed by w, h when several results are requested
     */
    public static function freqzZpk(mixed $z, mixed $p, mixed $k, mixed $worN = 512, mixed $whole = false): mixed
    {
        return Registry::routine('signal.freqz_zpk', [$z, $p, $k, $worN, $whole]);
    }

    /**
     * Gaussian-modulated sinusoid, in-phase component (scipy.signal.gausspulse).
     *
     * scipy.signal.gausspulse
     */
    public static function gausspulse(mixed $t, mixed $fc = 1000, mixed $bw = 0.5, mixed $bwr = -6): mixed
    {
        return Registry::routine('signal.gausspulse', [$t, $fc, $bw, $bwr]);
    }

    /**
     * Group delay of a digital filter (scipy.signal.group_delay).
     *
     * scipy.signal.group_delay
     *
     * @return mixed one array, or an array keyed by w, gd when several results are requested
     */
    public static function groupDelay(mixed $b, mixed $a, mixed $w = 512, mixed $whole = false): mixed
    {
        return Registry::routine('signal.group_delay', [$b, $a, $w, $whole]);
    }

    /**
     * Analytic signal of a real sequence via the FFT (scipy.signal.hilbert).
     *
     * scipy.signal.hilbert
     */
    public static function hilbert(mixed $x, mixed $N = null): mixed
    {
        return Registry::routine('signal.hilbert', [$x, $N]);
    }

    /**
     * 2-D analytic signal of a real matrix via the 2-D FFT (scipy.signal.hilbert2).
     *
     * scipy.signal.hilbert2
     */
    public static function hilbert2(mixed $x, mixed $N = null): mixed
    {
        return Registry::routine('signal.hilbert2', [$x, $N]);
    }

    /**
     * Kaiser-window attenuation (dB) for a filter length and transition width (scipy.signal.kaiser_atten).
     *
     * scipy.signal.kaiser_atten
     */
    public static function kaiserAtten(mixed $numtaps, mixed $width): mixed
    {
        return Registry::routine('signal.kaiser_atten', [$numtaps, $width]);
    }

    /**
     * Kaiser-window shape beta for a given attenuation (scipy.signal.kaiser_beta).
     *
     * scipy.signal.kaiser_beta
     */
    public static function kaiserBeta(mixed $a): mixed
    {
        return Registry::routine('signal.kaiser_beta', [$a]);
    }

    /**
     * Kaiser filter length and beta for a ripple and transition width (scipy.signal.kaiserord).
     *
     * scipy.signal.kaiserord
     *
     * @return mixed one array, or an array keyed by numtaps, beta when several results are requested
     */
    public static function kaiserord(mixed $ripple, mixed $width): mixed
    {
        return Registry::routine('signal.kaiserord', [$ripple, $width]);
    }

    /**
     * Filter a 1-D signal with an IIR or FIR filter (scipy.signal.lfilter; zero initial state).
     *
     * scipy.signal.lfilter
     */
    public static function lfilter(mixed $b, mixed $a, mixed $x): mixed
    {
        return Registry::routine('signal.lfilter', [$b, $a, $x]);
    }

    /**
     * Steady-state step-response initial conditions for lfilter (scipy.signal.lfilter_zi).
     *
     * scipy.signal.lfilter_zi
     */
    public static function lfilterZi(mixed $b, mixed $a): mixed
    {
        return Registry::routine('signal.lfilter_zi', [$b, $a]);
    }

    /**
     * Transform a lowpass analog prototype to bandpass (scipy.signal.lp2bp).
     *
     * scipy.signal.lp2bp
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function lp2bp(mixed $b, mixed $a, mixed $wo = 1.0, mixed $bw = 1.0): mixed
    {
        return Registry::routine('signal.lp2bp', [$b, $a, $wo, $bw]);
    }

    /**
     * Transform a lowpass analog prototype to bandstop (scipy.signal.lp2bs).
     *
     * scipy.signal.lp2bs
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function lp2bs(mixed $b, mixed $a, mixed $wo = 1.0, mixed $bw = 1.0): mixed
    {
        return Registry::routine('signal.lp2bs', [$b, $a, $wo, $bw]);
    }

    /**
     * Transform a lowpass analog prototype to highpass (scipy.signal.lp2hp).
     *
     * scipy.signal.lp2hp
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function lp2hp(mixed $b, mixed $a, mixed $wo = 1.0): mixed
    {
        return Registry::routine('signal.lp2hp', [$b, $a, $wo]);
    }

    /**
     * Transform a lowpass analog prototype to a different cutoff (scipy.signal.lp2lp).
     *
     * scipy.signal.lp2lp
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function lp2lp(mixed $b, mixed $a, mixed $wo = 1.0): mixed
    {
        return Registry::routine('signal.lp2lp', [$b, $a, $wo]);
    }

    /**
     * Normalize a transfer-function representation (scipy.signal.normalize).
     *
     * scipy.signal.normalize
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function normalize(mixed $b, mixed $a): mixed
    {
        return Registry::routine('signal.normalize', [$b, $a]);
    }

    /**
     * N-D convolution by the overlap-add method, modes full/same/valid (scipy.signal.oaconvolve; real).
     *
     * scipy.signal.oaconvolve
     */
    public static function oaconvolve(mixed $in1, mixed $in2, mixed $mode = 'full', mixed $axes = null): mixed
    {
        return Registry::routine('signal.oaconvolve', [$in1, $in2, $mode, $axes]);
    }

    /**
     * Power spectral density estimate from a single segment (scipy.signal.periodogram).
     *
     * scipy.signal.periodogram
     *
     * @return mixed one array, or an array keyed by f, Pxx when several results are requested
     */
    public static function periodogram(mixed $x, mixed $fs = 1.0, mixed $window = 'boxcar', mixed $nfft = null, mixed $detrend = 'constant', mixed $returnOnesided = true, mixed $scaling = 'density'): mixed
    {
        return Registry::routine('signal.periodogram', [$x, $fs, $window, $nfft, $detrend, $returnOnesided, $scaling]);
    }

    /**
     * Resample a real signal to num samples via the FFT (scipy.signal.resample; window=None).
     *
     * scipy.signal.resample
     */
    public static function resample(mixed $x, mixed $num, mixed $t = null, mixed $axis = 0, mixed $window = null, mixed $domain = 'time'): mixed
    {
        return Registry::routine('signal.resample', [$x, $num, $t, $axis, $window, $domain]);
    }

    /**
     * Savitzky-Golay filter coefficients (scipy.signal.savgol_coeffs).
     *
     * scipy.signal.savgol_coeffs
     */
    public static function savgolCoeffs(mixed $windowLength, mixed $polyorder, mixed $deriv = 0, mixed $delta = 1.0, mixed $pos = null, mixed $use = 'conv'): mixed
    {
        return Registry::routine('signal.savgol_coeffs', [$windowLength, $polyorder, $deriv, $delta, $pos, $use]);
    }

    /**
     * Apply a Savitzky-Golay filter to a 1-D signal (scipy.signal.savgol_filter).
     *
     * scipy.signal.savgol_filter
     */
    public static function savgolFilter(mixed $x, mixed $windowLength, mixed $polyorder, mixed $deriv = 0, mixed $delta = 1.0, mixed $axis = -1, mixed $mode = 'interp', mixed $cval = 0.0): mixed
    {
        return Registry::routine('signal.savgol_filter', [$x, $windowLength, $polyorder, $deriv, $delta, $axis, $mode, $cval]);
    }

    /**
     * Sawtooth/triangle wave of period 2pi with the given rising width (scipy.signal.sawtooth).
     *
     * scipy.signal.sawtooth
     */
    public static function sawtooth(mixed $t, mixed $width = 1): mixed
    {
        return Registry::routine('signal.sawtooth', [$t, $width]);
    }

    /**
     * Transfer function (b, a) from a second-order-sections cascade (scipy.signal.sos2tf).
     *
     * scipy.signal.sos2tf
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function sos2tf(mixed $sos): mixed
    {
        return Registry::routine('signal.sos2tf', [$sos]);
    }

    /**
     * Filter a 1-D signal through a cascade of second-order sections (scipy.signal.sosfilt; zero initial state).
     *
     * scipy.signal.sosfilt
     */
    public static function sosfilt(mixed $sos, mixed $x, mixed $axis = -1, mixed $zi = null): mixed
    {
        return Registry::routine('signal.sosfilt', [$sos, $x, $axis, $zi]);
    }

    /**
     * Per-section steady-state initial conditions for sosfilt (scipy.signal.sosfilt_zi).
     *
     * scipy.signal.sosfilt_zi
     */
    public static function sosfiltZi(mixed $sos): mixed
    {
        return Registry::routine('signal.sosfilt_zi', [$sos]);
    }

    /**
     * Zero-phase forward-backward SOS filtering with odd padding (scipy.signal.sosfiltfilt; 1-D).
     *
     * scipy.signal.sosfiltfilt
     */
    public static function sosfiltfilt(mixed $sos, mixed $x, mixed $axis = -1, mixed $padtype = 'odd', mixed $padlen = null): mixed
    {
        return Registry::routine('signal.sosfiltfilt', [$sos, $x, $axis, $padtype, $padlen]);
    }

    /**
     * Frequency response of a second-order-sections cascade (scipy.signal.sosfreqz).
     *
     * scipy.signal.sosfreqz
     *
     * @return mixed one array, or an array keyed by w, h when several results are requested
     */
    public static function sosfreqz(mixed $sos, mixed $worN = 512, mixed $whole = false): mixed
    {
        return Registry::routine('signal.sosfreqz', [$sos, $worN, $whole]);
    }

    /**
     * Spectrogram (per-segment PSD over time) by Welch's segmenting; default window periodic Tukey(0.25) (scipy.signal.spectrogram, mode='psd').
     *
     * scipy.signal.spectrogram
     *
     * @return mixed one array, or an array keyed by f, t, Sxx when several results are requested
     */
    public static function spectrogram(mixed $x, mixed $fs = 1.0, mixed $window = 'tukey', mixed $nperseg = null, mixed $noverlap = null, mixed $nfft = null, mixed $detrend = 'constant', mixed $returnOnesided = true, mixed $scaling = 'density', mixed $axis = -1, mixed $mode = 'psd'): mixed
    {
        return Registry::routine('signal.spectrogram', [$x, $fs, $window, $nperseg, $noverlap, $nfft, $detrend, $returnOnesided, $scaling, $axis, $mode]);
    }

    /**
     * Square-wave of period 2pi with the given duty cycle (scipy.signal.square).
     *
     * scipy.signal.square
     */
    public static function square(mixed $t, mixed $duty = 0.5): mixed
    {
        return Registry::routine('signal.square', [$t, $duty]);
    }

    /**
     * Zeros, poles and gain from transfer-function coefficients (scipy.signal.tf2zpk).
     *
     * scipy.signal.tf2zpk
     *
     * @return mixed one array, or an array keyed by z, p, k when several results are requested
     */
    public static function tf2zpk(mixed $b, mixed $a): mixed
    {
        return Registry::routine('signal.tf2zpk', [$b, $a]);
    }

    /**
     * Unit impulse: zeros with a single 1 at idx (scipy.signal.unit_impulse).
     *
     * scipy.signal.unit_impulse
     */
    public static function unitImpulse(mixed $shape, mixed $idx = null): mixed
    {
        return Registry::routine('signal.unit_impulse', [$shape, $idx]);
    }

    /**
     * Welch's averaged-periodogram power spectral density estimate (scipy.signal.welch).
     *
     * scipy.signal.welch
     *
     * @return mixed one array, or an array keyed by f, Pxx when several results are requested
     */
    public static function welch(mixed $x, mixed $fs = 1.0, mixed $window = 'hann', mixed $nperseg = null, mixed $noverlap = null, mixed $nfft = null, mixed $detrend = 'constant', mixed $returnOnesided = true, mixed $scaling = 'density', mixed $axis = -1, mixed $average = 'mean'): mixed
    {
        return Registry::routine('signal.welch', [$x, $fs, $window, $nperseg, $noverlap, $nfft, $detrend, $returnOnesided, $scaling, $axis, $average]);
    }

    /**
     * Transfer-function (b, a) from zeros, poles and gain (scipy.signal.zpk2tf).
     *
     * scipy.signal.zpk2tf
     *
     * @return mixed one array, or an array keyed by b, a when several results are requested
     */
    public static function zpk2tf(mixed $z, mixed $p, mixed $k): mixed
    {
        return Registry::routine('signal.zpk2tf', [$z, $p, $k]);
    }
}
