<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * scipy.sparse constructors: csr/csc/coo/dia _array and _matrix from a dense matrix, returning the storage arrays (data, indices/indptr or row/col or offsets, shape) as scipy lays them out.
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\Sparse.
 */
final class Sparse
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'coo_array' => 'cooArray',
    'coo_matrix' => 'cooMatrix',
    'csc_array' => 'cscArray',
    'csc_matrix' => 'cscMatrix',
    'csr_array' => 'csrArray',
    'csr_matrix' => 'csrMatrix',
    'dia_array' => 'diaArray',
    'dia_matrix' => 'diaMatrix',
    'hstack' => 'hstack',
    'vstack' => 'vstack',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: Sparse::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("Sparse::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * Coordinate (triplet) storage of a dense matrix (scipy.sparse.coo_array).
     *
     * scipy.sparse.coo_array
     *
     * @return mixed one array, or an array keyed by data, row, col, shape when several results are requested
     */
    public static function cooArray(mixed $A): mixed
    {
        return Registry::routine('sparse.coo_array', [$A]);
    }

    /**
     * Coordinate (triplet) storage of a dense matrix (scipy.sparse.coo_matrix).
     *
     * scipy.sparse.coo_matrix
     *
     * @return mixed one array, or an array keyed by data, row, col, shape when several results are requested
     */
    public static function cooMatrix(mixed $A): mixed
    {
        return Registry::routine('sparse.coo_matrix', [$A]);
    }

    /**
     * Compressed sparse column storage of a dense matrix (scipy.sparse.csc_array).
     *
     * scipy.sparse.csc_array
     *
     * @return mixed one array, or an array keyed by data, indices, indptr, shape when several results are requested
     */
    public static function cscArray(mixed $A): mixed
    {
        return Registry::routine('sparse.csc_array', [$A]);
    }

    /**
     * Compressed sparse column storage of a dense matrix (scipy.sparse.csc_matrix).
     *
     * scipy.sparse.csc_matrix
     *
     * @return mixed one array, or an array keyed by data, indices, indptr, shape when several results are requested
     */
    public static function cscMatrix(mixed $A): mixed
    {
        return Registry::routine('sparse.csc_matrix', [$A]);
    }

    /**
     * Compressed sparse row storage of a dense matrix (scipy.sparse.csr_array).
     *
     * scipy.sparse.csr_array
     *
     * @return mixed one array, or an array keyed by data, indices, indptr, shape when several results are requested
     */
    public static function csrArray(mixed $A): mixed
    {
        return Registry::routine('sparse.csr_array', [$A]);
    }

    /**
     * Compressed sparse row storage of a dense matrix (scipy.sparse.csr_matrix).
     *
     * scipy.sparse.csr_matrix
     *
     * @return mixed one array, or an array keyed by data, indices, indptr, shape when several results are requested
     */
    public static function csrMatrix(mixed $A): mixed
    {
        return Registry::routine('sparse.csr_matrix', [$A]);
    }

    /**
     * Diagonal storage of a dense matrix (scipy.sparse.dia_array).
     *
     * scipy.sparse.dia_array
     *
     * @return mixed one array, or an array keyed by data, offsets, shape when several results are requested
     */
    public static function diaArray(mixed $A): mixed
    {
        return Registry::routine('sparse.dia_array', [$A]);
    }

    /**
     * Diagonal storage of a dense matrix (scipy.sparse.dia_matrix).
     *
     * scipy.sparse.dia_matrix
     *
     * @return mixed one array, or an array keyed by data, offsets, shape when several results are requested
     */
    public static function diaMatrix(mixed $A): mixed
    {
        return Registry::routine('sparse.dia_matrix', [$A]);
    }

    /**
     * Stack sparse blocks horizontally, as CSR storage (scipy.sparse.hstack).
     *
     * scipy.sparse.hstack: the positional arguments are numpy's *blocks.
     */
    public static function hstack(mixed ...$blocks): mixed
    {
        return Registry::routineVariadic('sparse.hstack', $blocks);
    }

    /**
     * Stack sparse blocks vertically, as CSR storage (scipy.sparse.vstack).
     *
     * scipy.sparse.vstack: the positional arguments are numpy's *blocks.
     */
    public static function vstack(mixed ...$blocks): mixed
    {
        return Registry::routineVariadic('sparse.vstack', $blocks);
    }
}
