<?php

// Generated by tools/parity/gen-facades.php from libtessero's function registry. Do not edit.

declare(strict_types=1);

namespace Tessero;

use Tessero\Native\Registry;

/**
 * scipy.sparse.linalg: direct sparse solves, matrix norms and structure queries, shared by both backends through the kernel.
 *
 * Names are the SciPy/NumPy names in camelCase (log_ndtr -> logNdtr); apply() also takes the original names.
 * The native extension provides the same class as Tessero\Ext\SparseLinalg.
 */
final class SparseLinalg
{
    /** SciPy/NumPy name => method name */
    public const FUNCTIONS = [
    'expm' => 'expm',
    'inv' => 'inv',
    'is_sptriangular' => 'isSptriangular',
    'matrix_power' => 'matrixPower',
    'norm' => 'norm',
    'spbandwidth' => 'spbandwidth',
    'spsolve' => 'spsolve',
    'spsolve_triangular' => 'spsolveTriangular',
    ];

    private function __construct()
    {
    }

    /**
     * Call a function by its SciPy/NumPy name: SparseLinalg::apply('log_ndtr', $x).
     */
    public static function apply(string $name, mixed ...$args): mixed
    {
        if (! isset(self::FUNCTIONS[$name])) {
            throw new \ValueError("SparseLinalg::apply(): unknown function '{$name}'");
        }

        return self::{self::FUNCTIONS[$name]}(...$args);
    }

    /**
     * Matrix exponential of a sparse matrix (scipy.sparse.linalg.expm).
     *
     * scipy.splinalg.expm
     */
    public static function expm(mixed $A): mixed
    {
        return Registry::routine('splinalg.expm', [$A]);
    }

    /**
     * Inverse of a square sparse matrix, returned dense (scipy.sparse.linalg.inv).
     *
     * scipy.splinalg.inv
     */
    public static function inv(mixed $A): mixed
    {
        return Registry::routine('splinalg.inv', [$A]);
    }

    /**
     * Whether a sparse matrix is lower/upper triangular (scipy.sparse.linalg.is_sptriangular).
     *
     * scipy.splinalg.is_sptriangular
     *
     * @return mixed one array, or an array keyed by lower, upper when several results are requested
     */
    public static function isSptriangular(mixed $A): mixed
    {
        return Registry::routine('splinalg.is_sptriangular', [$A]);
    }

    /**
     * Integer matrix power of a square sparse matrix (scipy.sparse.linalg.matrix_power).
     *
     * scipy.splinalg.matrix_power
     */
    public static function matrixPower(mixed $A, mixed $power): mixed
    {
        return Registry::routine('splinalg.matrix_power', [$A, $power]);
    }

    /**
     * Norm of a sparse matrix (scipy.sparse.linalg.norm).
     *
     * scipy.splinalg.norm
     */
    public static function norm(mixed $x, mixed $ord = null, mixed $axis = null): mixed
    {
        return Registry::routine('splinalg.norm', [$x, $ord, $axis]);
    }

    /**
     * Lower and upper bandwidth of a sparse matrix (scipy.sparse.linalg.spbandwidth).
     *
     * scipy.splinalg.spbandwidth
     *
     * @return mixed one array, or an array keyed by lower, upper when several results are requested
     */
    public static function spbandwidth(mixed $A): mixed
    {
        return Registry::routine('splinalg.spbandwidth', [$A]);
    }

    /**
     * Solve a sparse linear system A x = b (scipy.sparse.linalg.spsolve).
     *
     * scipy.splinalg.spsolve
     */
    public static function spsolve(mixed $A, mixed $b, mixed $permcSpec = null, mixed $useUmfpack = true): mixed
    {
        return Registry::routine('splinalg.spsolve', [$A, $b, $permcSpec, $useUmfpack]);
    }

    /**
     * Solve a triangular sparse system (scipy.sparse.linalg.spsolve_triangular).
     *
     * scipy.splinalg.spsolve_triangular
     */
    public static function spsolveTriangular(mixed $A, mixed $b, mixed $lower = true, mixed $overwriteA = false, mixed $overwriteB = false, mixed $unitDiagonal = false): mixed
    {
        return Registry::routine('splinalg.spsolve_triangular', [$A, $b, $lower, $overwriteA, $overwriteB, $unitDiagonal]);
    }
}
