<?php

/**
 * Audit coverage language (prompts/numpy-scipy-parity-program.md section 3.5).
 *
 *   php tools/parity/claims-check.php
 *
 * Scans README.md, laravel/README.md and docs/**.md (pages generated by a tool are skipped: they carry a
 * "generated by" marker in their first line) for
 *  - claim phrases: "NumPy for PHP", "SciPy equivalent", "drop-in", "portable NumPy", and "complete" near
 *    NumPy/SciPy, unless negated ("not a drop-in ...");
 *  - percentages in coverage sentences (cover, implement, support, parity, symbols, verified, in scope): each must
 *    be one of the percentages the generated pages state (docs/project/_generated/metrics.md, usage.md and the
 *    coverage page), so a typed figure cannot drift from the measured one.
 * Exit status 1 with one line per finding.
 */

declare(strict_types=1);

$root = dirname(__DIR__, 2);
$files = [$root . '/README.md', $root . '/laravel/README.md'];
// scandir rather than RecursiveDirectoryIterator: the latter lists nothing on some FUSE file systems
$walk = static function (string $dir) use (&$walk, &$files): void {
    foreach (scandir($dir) ?: [] as $e) {
        if ($e === '.' || $e === '..') {
            continue;
        }
        $p = $dir . '/' . $e;
        if (is_dir($p)) {
            $walk($p);
        } elseif (str_ends_with($e, '.md')) {
            $files[] = $p;
        }
    }
};
$walk($root . '/docs');
sort($files);

// percentages the generated pages state
$allowed = [];
foreach ([$root . '/docs/project/_generated/metrics.md', $root . '/docs/project/_generated/usage.md', $root . '/docs/project/numpy-scipy-coverage.md'] as $g) {
    if (is_file($g) && preg_match_all('/(\d+(?:\.\d+)?) ?%/', (string) file_get_contents($g), $m)) {
        foreach ($m[1] as $v) {
            $allowed[(string) (float) $v] = true;
        }
    }
}

$phrases = '/numpy for php|scipy equivalent|drop-in|portable numpy|(?:numpy|scipy)\b.{0,60}\bcomplete\b|\bcomplete\b.{0,60}\b(?:numpy|scipy)/i';
$coverage = '/cover|implement|support|parity|symbols|verified|in scope/i';
$findings = [];
foreach ($files as $path) {
    if (! is_file($path)) {
        continue;
    }
    $lines = file($path, FILE_IGNORE_NEW_LINES) ?: [];
    if (isset($lines[0]) && stripos($lines[0], 'generated by') !== false) {
        continue;
    }
    $rel = substr($path, strlen($root) + 1);
    $inCode = false;
    foreach ($lines as $i => $line) {
        if (str_starts_with(ltrim($line), '```')) {
            $inCode = ! $inCode;
            continue;
        }
        if ($inCode) {
            continue;
        }
        if (preg_match($phrases, $line, $m, PREG_OFFSET_CAPTURE)) {
            $before = strtolower(substr($line, max(0, $m[0][1] - 24), min(24, $m[0][1])));
            if (! preg_match("/\\b(not|no|never|isn't|is not)\\b/", $before)) {
                $findings[] = sprintf('%s:%d: claim "%s" (back it with the coverage page or remove it)', $rel, $i + 1, $m[0][0]);
            }
        }
        if (preg_match($coverage, $line) && preg_match_all('/(\d+(?:\.\d+)?) ?%/', $line, $pm)) {
            foreach ($pm[1] as $v) {
                if (! isset($allowed[(string) (float) $v])) {
                    $findings[] = sprintf('%s:%d: %s %% is not a figure of the generated coverage pages', $rel, $i + 1, $v);
                }
            }
        }
    }
}
foreach ($findings as $f) {
    echo $f, "\n";
}
echo count($findings) === 0 ? "claims-check: ok (" . count($files) . " files)\n" : count($findings) . " finding(s)\n";
exit(count($findings) === 0 ? 0 : 1);
