#!/usr/bin/env python3
"""Generate the kernel registry sources for element-wise functions declared in spec/*.yaml (ADR 0011).

    python3 tools/parity/gen_registry.py            # writes the files below
    python3 tools/parity/gen_registry.py --check    # fails if they are out of date

For every spec module with element-wise entries (`impl:`), it writes
    csrc/cxx/gen_<module>.cpp       one extern "C" element function per entry (and per integer loop)
    csrc/src/gen_<module>_table.c   the fn_def table the registry serves to both bindings
A module marked `internal: true` (spec/special_internal.yaml: SciPy's private ufuncs) gets the element
functions only. From all special modules it also writes
    csrc/cxx/gen_sc.hpp             namespace sc: the functions as C++ calls (sc::ndtr(x), sc::_binom_pmf(k, n, p)),
                                    the same code the registry runs, for the scipy.stats distributions
"""
import json, os, sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
HEADER = '/* Generated by tools/parity/gen_registry.py from spec/{src}. Do not edit. */\n'


def cstr(s):
    return json.dumps(s, ensure_ascii=True)


def render(module, src, entries):
    cpp = [HEADER.format(src=src), '#include "special_common.hpp"', '']
    c = [HEADER.format(src=src), '#include "fn.h"', '']
    decls, rows = [], []
    for e in entries:
        if 'impl' not in e:
            continue
        sym = f"tsr_{module}_{e['name']}"
        nout = len(e['outs'])
        impl, int_impl = e['impl'], e.get('int_impl')
        if e.get('guard'):
            # inputs on which SciPy's own code crashes or hangs (tools/parity/crashes-<module>.json): NaN instead
            nan = ' '.join(f'o[{k}] = NAN;' for k in range(nout))
            impl = f'if ({e["guard"]}) {{ {nan} }} else {{ {impl} }}'
            if int_impl:
                int_impl = f'if ({e["guard"]}) {{ {nan} }} else {{ {int_impl} }}'
        cpp.append(f'extern "C" void {sym}(const void *, const double *i, double *o) {{ TSR_GUARD({nout}, {impl}) }}')
        decls.append(f'void {sym}(const void *, const double *, double *);')
        elem_int, mask = 'NULL', 0
        if e.get('int_impl'):
            cpp.append(f'extern "C" void {sym}__int(const void *, const double *i, double *o) {{ TSR_GUARD({nout}, {int_impl}) }}')
            decls.append(f'void {sym}__int(const void *, const double *, double *);')
            elem_int = f'{sym}__int'
            for k in e.get('int_args', []):
                mask |= 1 << k
        args = ', '.join(e['args'])
        outs = ', '.join(e['outs'])
        if e.get('cplx_impl'):
            # a complex128 loop: in/out are interleaved (re, im); TSR_GUARD fills 2*nout doubles with NaN on error
            cpp.append(f'extern "C" void {sym}__cplx(const void *, const double *i, double *o) {{ TSR_GUARD({2 * nout}, {e["cplx_impl"]}) }}')
            decls.append(f'void {sym}__cplx(const void *, const double *, double *);')
            rows.append(f'    UFUNC_C({cstr(module + "." + e["name"])}, {len(e["args"])}, {nout}, {cstr(args)}, {cstr(outs)}, '
                        f'{sym}, {elem_int}, {mask}, {sym}__cplx, {cstr(e.get("doc", ""))}),')
        else:
            rows.append(f'    UFUNCI({cstr(module + "." + e["name"])}, {len(e["args"])}, {nout}, {cstr(args)}, {cstr(outs)}, '
                        f'{sym}, {elem_int}, {mask}, {cstr(e.get("doc", ""))}),')
    c += decls + ['', f'const fn_def TSR_GEN_{module.upper()}[] = {{'] + rows + ['};',
          f'const fn_table TSR_GEN_{module.upper()}_TABLE = {{TSR_GEN_{module.upper()}, (int)(sizeof TSR_GEN_{module.upper()} / sizeof TSR_GEN_{module.upper()}[0])}};', '']
    return '\n'.join(cpp) + '\n', '\n'.join(c)


def sc_header(specs):
    """namespace sc: scipy.special as C++ functions over the generated element functions"""
    out = [HEADER.format(src='special*.yaml'), '#pragma once', '', 'extern "C" {']
    body = ['}', '', 'namespace sc {', '']
    for module, entries in specs:
        for e in entries:
            if 'impl' not in e:
                continue
            sym = f"tsr_{module}_{e['name']}"
            nin, nout = len(e['args']), len(e['outs'])
            out.append(f'void {sym}(const void *, const double *, double *);')
            params = ', '.join(f'double x{k}' for k in range(nin))
            ins = ', '.join(f'x{k}' for k in range(nin)) or '0'
            if nout == 1:
                body.append(f'inline double {e["name"]}({params}) {{ const double i[{max(nin, 1)}] = {{{ins}}}; double o[1]; {sym}(nullptr, i, o); return o[0]; }}')
            else:
                refs = ', '.join(f'double &y{k}' for k in range(nout))
                sets = ' '.join(f'y{k} = o[{k}];' for k in range(nout))
                body.append(f'inline void {e["name"]}({params}, {refs}) {{ const double i[{max(nin, 1)}] = {{{ins}}}; double o[{nout}]; {sym}(nullptr, i, o); {sets} }}')
    body += ['', '}  // namespace sc', '']
    return '\n'.join(out + body)


def main():
    check = '--check' in sys.argv
    stale = []
    sc_specs = []
    for fname in sorted(os.listdir(os.path.join(ROOT, 'spec'))):
        if not fname.endswith('.yaml'):
            continue
        doc = yaml.safe_load(open(os.path.join(ROOT, 'spec', fname)))
        entries = [e for e in doc.get('functions', []) if 'impl' in e]
        if not entries:
            continue
        module = doc['module']
        cpp, c = render(module, fname, entries)
        if module.startswith('special'):
            sc_specs.append((module, entries))
        if doc.get('internal'):
            # one translation unit for all special functions (the libraries are not multi-TU safe): the
            # internal functions are included by gen_special.cpp
            files = [(f'csrc/cxx/gen_{module}.inc', cpp.replace('#include "special_common.hpp"\n', ''))]
        else:
            if module == 'special':
                # the xsf/scipy code is not multi-TU safe, so the internal ufuncs and the complex-valued routines
                # (special_complex.inc: wofz, hankel1/2, lambertw) share gen_special.cpp's translation unit
                cpp += '\n#include "gen_special_internal.inc"\n#include "special_complex.inc"\n'
            files = [(f'csrc/cxx/gen_{module}.cpp', cpp), (f'csrc/src/gen_{module}_table.c', c)]
        for path, text in files:
            full = os.path.join(ROOT, path)
            old = open(full).read() if os.path.exists(full) else None
            if old != text:
                stale.append(path)
                if not check:
                    open(full, 'w').write(text)
        print(f'{module}: {len(entries)} functions')
    hdr = sc_header(sc_specs)
    full = os.path.join(ROOT, 'csrc/cxx/gen_sc.hpp')
    if not os.path.exists(full) or open(full).read() != hdr:
        stale.append('csrc/cxx/gen_sc.hpp')
        if not check:
            open(full, 'w').write(hdr)
    if check and stale:
        print('out of date:', ' '.join(stale))
        sys.exit(1)


if __name__ == '__main__':
    main()
