<?php

/**
 * Run the NumPy/SciPy parity fixtures (tests/fixtures/parity/*.json) against one backend and record the
 * outcome per function in tools/parity/results.json (read by tools/parity/report.py).
 *
 *   php -d ffi.enable=1 tools/parity/run-tests.php --backend=ffi [--module=special] [--only=gammainc,jv] [-v]
 *   php -d extension=tessero tools/parity/run-tests.php --backend=ext
 *   ... --fixtures=<file.json> --no-record     # one fixture file; do not update results.json
 *   ... --preload=DIR/Stats.php                # façades generated with gen-facades.php --out=DIR
 *
 * Element-wise modules (`blocks`, generated by fixtures.py): every block is checked twice: once with arrays (the element loop, broadcasting, float64) and once with
 * PHP scalars on a sample of rows (the scalar path). A value passes when both are NaN, both are the same
 * infinity, or |got - want| <= atol + rtol |want| (defaults: rtol 1e-13, atol 0; per-function overrides in
 * the spec's `tol:`). Call-based modules (`calls`, generated by fixtures_np.py) replay each recorded call with
 * its keyword arguments as PHP named arguments and compare the result's kind (int/float/bool), shape and values
 * (default rtol 1e-12; NumPy's summation order is replicated, so most results are exact). Exit status 1 when
 * anything fails.
 */

declare(strict_types=1);

$opt = [];
foreach (array_slice($argv, 1) as $a) {
    if (preg_match('/^--([a-z-]+)(?:=(.*))?$/', $a, $m)) {
        $opt[$m[1]] = $m[2] ?? true;
    } elseif ($a === '-v') {
        $opt['verbose'] = true;
    }
}
// --preload=a.php,b.php: façade classes generated for a work-in-progress library (gen-facades.php --out=DIR)
foreach (isset($opt['preload']) ? explode(',', (string) $opt['preload']) : [] as $f) {
    require_once $f;
}
require dirname(__DIR__, 2) . '/tests/autoload.php';
$backend = $opt['backend'] ?? (extension_loaded('tessero') ? 'ext' : 'ffi');
$only = isset($opt['only']) ? array_flip(explode(',', (string) $opt['only'])) : null;
$verbose = isset($opt['verbose']);
$root = dirname(__DIR__, 2);
$files = isset($opt['fixtures']) ? [(string) $opt['fixtures']] : (glob("{$root}/tests/fixtures/parity/*.json") ?: []);
$record = ! isset($opt['no-record']);
if (isset($opt['module'])) {
    $files = array_filter($files, static fn (string $f): bool => basename($f, '.json') === $opt['module']);
}

$classes = [
    'ffi' => ['special' => \Tessero\Special::class, 'stats' => \Tessero\Stats::class, 'np' => \Tessero\Np::class,
        'linalg' => \Tessero\Linalg::class, 'slinalg' => \Tessero\ScipyLinalg::class, 'distance' => \Tessero\Distance::class, 'sparse' => \Tessero\Sparse::class, 'signal' => \Tessero\Signal::class, 'windows' => \Tessero\SignalWindows::class, 'ndimage' => \Tessero\Ndimage::class, 'csgraph' => \Tessero\Csgraph::class, 'interpolate' => \Tessero\Interpolate::class, 'cluster' => \Tessero\Cluster::class, 'npoly' => \Tessero\Polynomial::class, 'fft' => \Tessero\Fft\Fft::class, 'random' => \Tessero\Random\Generator::class],
    'ext' => ['special' => 'Tessero\\Ext\\Special', 'stats' => 'Tessero\\Ext\\Stats', 'np' => 'Tessero\\Ext\\Np',
        'linalg' => 'Tessero\\Ext\\Linalg', 'slinalg' => 'Tessero\\Ext\\ScipyLinalg', 'distance' => 'Tessero\\Ext\\Distance', 'sparse' => 'Tessero\\Ext\\Sparse', 'signal' => 'Tessero\\Ext\\Signal', 'windows' => 'Tessero\\Ext\\SignalWindows', 'ndimage' => 'Tessero\\Ext\\Ndimage', 'csgraph' => 'Tessero\\Ext\\Csgraph', 'interpolate' => 'Tessero\\Ext\\Interpolate', 'cluster' => 'Tessero\\Ext\\Cluster', 'npoly' => 'Tessero\\Ext\\Polynomial', 'fft' => 'Tessero\\Ext\\Fft\\Fft', 'random' => 'Tessero\\Ext\\Random\\Generator'],
];
$arrayClass = $backend === 'ext' ? 'Tessero\\Ext\\NDArray' : \Tessero\NDArray::class;

function dec(mixed $v): ?float
{
    return match ($v) {
        'nan' => NAN, 'inf' => INF, '-inf' => -INF, 'undef' => null, default => (float) $v,
    };
}

function camelName(string $s): string
{
    $parts = explode('_', $s);
    $out = array_shift($parts);
    foreach ($parts as $p) {
        $out .= $p === '' ? '_' : ucfirst($p);   /* gen-facades.php camel(): lambda_ stays lambda_ */
    }

    return $out;
}

/** @return array{bool, float} ok, relative error (0 when exact) */
function close(float $got, float $want, float $rtol, float $atol): array
{
    if (is_nan($want)) {
        return [is_nan($got), is_nan($got) ? 0.0 : INF];
    }
    if (is_infinite($want)) {
        return [$got === $want, $got === $want ? 0.0 : INF];
    }
    if (is_nan($got) || is_infinite($got)) {
        return [false, INF];
    }
    $err = abs($got - $want);
    $rel = $want != 0.0 ? $err / abs($want) : $err;

    return [$err <= $atol + $rtol * abs($want), $rel];
}

/** Per-function tolerances for call fixtures, each with its reason (the default is rtol 1e-12). */
const CALL_RTOL = [
    // Generator draws run NumPy's own C code on the same PCG64 stream and, with the fixtures generated in the
    // pinned environment (tools/parity/fixture_env.py: NumPy's float64 loops are the C library's), must be
    // bit-identical
    'random' => 0.0,
    // LAPACK-backed polynomial helpers: a different LAPACK may differ in the last few digits (ADR 0012)
    'polyfit' => 1e-6,
    'roots' => 1e-6,
    'chebfit' => 1e-6, 'legfit' => 1e-6, 'lagfit' => 1e-6, 'hermfit' => 1e-6, 'hermefit' => 1e-6,
    // Gauss quadrature: eigenvalues of the companion + one Newton step may differ in the last couple of digits
    'leggauss' => 1e-9, 'laggauss' => 1e-9, 'hermgauss' => 1e-9, 'hermegauss' => 1e-9,
    // tensor B-spline: per-dimension de Boor composition sums in a different order than SciPy's direct tensor eval
    'NdBSpline' => 1e-9,
    // Newton-Cotes weights: solving the moment Vandermonde in float64 vs SciPy's exact-rational weights
    'newton_cotes' => 1e-6,
    // gaussian_kde: Cholesky-whitening sum accumulates slightly differently than SciPy's vectorized form
    'gaussian_kde' => 1e-9,
    // vonmises_fisher: normalization uses the modified Bessel I_v, which differs from SciPy in the last digits
    'vonmises_fisher' => 1e-9,
    // matrix-variate densities: Cholesky logdets + dgesv traces + multivariate log-gamma vs SciPy's own
    'matrix_normal' => 1e-8, 'wishart' => 1e-8, 'invwishart' => 1e-8,
];
// absolute tolerances: polyfit/roots/*fit coefficients can be legitimately ~0, where a relative tolerance is meaningless
const CALL_ATOL = ['polyfit' => 1e-8, 'roots' => 1e-8,
    'chebfit' => 1e-8, 'legfit' => 1e-8, 'lagfit' => 1e-8, 'hermfit' => 1e-8, 'hermefit' => 1e-8,
    'leggauss' => 1e-11, 'laggauss' => 1e-11, 'hermgauss' => 1e-11, 'hermegauss' => 1e-11];

function decodeValue(mixed $v, string $arrayClass): mixed
{
    if (! is_array($v)) {
        return is_string($v) ? dec($v) : $v;
    }
    if (isset($v['s'])) {
        return $v['s'];
    }
    if (array_key_exists('rng', $v)) {                         // a seeded numpy.random.default_rng
        $gen = str_contains($arrayClass, 'Ext') ? 'Tessero\\Ext\\Random\\Generator' : \Tessero\Random\Generator::class;

        return $gen::defaultRng($v['rng']);
    }
    if (array_key_exists('list', $v)) {
        return array_map(static fn ($x) => decodeValue($x, $arrayClass), $v['list']);
    }
    $data = array_map(static fn ($x) => is_string($x) ? dec($x) : $x, $v['data']);
    if (($v['dtype'] ?? '') === 'complex128') {          // interleaved [re, im, ...] -> a complex NDArray
        $re = [];
        $im = [];
        foreach ($data as $j => $val) {
            if ($j % 2 === 0) {
                $re[] = $val;
            } else {
                $im[] = $val;
            }
        }
        $a = $arrayClass::complex($arrayClass::array($re, 'float64'), $arrayClass::array($im, 'float64'));

        return $v['shape'] === [count($re)] ? $a : $a->reshape($v['shape']);
    }
    $a = $arrayClass::array($data, $v['dtype']);

    return $v['shape'] === [count($data)] ? $a : $a->reshape($v['shape']);
}

function kindOf(mixed $v): string
{
    return is_bool($v) ? 'bool' : (is_int($v) ? 'int' : 'float');
}

function dtypeKind(object $a): string
{
    $d = $a->dtype();
    $d = is_string($d) ? $d : strtolower($d->name);

    return str_starts_with($d, 'int') || str_starts_with($d, 'uint') ? 'int' : ($d === 'bool' ? 'bool' : 'float');
}

function describeCall(array $case): string
{
    $f = static function ($v) use (&$f): string {
        if (! is_array($v)) {
            return var_export($v, true);
        }
        if (isset($v['s'])) {
            return "'{$v['s']}'";
        }
        if (array_key_exists('list', $v)) {
            return '[' . implode(', ', array_map($f, $v['list'])) . ']';
        }
        $n = count($v['data']);

        return $v['dtype'] . '(' . implode('x', $v['shape']) . ')' . ($n <= 6 ? json_encode($v['data']) : '');
    };
    $parts = array_map($f, $case['args']);
    foreach ($case['kwargs'] as $k => $v) {
        $parts[] = camelName($k) . ': ' . $f($v);
    }

    return '(' . implode(', ', $parts) . ')';
}

/** Compare one expected (encoded) value with what Tessero returned; null when they agree. */
function compareValue(mixed $want, mixed $got, float $rtol, float $atol, float &$worst): ?string
{
    if (is_array($want) && array_key_exists('list', $want)) {    // a pair (support, interval)
        if (! is_array($got) || count($got) !== count($want['list'])) {
            return 'expected a list of ' . count($want['list']) . ' values, got ' . get_debug_type($got);
        }
        foreach (array_values($want['list']) as $i => $w) {
            $p = compareValue($w, array_values($got)[$i], $rtol, $atol, $worst);
            if ($p !== null) {
                return "[{$i}] {$p}";
            }
        }

        return null;
    }
    if (is_array($want) && isset($want['dict'])) {
        if (! is_array($got)) {
            return 'expected keys ' . implode(',', array_keys($want['dict'])) . ', got ' . get_debug_type($got);
        }
        if (array_keys($want['dict']) !== array_keys($got)) {
            return 'expected keys ' . implode(',', array_keys($want['dict'])) . ', got ' . implode(',', array_keys($got));
        }
        foreach ($want['dict'] as $k => $w) {
            $p = compareValue($w, $got[$k], $rtol, $atol, $worst);
            if ($p !== null) {
                return "[{$k}] {$p}";
            }
        }

        return null;
    }
    if (is_array($want) && isset($want['s'])) {              // a string result (e.g. a dtype name)
        return is_string($got) && $got === $want['s'] ? null : 'got ' . var_export($got, true) . " want '{$want['s']}'";
    }
    if (is_array($want)) {                                   // an array
        if (! is_object($got)) {
            return 'expected an array of shape (' . implode(',', $want['shape']) . '), got ' . var_export($got, true);
        }
        if ($got->shape() !== $want['shape']) {
            return 'shape (' . implode(',', $got->shape()) . ') instead of (' . implode(',', $want['shape']) . ')';
        }
        if ($want['dtype'] === 'complex128') {              // interleaved [re, im, ...]; compare parts (toList of
            $re = $got->real()->toList();                   // a complex array is not portable across backends)
            $im = $got->imag()->toList();
            $nel = intdiv(count($want['data']), 2);
            for ($i = 0; $i < $nel; $i++) {
                $wr = is_string($want['data'][2 * $i]) ? dec($want['data'][2 * $i]) : $want['data'][2 * $i];
                $wi = is_string($want['data'][2 * $i + 1]) ? dec($want['data'][2 * $i + 1]) : $want['data'][2 * $i + 1];
                [$ok1, $r1] = close((float) $re[$i], (float) $wr, $rtol, $atol);
                [$ok2, $r2] = close((float) $im[$i], (float) $wi, $rtol, $atol);
                if ($r1 !== INF && $r1 > $worst) { $worst = $r1; }
                if ($r2 !== INF && $r2 > $worst) { $worst = $r2; }
                if (! $ok1 || ! $ok2) {
                    return sprintf('element %d: got %.17g%+.17gi want %.17g%+.17gi', $i, (float) $re[$i], (float) $im[$i], (float) $wr, (float) $wi);
                }
            }

            return null;
        }
        $wk = $want['dtype'] === 'int64' ? 'int' : ($want['dtype'] === 'bool' ? 'bool' : 'float');
        if (dtypeKind($got) !== $wk) {
            return 'dtype kind ' . dtypeKind($got) . " instead of {$wk}";
        }
        $vals = $got->toList();
        foreach ($want['data'] as $i => $w) {
            $w = is_string($w) ? dec($w) : $w;
            if (is_int($w) && is_int($vals[$i])) {            // integers compare exactly (float64 rounds above 2^53)
                if ($vals[$i] !== $w) {
                    return sprintf('element %d: got %d want %d', $i, $vals[$i], $w);
                }
                continue;
            }
            [$ok, $rel] = close((float) $vals[$i], (float) $w, $rtol, $atol);
            if ($rel !== INF && $rel > $worst) {
                $worst = $rel;
            }
            if (! $ok) {
                return sprintf('element %d: got %.17g want %.17g', $i, $vals[$i], $w);
            }
        }

        return null;
    }
    $w = is_string($want) ? dec($want) : $want;
    if (is_object($got)) {
        return 'expected a scalar, got an array of shape (' . implode(',', $got->shape()) . ')';
    }
    if (kindOf($got) !== kindOf($w) && ! ($GLOBALS['scalarKindLoose'] && ! is_bool($got) && ! is_bool($w))) {
        return 'scalar kind ' . kindOf($got) . ' instead of ' . kindOf($w) . sprintf(' (%s vs %s)', var_export($got, true), var_export($w, true));
    }
    if (is_int($got) && is_int($w)) {
        return $got === $w ? null : sprintf('got %d want %d', $got, $w);
    }
    [$ok, $rel] = close((float) $got, (float) $w, $rtol, $atol);
    if ($rel !== INF && $rel > $worst) {
        $worst = $rel;
    }

    return $ok ? null : sprintf('got %.17g want %.17g', $got, $w);
}

/** partition / argpartition: NumPy fixes only the kth element and the invariant, so check exactly that. */
function comparePartition(string $method, array $case, mixed $got, string $arrayClass): ?string
{
    $want = $case['expect'];
    if (! is_object($got) || $got->shape() !== $want['shape']) {
        return 'shape mismatch';
    }
    $a = $case['args'][0];
    $in = array_map(static fn ($x) => is_string($x) ? dec($x) : $x, $a['data']);
    $shape = $a['shape'];
    $axis = $case['kwargs']['axis'] ?? -1;
    $nd = count($shape);
    $axis = $axis < 0 ? $axis + $nd : $axis;
    $kth = $case['args'][1];
    $kths = is_array($kth) ? array_map('intval', $kth['data'] ?? $kth['list']) : [(int) $kth];
    $g = $got->toList();
    $strides = [];
    $st = 1;
    for ($d = $nd - 1; $d >= 0; $d--) {
        $strides[$d] = $st;
        $st *= $shape[$d];
    }
    $len = $shape[$axis];
    $total = array_product($shape);
    $key = static fn (float $x): float => is_nan($x) ? INF : $x;
    for ($base = 0; $base < $total; $base++) {
        if (intdiv($base, $strides[$axis]) % $len !== 0) {
            continue;                                         // not the start of a lane
        }
        $lane = [];
        $orig = [];
        for ($i = 0; $i < $len; $i++) {
            $idx = $base + $i * $strides[$axis];
            $v = $g[$idx];
            if ($method === 'argpartition') {
                if (! is_int($v) || $v < 0 || $v >= $len) {
                    return "index {$v} out of range";
                }
                $v = $in[$base + $v * $strides[$axis]];
            }
            $lane[] = (float) $v;
            $orig[] = (float) $in[$idx];
        }
        $s1 = $orig;
        $s2 = $lane;
        usort($s1, static fn ($x, $y) => $key($x) <=> $key($y));
        usort($s2, static fn ($x, $y) => $key($x) <=> $key($y));
        if (array_map('strval', $s1) !== array_map('strval', $s2)) {
            return 'not a permutation of the input lane';
        }
        foreach ($kths as $k) {
            $k = $k < 0 ? $k + $len : $k;
            if (strval($lane[$k]) !== strval($s1[$k])) {
                return "kth {$k}: got {$lane[$k]} want {$s1[$k]}";
            }
            for ($i = 0; $i < $len; $i++) {
                if (($i < $k && $key($lane[$i]) > $key($lane[$k])) || ($i > $k && $key($lane[$i]) < $key($lane[$k]))) {
                    return "partition invariant broken at {$i} around kth {$k}";
                }
            }
        }
    }

    return null;
}

function runCall(string|object $class, string $method, array $case, string $arrayClass, float $rtol, float $atol, float &$worst): ?string
{
    $args = array_map(static fn ($v) => decodeValue($v, $arrayClass), $case['args']);
    foreach ($case['kwargs'] as $k => $v) {
        $args[camelName($k)] = decodeValue($v, $arrayClass);
    }
    $want = $case['expect'];
    try {
        $got = [$class, $method](...$args);
        if (($case['compare'] ?? 'tol') === 'inplace' && ! (is_array($want) && isset($want['error']))) {
            // numpy.put, place, copyto ...: None is returned and the first argument holds the result
            if ($got !== null) {
                return 'expected null (the array is modified in place), got ' . get_debug_type($got);
            }
            $got = $args[0];
        }
    } catch (\Throwable $e) {
        if (is_array($want) && isset($want['error'])) {
            return null;                                      // NumPy raises too
        }

        return 'threw ' . get_class($e) . ': ' . $e->getMessage();
    }
    if (is_array($want) && isset($want['error'])) {
        return "NumPy raises {$want['error']}, Tessero returned " . get_debug_type($got);
    }
    if (($case['compare'] ?? 'tol') === 'shape') {         // numpy.empty_like: only the shape and dtype are specified
        if (! is_object($got) || ! is_array($want) || ! isset($want['shape'])) {
            return is_object($got) || ! is_array($want) ? null : 'expected an array';
        }
        $wk = $want['dtype'] === 'int64' ? 'int' : ($want['dtype'] === 'bool' ? 'bool' : 'float');

        return $got->shape() !== $want['shape'] ? 'shape mismatch' : (dtypeKind($got) !== $wk ? 'dtype kind ' . dtypeKind($got) . " instead of {$wk}" : null);
    }
    if (($case['compare'] ?? 'tol') === 'partition') {
        return comparePartition($method, $case, $got, $arrayClass);
    }
    if (($case['compare'] ?? 'tol') === 'sorted' && is_object($got) && is_array($want) && isset($want['data'])) {
        $key = static fn ($x): float => is_nan((float) $x) ? INF : (float) $x;
        $w = array_map(static fn ($x) => is_string($x) ? dec($x) : $x, $want['data']);
        usort($w, static fn ($a, $b) => $key($a) <=> $key($b));
        $want['data'] = $w;
        $vals = $got->toList();
        usort($vals, static fn ($a, $b) => $key($a) <=> $key($b));
        $got = $arrayClass::array($vals, $got->dtype());
    }

    return compareValue($want, $got, $rtol, $atol, $worst);
}

/** Rebuild a named objective (used by the scipy.optimize solver fixtures) as a PHP callable. */
function makeObjective(array $spec): callable
{
    return match ($spec['kind']) {
        'poly' => static function (float $x) use ($spec): float { $s = 0.0; $p = 1.0; foreach ($spec['c'] as $ck) { $s += $ck * $p; $p *= $x; } return $s; },
        'cosx' => static fn (float $x): float => cos($x) - $x,
        'gauss' => static fn (float $x): float => exp(-$x * $x),
        'sinx' => static fn (float $x): float => sin($x),
        'lorentz' => static fn (float $x): float => 1.0 / (1.0 + $x * $x),
        'rosen' => static function (array $x): float { $s = 0.0; for ($i = 0, $n = count($x); $i < $n - 1; $i++) { $s += 100.0 * ($x[$i + 1] - $x[$i] ** 2) ** 2 + (1.0 - $x[$i]) ** 2; } return $s; },
        // vector residuals for leastsq (data embedded in the spec)
        'linresid' => static function (array $p) use ($spec): array { $r = []; foreach ($spec['x'] as $i => $xi) { $r[] = $p[0] * $xi + $p[1] - $spec['y'][$i]; } return $r; },
        'expresid' => static function (array $p) use ($spec): array { $r = []; foreach ($spec['x'] as $i => $xi) { $r[] = $p[0] * exp($p[1] * $xi) + $p[2] - $spec['y'][$i]; } return $r; },
        'vecsys' => static fn (array $x): array => [$x[0] - 0.5 * cos($x[1]) - 0.5, $x[1] - 0.5 * sin($x[0]) - 0.3],
        default => throw new \RuntimeException("unknown objective '{$spec['kind']}'"),
    };
}

/** Structural equality for datetime fixtures: ints/bools/strings exact, floats within a small tolerance. */
function dtEqual(mixed $got, mixed $want): bool
{
    if (is_array($want)) {
        if (! is_array($got) || count($got) !== count($want)) {
            return false;
        }
        $got = array_values($got);
        foreach (array_values($want) as $i => $w) {
            if (! dtEqual($got[$i] ?? null, $w)) {
                return false;
            }
        }
        return true;
    }
    if (is_bool($want)) {
        return (bool) $got === $want;
    }
    if (is_int($want)) {
        return is_numeric($got) && (int) $got === $want;
    }
    if (is_float($want)) {
        return is_numeric($got) && abs((float) $got - $want) <= 1e-9;
    }
    return (string) $got === (string) $want;
}

/** Flatten a (possibly nested) numeric array to a flat list. */
function flattenNums(mixed $a): array
{
    $arr = is_array($a) ? $a : [$a];
    $out = [];
    array_walk_recursive($arr, static function ($v) use (&$out) { $out[] = $v; });
    return $out;
}

/** @param list<float> $got @param list<float> $want */
function vecClose(array $got, array $want, float $rtol): bool
{
    if (count($got) !== count($want)) {
        return false;
    }
    foreach ($want as $i => $w) {
        if (abs($got[$i] - $w) > $rtol * (1 + abs((float) $w))) {
            return false;
        }
    }
    return true;
}

/**
 * Run the scipy.optimize solver fixtures (brentq/newton/minimize/fmin): the pure-PHP solvers verified against
 * scipy on the current backend's process. Returns a status map keyed "optimize.<fn>".
 *
 * @param list<array<string, mixed>> $cases
 * @return array<string, string>
 */
function runSolverCases(array $cases, string $module, int &$checked, int &$failures): array
{
    $status = [];
    foreach ($cases as $c) {
        $fn = $c['fn'];
        $key = "{$module}.{$fn}";
        $rtol = (float) ($c['rtol'] ?? 1e-9);
        $obj = isset($c['obj']) ? makeObjective($c['obj']) : null;
        $checked++;
        $ok = false;
        $msg = '';
        try {
            if ($fn === 'brentq') {
                $got = \Tessero\Optimize\Root::brentq($obj, (float) $c['a'], (float) $c['b']);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'bisect') {
                $got = \Tessero\Optimize\Root::bisect($obj, (float) $c['a'], (float) $c['b']);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'brenth') {
                $got = \Tessero\Optimize\Root::brenth($obj, (float) $c['a'], (float) $c['b']);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'ridder') {
                $got = \Tessero\Optimize\Root::ridder($obj, (float) $c['a'], (float) $c['b']);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'toms748') {
                $got = \Tessero\Optimize\Root::toms748($obj, (float) $c['a'], (float) $c['b']);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'root_scalar') {
                $bracket = isset($c['bracket']) ? array_map('floatval', $c['bracket']) : null;
                $r = \Tessero\Optimize\Root::rootScalar($obj, $c['method'] ?? null, $bracket, isset($c['x0']) ? (float) $c['x0'] : null);
                $got = $r['root'];
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'fminbound') {
                $got = \Tessero\Optimize\Minimize::fminbound($obj, (float) $c['a'], (float) $c['b']);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'minimize_scalar') {
                $bracket = isset($c['bracket']) ? array_map('floatval', $c['bracket']) : null;
                $bounds = isset($c['bounds']) ? array_map('floatval', $c['bounds']) : null;
                $got = \Tessero\Optimize\Minimize::minimizeScalar($obj, $bracket, $bounds, (string) ($c['method'] ?? ''))->x[0];
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'newton') {
                $got = \Tessero\Optimize\Root::newton($obj, (float) $c['x0']);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'minimize') {
                $got = \Tessero\Optimize\Minimize::minimize($obj, array_map('floatval', $c['x0']), null, (string) $c['method'])->x;
                $ok = vecClose($got, $c['expect'], $rtol);
            } elseif ($fn === 'fmin') {
                $got = \Tessero\Optimize\Minimize::fmin($obj, array_map('floatval', $c['x0']));
                $ok = vecClose($got, $c['expect'], $rtol);
            } elseif ($fn === 'quad') {
                $r = \Tessero\Integrate\Quad::quad($obj, (float) $c['a'], (float) $c['b']);
                $ok = abs($r[0] - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'leastsq') {
                $r = \Tessero\Optimize\LeastSquares::solve($obj, array_map('floatval', $c['x0']));
                $ok = vecClose($r['x'], $c['expect'], $rtol);
            } elseif ($fn === 'least_squares') {
                $r = \Tessero\Optimize\LeastSquares::leastSquares($obj, array_map('floatval', $c['x0']));
                $ok = vecClose($r->x, $c['expect'], $rtol);
            } elseif ($fn === 'nnls') {
                $r = \Tessero\Optimize\LeastSquares::nnls($c['A'], $c['b']);
                $ok = vecClose($r[0], $c['expect'], $rtol);
            } elseif ($fn === 'lsq_linear') {
                $r = \Tessero\Optimize\LeastSquares::lsqLinear($c['A'], $c['b']);
                $ok = vecClose($r->x, $c['expect'], $rtol);
            } elseif ($fn === 'root') {
                $got = \Tessero\Optimize\Root::root($obj, array_map('floatval', $c['x0']))->x;
                $ok = vecClose($got, $c['expect'], $rtol);
            } elseif ($fn === 'fsolve') {
                $got = \Tessero\Optimize\Root::fsolve($obj, array_map('floatval', $c['x0']));
                $ok = vecClose($got, $c['expect'], $rtol);
            } elseif ($fn === 'fixed_point') {
                $got = \Tessero\Optimize\Root::fixedPoint($obj, (float) $c['x0']);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'bracket') {
                $r = \Tessero\Optimize\Minimize::bracket($obj, (float) $c['a'], (float) $c['b']);
                $ok = vecClose([$r[0], $r[1], $r[2]], $c['expect'], $rtol);
            } elseif ($fn === 'linear_sum_assignment') {
                [$ri, $ci] = \Tessero\Optimize\Assignment::linearSumAssignment($c['cost'], (bool) ($c['maximize'] ?? false));
                $ok = array_map('intval', $ri) === array_map('intval', $c['expect_row']) && array_map('intval', $ci) === array_map('intval', $c['expect_col']);
            } elseif ($fn === 'rosen') {
                $got = \Tessero\Optimize\Minimize::rosen(array_map('floatval', $c['x']));
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'rosen_der') {
                $ok = vecClose(\Tessero\Optimize\Minimize::rosenDer(array_map('floatval', $c['x'])), $c['expect'], $rtol);
            } elseif ($fn === 'rosen_hess_prod') {
                $ok = vecClose(\Tessero\Optimize\Minimize::rosenHessProd(array_map('floatval', $c['x']), array_map('floatval', $c['p'])), $c['expect'], $rtol);
            } elseif ($fn === 'rosen_hess') {
                $H = \Tessero\Optimize\Minimize::rosenHess(array_map('floatval', $c['x']));
                $ok = vecClose(array_merge(...$H), array_merge(...$c['expect']), $rtol);   // flatten row-major
            } elseif ($fn === 'brent') {
                $got = \Tessero\Optimize\Minimize::brent($obj, isset($c['bracket']) ? array_map('floatval', $c['bracket']) : null);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'golden') {
                $got = \Tessero\Optimize\Minimize::golden($obj, isset($c['bracket']) ? array_map('floatval', $c['bracket']) : null);
                $ok = abs($got - $c['expect']) <= $rtol * (1 + abs((float) $c['expect']));
            } elseif ($fn === 'fmin_bfgs') {
                $ok = vecClose(\Tessero\Optimize\Minimize::fminBfgs($obj, array_map('floatval', $c['x0'])), $c['expect'], $rtol);
            }
        } catch (\Throwable $e) {
            $msg = $e->getMessage();
        }
        $status[$key] = ($status[$key] ?? 'pass') === 'fail' ? 'fail' : ($ok ? 'pass' : 'fail');
        if (! $ok) {
            $failures++;
            echo "FAIL {$key}: " . ($msg !== '' ? $msg : 'result did not match scipy') . "\n";
        }
    }
    return $status;
}

$resultsPath = "{$root}/tools/parity/results.json";
$results = is_file($resultsPath) ? (json_decode((string) file_get_contents($resultsPath), true) ?: []) : [];
$results[$backend] ??= [];
$results['max_rel'][$backend] ??= [];
$failures = 0;
$checked = 0;
$t0 = microtime(true);
foreach ($files as $file) {
    $data = json_decode((string) file_get_contents($file), true, 64, JSON_THROW_ON_ERROR);
    $module = $data['module'];
    if (isset($data['io_cases'])) {                          // numpy.loadtxt etc.: fixture provides the file content
        $np = $classes[$backend]['np'];
        $local = [];
        foreach ($data['io_cases'] as $c) {
            $key = "np.{$c['fn']}";
            $tmp = tempnam(sys_get_temp_dir(), 'tsrio');
            file_put_contents($tmp, isset($c['content_b64']) ? base64_decode($c['content_b64']) : $c['content']);
            $cargs = [$tmp];
            foreach (($c['kwargs'] ?? []) as $k => $v) {
                $cargs[camelName($k)] = decodeValue($v, $arrayClass);
            }
            $checked++;
            $w = 0.0;
            try {
                $got = [$np, camelName($c['fn'])](...$cargs);
                $p = compareValue($c['expect'], $got, 1e-12, 0.0, $w);
            } catch (\Throwable $e) {
                $p = 'threw ' . $e->getMessage();
            }
            @unlink($tmp);
            $local[$key] = ($local[$key] ?? 'pass') === 'fail' ? 'fail' : ($p === null ? 'pass' : 'fail');
            if ($p !== null) { $failures++; echo "FAIL {$key}: {$p}\n"; }
        }
        foreach ($local as $k => $s) { $results[$backend][$k] = $s; $results['max_rel'][$backend][$k] = null; }
        continue;
    }
    if (isset($data['datetime_cases'])) {                    // numpy datetime64 / busday / isnat (pure-PHP, int64 counts)
        $local = [];
        foreach ($data['datetime_cases'] as $c) {
            $key = "datetime.{$c['fn']}";
            $checked++;
            $args = $c['args'];
            foreach (($c['kwargs'] ?? []) as $k => $v) {
                $args[$k] = $v;                              // named args (unit, weekmask, holidays, roll, offset)
            }
            $ok = false; $msg = '';
            try {
                $got = [\Tessero\Datetime\Datetime::class, camelName($c['fn'])](...$args);
                $ok = dtEqual($got, $c['expect']);
                if (! $ok) { $msg = 'got ' . json_encode($got) . ' want ' . json_encode($c['expect']); }
            } catch (\Throwable $e) {
                $msg = $e->getMessage();
            }
            $local[$key] = ($local[$key] ?? 'pass') === 'fail' ? 'fail' : ($ok ? 'pass' : 'fail');
            if (! $ok) { $failures++; echo "FAIL {$key}: {$msg}\n"; }
        }
        foreach ($local as $k => $s) { $results[$backend][$k] = $s; $results['max_rel'][$backend][$k] = null; }
        continue;
    }
    if (isset($data['spatial_cases'])) {                     // scipy.spatial.cKDTree: construct a tree, then query
        $local = [];
        foreach ($data['spatial_cases'] as $c) {
            $key = "spatial.{$c['fn']}";
            $checked++;
            $ok = false; $msg = '';
            try {
                $tree = new \Tessero\Spatial\KDTree($c['data']);
                [$d, $i] = $tree->query($c['query'], (int) ($c['k'] ?? 1));
                $ok = vecClose(flattenNums($d), flattenNums($c['expect']['distances']), 1e-9)
                    && flattenNums($i) === flattenNums($c['expect']['indices']);
                if (! $ok) { $msg = 'distances or indices did not match scipy'; }
            } catch (\Throwable $e) {
                $msg = $e->getMessage();
            }
            $local[$key] = ($local[$key] ?? 'pass') === 'fail' ? 'fail' : ($ok ? 'pass' : 'fail');
            if (! $ok) { $failures++; echo "FAIL {$key}: {$msg}\n"; }
        }
        foreach ($local as $k => $s) { $results[$backend][$k] = $s; $results['max_rel'][$backend][$k] = null; }
        continue;
    }
    if (isset($data['solver_cases'])) {                      // scipy.optimize / scipy.integrate: callable objectives
        foreach (runSolverCases($data['solver_cases'], $module, $checked, $failures) as $k => $s) {
            $results[$backend][$k] = $s;
            $results['max_rel'][$backend][$k] = null;
        }
        continue;
    }
    if ($module === 'constants') {                           // scipy.constants: scalar constants + helper functions
        $allok = true;
        foreach ($data['values'] as $name => $v) {
            $checked++;
            $got = (float) constant("Tessero\\Constants::{$name}");
            if (abs($got - (float) $v) > 1e-12 * (1 + abs((float) $v))) { $allok = false; $failures++; echo "FAIL constants.{$name}: {$got} vs {$v}\n"; }
        }
        $results[$backend]['constants.values'] = $allok ? 'pass' : 'fail';
        $results['max_rel'][$backend]['constants.values'] = null;
        $helpers = [
            'convert_temperature' => static fn (array $c): float => \Tessero\Constants::convertTemperature((float) $c['val'], (string) $c['old'], (string) $c['new']),
            'lambda2nu' => static fn (array $c): float => \Tessero\Constants::lambda2nu((float) $c['x']),
            'nu2lambda' => static fn (array $c): float => \Tessero\Constants::nu2lambda((float) $c['x']),
        ];
        foreach ($helpers as $hn => $call) {
            $hok = true;
            foreach ($data[$hn] ?? [] as $c) {
                $checked++;
                if (abs($call($c) - (float) $c['expect']) > 1e-9 * (1 + abs((float) $c['expect']))) { $hok = false; $failures++; echo "FAIL constants.{$hn}\n"; }
            }
            $results[$backend]["constants.{$hn}"] = $hok ? 'pass' : 'fail';
            $results['max_rel'][$backend]["constants.{$hn}"] = null;
        }
        continue;
    }
    $class = $classes[$backend][$module] ?? null;
    if ($class === null || ! class_exists($class)) {
        fwrite(STDERR, "no {$module} class on the {$backend} backend\n");
        exit(2);
    }
    $status = [];
    $maxRel = [];
    // scipy.stats returns Python ints or floats for scalar results as its internals happen to produce them
    // (support() of a discrete distribution is (0, 5.0)); compare those as numbers
    $GLOBALS['scalarKindLoose'] = ($data['kind'] ?? '') === 'distributions';
    if (isset($data['calls'])) {
        foreach ($data['calls'] as $blk) {
            $fn = $blk['fn'];
            if ($only !== null && ! isset($only[$fn])) {
                continue;
            }
            $key = "{$module}.{$fn}";
            $method = camelName($fn);
            if (! method_exists($class, $method)) {       // not implemented on this backend: reported, not failed
                $status[$key] = 'missing';
                echo "MISSING {$key}: no {$class}::{$method}()\n";
                continue;
            }
            $rtol = (float) ($blk['tol']['rtol'] ?? CALL_RTOL[$module === 'random' ? 'random' : $fn] ?? 1e-12);
            $atol = (float) ($blk['tol']['atol'] ?? CALL_ATOL[$fn] ?? 0.0);
            $problems = [];
            $worst = 0.0;
            foreach ($blk['cases'] as $ci => $case) {
                if (isset($case['dist_args'])) {             // scipy.stats: calls on one frozen distribution
                    $dargs = array_map(static fn ($v) => decodeValue($v, $arrayClass), $case['dist_args']);
                    foreach ($case['dist_kwargs'] as $k => $v) {
                        $dargs[$k] = decodeValue($v, $arrayClass);
                    }
                    try {
                        $dist = $class::$method(...$dargs);
                    } catch (\Throwable $e) {
                        $problems[] = "case {$ci}: constructing threw " . get_class($e) . ': ' . $e->getMessage();
                        continue;
                    }
                    foreach ($case['calls'] as $k => $c) {
                        $checked++;
                        $p = runCall($dist, camelName($c['method']), $c, $arrayClass, $rtol, $atol, $worst);
                        if ($p !== null) {
                            $problems[] = "case {$ci} " . describeCall(['args' => $case['dist_args'], 'kwargs' => $case['dist_kwargs']])
                                . "->{$c['method']}" . describeCall($c) . ": {$p}";
                        }
                    }
                    continue;
                }
                if (isset($case['seed'])) {                   // Generator methods: one generator per seed, calls in order
                    $gen = $class::defaultRng($case['seed']);
                    foreach ($case['calls'] as $k => $c) {
                        $checked++;
                        $p = runCall($gen, camelName($fn), $c, $arrayClass, $rtol, $atol, $worst);
                        if ($p !== null) {
                            $problems[] = "seed {$case['seed']} call {$k} " . describeCall($c) . ": {$p}";
                        }
                    }
                    continue;
                }
                $checked++;
                // a per-call tolerance the generator derived from the call's own data (with its reason in "why")
                $crtol = isset($case['tol']['rtol']) ? max($rtol, (float) $case['tol']['rtol']) : $rtol;
                $p = runCall($class, camelName($fn), $case, $arrayClass, $crtol, $atol, $worst);
                if ($p !== null) {
                    $problems[] = "call {$ci} " . describeCall($case) . ": {$p}";
                }
            }
            $status[$key] = $problems === [] ? 'pass' : 'fail';
            $maxRel[$key] = $worst;
            if ($problems !== []) {
                $failures++;
                echo "FAIL {$key}: " . count($problems) . ' of ' . count($blk['cases']) . " call(s)\n";
                foreach (array_slice($problems, 0, $verbose ? 20 : 3) as $p) {
                    echo "    {$p}\n";
                }
            }
        }
    }
    foreach ($data['blocks'] ?? [] as $blk) {
        $fn = $blk['fn'];
        if ($only !== null && ! isset($only[$fn])) {
            continue;
        }
        $key = "{$module}.{$fn}";
        if (! method_exists($class, camelName($fn))) {
            $status[$key] = 'missing';
            echo "MISSING {$key}: no {$class}::" . camelName($fn) . "()\n";
            continue;
        }
        $status[$key] ??= 'pass';
        $maxRel[$key] ??= 0.0;
        $rtol = (float) ($blk['tol']['rtol'] ?? 1e-13);
        $atol = (float) ($blk['tol']['atol'] ?? 0.0);
        $method = camelName($fn);
        $isInt = $blk['int'];
        $cols = [];
        foreach ($blk['args'] as $c) {
            $allInt = $isInt && array_reduce($c, static fn (bool $acc, mixed $v): bool => $acc && is_int($v), true);
            $cols[] = $allInt ? $c : array_map('dec', $c);
        }
        // "undef": SciPy's own code has undefined behaviour on that row (tools/parity/ub_scan.py): not compared
        $expect = array_map(static fn (array $c): array => array_map('dec', $c), $blk['expect']);
        $nrows = count($cols[0] ?? []);
        $nout = count($expect);
        $problems = [];
        // arrays
        try {
            $args = [];
            foreach ($cols as $c) {
                $args[] = $arrayClass::array($c, is_int($c[0] ?? 0.0) && $isInt ? 'int64' : 'float64');
            }
            $r = $class::$method(...$args);
            $outs = $nout === 1 ? [$r] : array_values($r);
            foreach ($outs as $o => $arr) {
                $got = $arr->toList();
                for ($i = 0; $i < $nrows; $i++) {
                    if ($expect[$o][$i] === null) {
                        continue;
                    }
                    [$ok, $rel] = close((float) $got[$i], $expect[$o][$i], $rtol, $atol);
                    $checked++;
                    if ($rel !== INF && $rel > $maxRel[$key]) {
                        $maxRel[$key] = $rel;
                    }
                    if (! $ok) {
                        $problems[] = sprintf('array row %d out %d: args (%s) got %.17g want %.17g', $i, $o,
                            implode(', ', array_map(static fn (array $c) => var_export($c[$i], true), $cols)), $got[$i], $expect[$o][$i]);
                    }
                }
            }
        } catch (\Throwable $e) {
            $problems[] = 'array call threw ' . get_class($e) . ': ' . $e->getMessage();
        }
        // scalars (a sample)
        $step = max(1, intdiv($nrows, 40));
        for ($i = 0; $i < $nrows; $i += $step) {
            $sargs = array_map(static fn (array $c) => $c[$i], $cols);
            try {
                $r = $class::$method(...$sargs);
                $outs = $nout === 1 ? [$r] : array_values($r);
                foreach ($outs as $o => $v) {
                    if ($expect[$o][$i] === null) {
                        continue;
                    }
                    [$ok] = close((float) $v, $expect[$o][$i], $rtol, $atol);
                    $checked++;
                    if (! $ok) {
                        $problems[] = sprintf('scalar row %d out %d: args (%s) got %.17g want %.17g', $i, $o,
                            implode(', ', array_map(static fn ($v) => var_export($v, true), $sargs)), $v, $expect[$o][$i]);
                    }
                }
            } catch (\Throwable $e) {
                $problems[] = "scalar row {$i} threw " . get_class($e) . ': ' . $e->getMessage();
            }
        }
        if ($problems !== []) {
            $status[$key] = 'fail';
            $failures++;
            echo "FAIL {$key}" . ($isInt ? ' (integer loop)' : '') . ': ' . count($problems) . " mismatch(es)\n";
            foreach (array_slice($problems, 0, $verbose ? 20 : 3) as $p) {
                echo "    {$p}\n";
            }
        }
    }
    foreach ($status as $k => $s) {
        $results[$backend][$k] = $s;
        $results['max_rel'][$backend][$k] = $maxRel[$k] ?? null;
    }
}
ksort($results[$backend]);
if ($record) {
    file_put_contents($resultsPath, json_encode($results, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n");
}
$pass = count(array_filter($results[$backend], static fn ($s) => $s === 'pass'));
$missing = count(array_filter($results[$backend], static fn ($s) => $s === 'missing'));
printf("%s: %d functions pass, %d fail, %d not implemented; %d values checked in %.1fs\n", $backend, $pass,
    count($results[$backend]) - $pass - $missing, $missing, $checked, microtime(true) - $t0);
exit($failures > 0 ? 1 : 0);
